### ISSUE TITLE
[BUG] Connection OpenAIConnection in tool with custom_llm not initialized

### ISSUE THREAD

**Issue by ArtyomZemlyak** [microsoft/promptflow#1032]
**Describe the bug**
Connection `OpenAIConnection` in tool with `custom_llm` not initialized.

```
Traceback (most recent call last):
  File "/home/kuruhuru/dev/llm/pf/os-llm-tool/os_llm_tool/tools/os_llm.py", line 195, in completion
    return OpenOpenAI(connection).completion(
  File "/home/kuruhuru/dev/llm/pf/os-llm-tool/os_llm_tool/tools/os_llm.py", line 37, in __init__
    self._connection_dict = dict(self.connection)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

Flow test failed with UserErrorException: ValueError: Execution failure in 'reformulate_question': (ValueError) dictionary update sequence element #0 has length 1; 2 is required
```

Can be fixed:
```python
class OpenOpenAI(ToolProvider):
    def __init__(self, connection: OpenAIConnection):
        super().__init__()

        ##### Fix: 
        if isinstance(connection, str):
            client = PFClient()
            connection = client.connections.get(name=connection)
        #####

        self.connection = connection
        self._connection_dict = dict(self.connection)
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create tool with `custom_llm` type and some of connection (like `OpenAIConnection`)
2. Add tool to flow
3. Run flow
4. Error occured

**Environment Information**
 - Promptflow Package Version using `pf -v`: 0.1.0b8
 - Operating System: Ubuntu 20.04
 - Python Version using `python --version`: Python 3.9.18
 - VS Code version. v1.84.1
 - Prompt Flow extension version. v1.3.1

**Comment by thy09** [comment]
@ArtyomZemlyak Can you share more details how did you hit this case? The connection would be converted to the object OpenAIConnection before calling your init function, I didn't hit the similar issue.

**Comment by ArtyomZemlyak** [comment]
Here files of tool.
[os-llm-tool.zip](https://github.com/microsoft/promptflow/files/13304128/os-llm-tool.zip)

**Comment by thy09** [comment]
@ArtyomZemlyak 
Thank you for reporting this, after some investigation, it is a bug, we will fix it then.

**Comment by lumoslnt** [comment]
@ArtyomZemlyak The fix PR has been merged. You can now try again to see if the issue has been resolved.

**Comment by ArtyomZemlyak** [comment]
Because I install from `pip install promptflow` - I cant load last changes directly.
But I tried change `src/promptflow/promptflow/executor/_tool_resolver.py` file with appropriate changes as in PR.
And issue for my case steel exists :(
Maybe I do something wrong. Or also some another PR`s need be installed

**Comment by ArtyomZemlyak** [comment]
@lumoslnt Thanks, checked another time - its fixed!
