### ISSUE TITLE
[BUG] No module named 'PyPDF2' when running notebook "chat-with-pdf-azure.ipynb" 

### ISSUE THREAD

**Issue by HeZhang33** [microsoft/promptflow#1054]
**Describe the bug**
On a newly-created AML Compute (Standard_D13_v2), when running the notebook "chat-with-pdf-azure.ipynb", it keeps giving me error like ".......No module named 'PyPDF2'......". 

The notebook cell I was running:
>  run_2k_context = pf.run(
    flow=flow_path,
    data=data_path,
    column_mapping=column_mapping,
    runtime=runtime,
    display_name="chat_with_pdf_2k_context",
    tags={"chat_with_pdf": "", "1st_round": ""},
)
pf.stream(run_2k_context)

And the error it gives (same error after trying mutiple times):

> Uploading chat-with-pdf (16.91 MBs): 100%|██████████| 16905693/16905693 [00:00<00:00, 22414335.47it/s]
> 
> 
> ---------------------------------------------------------------------------
> HttpResponseError                         Traceback (most recent call last)
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/promptflow/azure/_restclient/flow_service_caller.py:58, in _request_wrapper.<locals>.exception_wrapper.<locals>.wrapper(self, *args, **kwargs)
>      57 try:
> ---> 58     return func(self, *args, **kwargs)
>      59 except HttpResponseError as e:
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/promptflow/azure/_restclient/flow_service_caller.py:416, in FlowServiceCaller.submit_bulk_run(self, subscription_id, resource_group_name, workspace_name, body, **kwargs)
>     415 self._set_headers_with_user_aml_token(headers)
> --> 416 return self.caller.bulk_runs.submit_bulk_run(
>     417         subscription_id=subscription_id,
>     418         resource_group_name=resource_group_name,
>     419         workspace_name=workspace_name,
>     420         headers=headers,
>     421         body=body,
>     422         **kwargs
>     423     )
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/core/tracing/decorator.py:76, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
>      75 if span_impl_type is None:
> ---> 76     return func(*args, **kwargs)
>      78 # Merge span is parameter is set, but only if no explicit parent are passed
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/promptflow/azure/_restclient/flow/operations/_bulk_runs_operations.py:370, in BulkRunsOperations.submit_bulk_run(self, subscription_id, resource_group_name, workspace_name, body, **kwargs)
>     369     error = self._deserialize.failsafe_deserialize(_models.ErrorResponse, pipeline_response)
> --> 370     raise HttpResponseError(response=response, model=error)
>     372 if response.status_code == 200:
> 
> HttpResponseError: (BadRequest) key: build_index_tool.py, Message: Failed to load python module from file '/service/app/36873/requests/meta_a902f8ce-2714-4408-9d95-7e9543138c90/build_index_tool.py': (ModuleNotFoundError) No module named 'PyPDF2'
> Code: BadRequest
> Message: key: build_index_tool.py, Message: Failed to load python module from file '/service/app/36873/requests/meta_a902f8ce-2714-4408-9d95-7e9543138c90/build_index_tool.py': (ModuleNotFoundError) No module named 'PyPDF2'
> 
> During handling of the above exception, another exception occurred:
> 
> FlowRequestException                      Traceback (most recent call last)
> Cell In[5], line 21
>       4 config_2k_context = {
>       5     "EMBEDDING_MODEL_DEPLOYMENT_NAME": "text-embedding-ada-002",
>       6     "CHAT_MODEL_DEPLOYMENT_NAME": "gpt-35-turbo",
>    (...)
>      11     "CHUNK_OVERLAP": 32,
>      12 }
>      14 column_mapping = {
>      15     "question": "${data.question}",
>      16     "pdf_url": "${data.pdf_url}",
>      17     "chat_history": "${data.chat_history}",
>      18     "config": config_2k_context,
>      19 }
> ---> 21 run_2k_context = pf.run(
>      22     flow=flow_path,
>      23     data=data_path,
>      24     column_mapping=column_mapping,
>      25     runtime=runtime,
>      26     display_name="chat_with_pdf_2k_context",
>      27     tags={"chat_with_pdf": "", "1st_round": ""},
>      28 )
>      29 pf.stream(run_2k_context)
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/promptflow/azure/_pf_client.py:248, in PFClient.run(self, flow, data, run, column_mapping, variant, connections, environment_variables, name, display_name, tags, **kwargs)
>     234     raise ValueError("at least one of data or run must be provided")
>     236 run = Run(
>     237     name=name,
>     238     display_name=display_name,
>    (...)
>     246     environment_variables=environment_variables,
>     247 )
> --> 248 return self.runs.create_or_update(run=run, **kwargs)
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/promptflow/_telemetry/activity.py:138, in monitor_operation.<locals>.monitor.<locals>.wrapper(self, *args, **kwargs)
>     135 custom_dimensions.update(extract_telemetry_info(self))
>     137 with log_activity(logger, activity_name, activity_type, custom_dimensions):
> --> 138     return f(self, *args, **kwargs)
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/promptflow/azure/operations/_run_operations.py:226, in RunOperations.create_or_update(self, run, **kwargs)
>     222 reset = kwargs.pop("reset_runtime", False)
>     224 rest_obj = self._resolve_dependencies_in_parallel(run=run, runtime=kwargs.get("runtime"), reset=reset)
> --> 226 self._service_caller.submit_bulk_run(
>     227     subscription_id=self._operation_scope.subscription_id,
>     228     resource_group_name=self._operation_scope.resource_group_name,
>     229     workspace_name=self._operation_scope.workspace_name,
>     230     body=rest_obj,
>     231 )
>     232 if in_jupyter_notebook():
>     233     print(f"Portal url: {self._get_run_portal_url(run_id=run.name)}")
> 
> File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/promptflow/azure/_restclient/flow_service_caller.py:60, in _request_wrapper.<locals>.exception_wrapper.<locals>.wrapper(self, *args, **kwargs)
>      58     return func(self, *args, **kwargs)
>      59 except HttpResponseError as e:
> ---> 60     raise FlowRequestException(
>      61         f"Calling {func.__name__} failed with request id: {self._request_id} \n"
>      62         f"Status code: {e.status_code} \n"
>      63         f"Reason: {e.reason} \n"
>      64         f"Error message: {e.message} \n"
>      65     )
> 
> FlowRequestException: Calling submit_bulk_run failed with request id: 2bd85016-1903-423e-9048-e8c550f5b13a 
> Status code: 400 
> Reason: key: build_index_tool.py, Message: Failed to load python module from file '/service/app/36873/reques 
> Error message: (BadRequest) key: build_index_tool.py, Message: Failed to load python module from file '/service/app/36873/requests/meta_a902f8ce-2714-4408-9d95-7e9543138c90/build_index_tool.py': (ModuleNotFoundError) No module named 'PyPDF2'
> Code: BadRequest
> **Message: key: build_index_tool.py, Message: Failed to load python module from file '/service/app/36873/requests/meta_a902f8ce-2714-4408-9d95-7e9543138c90/build_index_tool.py': (ModuleNotFoundError) No module named 'PyPDF2'** 

It seems that the required installing packages were not correctly installed in the runtime machine? By the way, I used a newly-created latest runtime machine. 

Please help! Thanks!

**Comment by D-W-** [comment]
Hi, @HeZhang33 this sample requires a customized runtime with [these dependencies](https://github.com/microsoft/promptflow/blob/main/examples/flows/chat/chat-with-pdf/requirements.txt) to run in cloud.
However customizing runtime is still in preview so we did not add instruction for it. 
You can reference this [private doc](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-customize-environment-runtime) to create a runtime with customized environment with above pip requirements in it and try again.

**Comment by D-W-** [comment]
Hi @HeZhang33 , I'm closing this since we've provided doc for this. Feel free to re-open if there's still issue.
