### ISSUE TITLE
metadata in azure cognitive search output for vector_db_lookup_tool?

### ISSUE THREAD

**Issue by eric-sf** [microsoft/promptflow#1078]
### Discussed in https://github.com/microsoft/promptflow/discussions/1077

<div type='discussions-op-text'>

<sup>Originally posted by **eric-sf** November  9, 2023</sup>
Hi,
How can I get metadata in vector_db_lookup_tool for azure cognitive search? It looks like currently, it is returning null. 

 https://microsoft.github.io/promptflow/reference/tools-reference/vector_db_lookup_tool.html</div>

**Comment by dans-msft** [comment]
Per the documentation, metadata is not currently supported as an output from ACS indexes -- it is used only for QDrant.
Are you interested in seeing the raw ACS payload in the metadata field?  Or something else?

**Comment by eric-sf** [comment]
I found the metadata I need in original_entity["metadata"], it's just a little bit confusing since there are 2 metadata.
