### ISSUE TITLE
[Feature Request] Non-private method to retrieve run details comparable to `LocalStorageOperations.load_detail`

### ISSUE THREAD

**Issue by bwilliams2** [microsoft/promptflow#1079]
**Is your feature request related to a problem? Please describe.**
I am investigating the logging evaluation runs of Prompt flow using the `PFClient`. I am especially interested in logging the inter-node inputs and outputs of the flow which are not returned in any of the public facing methods (e.g., `get_metrics`, `get_details`). These are readily available when visualizing with `PFClient.runs.visualize` and the details are internally retrieved using `LocalStorageOperations.load_detail`.

https://github.com/microsoft/promptflow/blob/d5d3c1a36a66155895f922466a47d2b13643d07c/src/promptflow/promptflow/_sdk/operations/_run_operations.py#L271-L272

`LocalStorageOperations` is not public facing class and I am hesitant to utilize it directly since it may be subject to undocumented changes.

**Describe the solution you'd like**
Provide a public facing method to retrieve complete run details including inter-node inputs and outputs along with other information currently displayed in a flow visualization.

**Describe alternatives you've considered**
I have not found any alternatives of retrieving the desired run details but am open to other suggestions.

**Comment by 0mza987** [comment]
Hi @bwilliams2,
Thank you for your feedback. As you can observe from the results of the pf run visualize command, it provides a comprehensive overview of a completed flow run. However, it is unlikely that we can expose all the data contracts as they may undergo changes during code development.

To better understand your user scenario and determine what information you require the most, could you please provide more details? This will allow us to have a more in-depth discussion and ascertain if the requested data can be exposed.
