### ISSUE TITLE
expose AutoGPT operator

### ISSUE THREAD

**Issue by iuiu34** [microsoft/promptflow#1085]
hi,
i think class `AutoGPT` in [examples/flows/standard/autonomous-agent/autogpt_class.py](https://github.com/microsoft/promptflow/blob/main/examples/flows/standard/autonomous-agent/autogpt_class.py) is great.

Is exposed as a "promptflow operator" anywhere?

So i could do something simple like
`from promptflow.operators import AutoGPT`

thanks

**Comment by 0mza987** [comment]
Hi @iuiu34 
Thank you for the feedback. Currently, this class is not included in the promptflow code. We will consider adding it, but it may require further improvements in terms of code quality and public documentation. In the meantime, please feel free to copy this class into your flow and use it as you see fit.
