### ISSUE TITLE
[Feature Request] support openai/openai-python >= v1.0.0

### ISSUE THREAD

**Issue by jsburckhardt** [microsoft/promptflow#1107]
**Is your feature request related to a problem? Please describe.**
Since OpenAI released v1.0.0 with breaking changes. PF requires to add fixes. -> https://github.com/openai/openai-python/releases

**Describe the solution you'd like**
Compatibility with v1.0.0 >=

**Describe alternatives you've considered**
Keep the version pin to v0.28.* ... but not a real option since they are moving fast.

**Additional context**
How to reproduce:
```bash
pip install openai
pip install promptflow
pip freeze | grep openai
```
![image](https://github.com/microsoft/promptflow/assets/18494471/c839ce3e-2d0c-4417-8806-e84283b2e5bc)

**Comment by thy09** [comment]
Duplicated issue with https://github.com/microsoft/promptflow/issues/1019
We are working on this, target on the end of this month for the new version.
