### ISSUE TITLE
[Feature Request] debugging when flow running

### ISSUE THREAD

**Issue by liyuming1978** [microsoft/promptflow#1136]
**Is your feature request related to a problem? Please describe.**
when flow running, I can add a breakpoint in node code, and start debugging

**Describe the solution you'd like**
flow dynamically load node, so debugger can stop at breakpoint source

**Comment by lalala123123** [comment]
Hi, [Prompt Flow for VScode](https://marketplace.visualstudio.com/items?itemName=prompt-flow.prompt-flow) has supported to add a breakpoint in node code and debug it. You can follow this doc to debug your node:
https://github.com/microsoft/promptflow/blob/main/docs/how-to-guides/init-and-test-a-flow.md#debug-a-single-node-in-the-flow
