### ISSUE TITLE
[Feature Request] Logging configuration

### ISSUE THREAD

**Issue by martin-weber** [microsoft/promptflow#1149]
**Is your feature request related to a problem? Please describe.**
Currently the logging of Prompt Flow seems to be configured in the framework code. Therefore the loglevel seems to be not be not configurable on a deployed endpoint. This can result in many and big log entries when the logs are collected as some of the log message contain the raw data, see point 1 below.

1. **Log levels**: Some log statements such as in [logger.info(f"PromptFlow executor received data: {raw_data}")](https://github.com/microsoft/promptflow/blob/main/src/promptflow/promptflow/_sdk/_serving/app.py#L102C4-L102C4) in app.score() or [logger.info(f"Validating flow input with data {data!r}")](https://github.com/microsoft/promptflow/blob/c0f2724133c08c9fdc889ba365c71ad728067f35/src/promptflow/promptflow/_sdk/_serving/flow_invoker.py#L118) use `logger.info()` to print out the raw request data which results in potentially big log entries. 
When log collection is enabled on a deployed endpoint, this results in big log entries.
2. **print vs logger**: In some places `print()` is used in the framework instead of the `loggger`, see: [print_yellow_warning(message)](https://github.com/microsoft/promptflow/blob/d5d3c1a36a66155895f922466a47d2b13643d07c/src/promptflow/promptflow/_sdk/_utils.py#L393) and [print_red_error(message)](https://github.com/microsoft/promptflow/blob/d5d3c1a36a66155895f922466a47d2b13643d07c/src/promptflow/promptflow/_sdk/_utils.py#L400C13-L400C13)  
  It looks like the prints are not in the logs. Is the intention to use print only for the local development environment?

**Describe the solution you'd like**
It would be great to be able to control the logging outputs via configuration:

1. Be able to configure the log-level when deploying the application by providing a config file or environment variables.
2. Log every output via the `logger` with the appropriate log-level and do not use `print` statements so that logger configuration as requested in 1. applies in a consistent way to all outputs.
3. Use `logger.debug` for outputs with potentially big content as the whole content is mainly interesting when debugging but less for info used in production.

**Describe alternatives you've considered**
We did not find any maintainable alternatives as these features are inside the promptflow library.

**Additional context**  
None

**Comment by brynn-code** [comment]
@martin-weber The log level in local would be available since v1.1.0,  please reach the docs for more details. https://microsoft.github.io/promptflow/how-to-guides/faq.html#set-logging-level . We have removed the print, but there may still be some other logs needs to be adjusted, like the log level, or the content, that's a long way to go, feel free to open issue for your thoughts, we appreciate your feedback.

**Comment by doz-msft** [comment]
Hi @fbeltrao and @martin-weber , AML cloud deployment serving (with prompt flow [runtime image](https://mcr.microsoft.com/v2/azureml/promptflow/promptflow-runtime/tags/list)) uses different code than the SDK local deployment serving. And the logging level support (through environment variable) for cloud scenario still rely on another feature of supporting environment variables in flow yaml. Will update when it's done for cloud.

**Comment by martin-weber** [comment]
Hi @doz-msft  and @brynn-code, Thanks for your answers. It is important for us to get this on the runtime image.

Which runtime image should we use? I see in the [documentation on how-to-customize-environment-runtime](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-customize-environment-runtime?view=azureml-api-2#define-the-dockerfile) that `mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:<newest_version>` is used, which has no new version, see [latest version](https://mcr.microsoft.com/v2/azureml/promptflow/promptflow-runtime-stable/tags/list).  
It is also a different image than the one you [linked above](https://mcr.microsoft.com/v2/azureml/promptflow/promptflow-runtime/tags/list): `https://mcr.microsoft.com/v2/azureml/promptflow/promptflow-runtime`.
