### ISSUE TITLE
[Feature Request] Request to add openai api_base functionality

### ISSUE THREAD

**Issue by WRXinYue** [microsoft/promptflow#1154]
**Is your feature request related to a problem? Please describe.**

~~~yaml
# Notices:
# - Don't replace the '<user-input>' placeholder in this file, the application will prompt you to enter a value when it runs.
# - Manually save the file will create the connection after basic validation.
# - The connection information will be stored in a local database with api_key encrypted for safety.
# - Prompt flow will ONLY use the connection information (incl. keys) when instructed by you, e.g. manage connections, use connections to run flow etc.
# - All the values should be string type, please use "123" instead of 123 or "True" instead of True.

$schema: https://azuremlschemas.azureedge.net/promptflow/latest/OpenAIConnection.schema.json
name: "to_replace_with_connection_name"
type: open_ai
api_key: "<user-input>" # Don't replace the '<user-input>' placeholder. The application will prompt you to enter a value when it runs.
api_base: ""
organization: ""
~~~

But report an error:
~~~
Exception: Load entity error: Load connection failed with {'api_base': ['Unknown field.']}. fIf you are trying to configure a job that is not of type OpenAI, please specify the correct connection type in the 'type' property..
~~~

I have carefully reviewed the official documentation and the examples of configuration files, and I noticed that there is no parameter related to 'api_base'. I require the functionality that 'api_base' provides. If 'api_base' has been renamed to something else, please inform me. Your assistance is greatly appreciated.

**Comment by brynn-code** [comment]
Hi @WRXinYue , this is an unreleased feature and still working in progress, please see https://github.com/microsoft/promptflow/issues/869 for more details. We still need to adjust the parameter as openai version >=1.0.0 has changed this name from 'api_base' to 'base_url'.

By the way, could you please let us know where did you get the template with key 'api_base' for open ai connection, is it generated by vscode extension?

**Comment by WRXinYue** [comment]
> Hi @WRXinYue , this is an unreleased feature and still working in progress, please see #869 for more details. We still need to adjust the parameter as openai version >=1.0.0 has changed this name from 'api_base' to 'base_url'.
> 
> By the way, could you please let us know where did you get the template with key 'api_base' for open ai connection, is it generated by vscode extension?

Thank you for your response. The reason I used 'api_base' is because the official environment variable name for OpenAI is 'OPENAI_API_BASE'.
