### ISSUE TITLE
[Feature Request] Remove version constraint for Flask

### ISSUE THREAD

**Issue by pamelafox** [microsoft/promptflow#1209]
**Is your feature request related to a problem? Please describe.**

This package currently pins the upper version of Flask to <3:
https://github.com/microsoft/promptflow/blob/main/src/promptflow/setup.py#L26

That means I can't bring this package into my app that uses Flask 3+

**Describe the solution you'd like**

Please remove the upper version of Flask. You could add tests/nightly tests to check compatibility if you're worried about future backward incompatibility.

**Describe alternatives you've considered**

You could remove PromptFlow's dependency on Flask entirely, but it seems as if you're using it for a local REST server or something.

In that case, I'd recommend at least moving to Quart or FastAPI, since async frameworks are a better fit for ChatGPT dependent apps, in my experience. (I wrote up more in this post: http://blog.pamelafox.org/2023/09/best-practices-for-openai-chat-apps.html)

**Comment by D-W-** [comment]
Hi @pamelafox , thanks for reporting! We'll test if it's compatible with our package then bump it.

**Comment by crazygao** [comment]
just relax the flask to 4.0.0, however there is flask-restx dependency which is restricting the flask version.

We relax all these dependencies on our package.
