### ISSUE TITLE
[Feature Request] Remove upper version constraint for SQLAlchemy

### ISSUE THREAD

**Issue by pamelafox** [microsoft/promptflow#1210]
**Is your feature request related to a problem? Please describe.**

Currently Promptflow pins <2.0 for SQLAlchemy:
https://github.com/microsoft/promptflow/blob/e8a22e5cc632d11055d1bf2475ad3d0045908591/src/promptflow/setup.py#L29

This makes it difficult for me to use PromptFlow in my apps that use SQLAlchemy. I've moved most to SA 2.0 since it has a much better API and SA 1.4 API is considered deprecated/legacy now.

**Describe the solution you'd like**

Please get your usage compatible with 2.0 and remove the upper version constraints.

**Describe alternatives you've considered**

You could also remove the constraint entirely or move to an extra, depending on how you're using SQLAlchemy.

**Comment by D-W-** [comment]
Hi @pamelafox , thanks for reporting! We'll test if it's compatible with our package then bump it.

**Comment by zhengfeiwang** [comment]
Hi @pamelafox , we have verified and bumped the upper bound. The change will be shipped in the 1.1.0 release. Thanks for reaching out!
