### ISSUE TITLE
[Feature Request] Carry chat history across nodes

### ISSUE THREAD

**Issue by tglanz** [microsoft/promptflow#1228]
**Is your feature request related to a problem? Please describe.**

I have different `llm` and `prompt` nodes that have different templates. The different nodes need to carry the chat context between each other.

Here is an [example repository](https://github.com/tglanz/example-prompt-flows/tree/main/flows/base) with a [basic flow](https://github.com/tglanz/example-prompt-flows/tree/main/flows/base) that illustrate the problem. In the example, there is an (invalid) attempt to use the `chat_history` flow input for this purpose. The issue is that the list is not updated across nodes.   

**Describe the solution you'd like**

Have the `chat_history` or some other mechanism provide all chat messages until a node's execution. 

**Describe alternatives you've considered**

I have considered using a custom python tool for the purpose. This tool will aggregate the outputs and will be given as input to different nodes. I didn't know how to pass in the rendered jinja2 templates as input (i.e. the `user` messages).

**Additional context**

As mentioned, here is an [example repository](https://github.com/tglanz/example-prompt-flows/tree/main/flows/base).

Thank you all for this great tool.

**Comment by thy09** [comment]
Hi @tglanz could you explain more about "the list is not updated across nodes"?
It would be helpful if you can have an example to show what is your expectation.

I also noticed that you are wrongly used the chat history in the node `birthdate`
```
{% for item in chat_history %}
user:
{{item.inputs}}
assistant:
{{item.output}}
{% endfor %}
```
Usually we use the chat_history like this:
```
{% for item in chat_history %}
user:
{{item.inputs.user_message}}
assistant:
{{item.output.assistant_message}}
{% endfor %}
```
Where `user_message` and `assistant_message` are one of the flow inputs and one of the flow outputs.

**Comment by tglanz** [comment]
@thy09 

> could you explain more about "the list is not updated across nodes"?

When debugging, I see that the `chat_history` input is always `[]` in the `birthdate` node.

> It would be helpful if you can have an example to show what is your expectation.

My expectation is that somehow I can accumulate all of the chat messages in the flow. Specifically in the example, i'd like the `birthdate` node to have access to all of the chat messages that occurred before it (in the `introduction` node) so I can add them as part of the `birthdate` node.

To ask the `llm` what is the birthdate of the `person` we are referring to, it requires the full context - the messages that were sent previously.

As a single `llm` node it could have looked like this:

```
system:
You are a helpful assistant.

user:
The following questions are about the person: {{person}}

// The response will be something like:
assistant:
Ok, ask me anything about {{person}}.

// Now we want to keep asking questions
user:
What is their birthdate?

// We expect the assistant to provide the birtdhate of the {{person}}
assistant:
{{person}}'s birthdate is 22/11/2023.
``` 

My scenario is that the chat is compose programaticly across different nodes (using `python` and `prompt` tools), it is not "interactive" (where the `chat_history`) is accumulated.

> I also noticed that you are wrongly used the chat history in the node `birthdate`

Yea, understood. I didn't really know what to write here in this case. The standard usage (from what I understood) is when it refers to the same node, so the input and output are consistent between chat history items.

Not sure if `chat_history` is what I need or there is another mechanism I can use for the scenario. I am currently investigating whether I can leverage the `echo` attribute for this purpose.

Thanks

**Comment by thy09** [comment]
I guess chat_history is not what you want, you just need the output of a previous node, right?
According to your expectation, I guess one proposal is like this:
node: introduction
```
system:
You are a helpful assistant.

user:
The following questions are about the person: {{person}}
```

node: birth_date
```
system:
You are a helpful assistant.

user:
The following questions are about the person: {{person}}

assistant:
{{response}}

user:
What is their birthdate?
```

The flow definition of the two nodes:
```yaml
- name: introduction
  type: llm
  source:
    type: code
    path: introduction.jinja2
  inputs:
    deployment_name: ${inputs.deployment_name}
    person: ${inputs.person}
  connection: open_ai_connection
  api: chat
- name: birthdate
  type: llm
  source:
    type: code
    path: birthdate.jinja2
  inputs:
    deployment_name: ${inputs.deployment_name}
    person: ${inputs.person}
    response: ${introduction.output}
  connection: open_ai_connection
  api: chat
```

**Comment by tglanz** [comment]
IIUC not exactly, for the same reason that in interactive chat there is a full chat history (including previous user messages) and not only the assistant's response.

This approach is highly dependent on the response itself. For example, if the output of the introduction is something like:

```
Ok, I'm ready for your questions.
```

It doesn't provide enough context for the questions.

But if the input to birthdate will be the introduction's output in addition to it's prompts, it will have enough context. For example, such input will be:

```
user:
The following questions are about "Someone"

assistant:
Ok, I'm ready for your questions!
```

Then in the `birthdate` chat API call, we will send the entire history, providing it enough context for the question.

Also, this is a simple example to a larger scenario where I need to repeat this process multiple times and build the context incrementally. Therefore the single output from a specific `llm` node is not enough.

**Comment by thy09** [comment]
In general, your purpose is to repeat multiple rounds of chat completion until it can returns your expected result?
I think we do not have such supports for now and you need to do the loops in script tool.

`chat_history` is the record of all interactions between the user and the chatbot, which inlcudes both flow inputs and flow outputs, it is not the openai history.
The common practice is to use a "user_message" from flow_input to set as chat completion input, then put the chat completion output as "assistant_message" of the flow. Then we could refer to them. But we can only refer them in the next round of flow execution.
See the document here: https://microsoft.github.io/promptflow/how-to-guides/develop-a-flow/develop-chat-flow.html#flow-input-data

**Comment by tglanz** [comment]
I am not sure how can I achieve this in a non-interactive way. 

> "Chat input refers to the messages or queries submitted by users to the chatbot"

I have a set predefined set of questions, only the initial input changes between flow executions.

Is there any example which implements such a scenario?

**Comment by thy09** [comment]
I'm not sure what do you mean by "a set predefined set of questions".
Like this?
```
system:
You are a helpful assistant.
user:
{{question1}}
assistant:
{{answer1}}
user:
{{question2}}
assistant:
{{answer2}}
user:
{{question3}}
assistant:
{{answer3}}
```
Where all questions are from some predefined value, and all the answers are from chat completion API.

If this is what you want, I think we don't have such native support, you have two options:
1. Do such stuffs in your script tool;
2. Use the interactive run with the following tricky prompt;
```
{% for item in chat_history %}
user:
{{predefined_questions[loop.index-1]}}
assistant:
{{item.outputs.chat_completion_output}}
{% endfor %}
user:
{{predefined_questions[chat_history|length]}}
```
In this implementation, I assume the predefined questions are in a list, then we put the question in the user message one by one, and put the chat completion output after each questions according to the loop.index (the round you talk to gpt)

**Comment by thy09** [comment]
@tglanz Could you help confirm whether your problem is resolved or do you have more concrete feature request for your requirement? Thanks

**Comment by tglanz** [comment]
Its resolved, thanks.
