### ISSUE TITLE
[Feature Request] Remove version constraint for pydash 

### ISSUE THREAD

**Issue by wangchao1230** [microsoft/promptflow#1239]
**Is your feature request related to a problem? Please describe.**
├── pydash [required: >=6.0.0,<7.0.0, installed: 6.0.2]             -- latest version 7.0.6, 7.0 released 2023-04-12

**Describe the solution you'd like**
relax pydash version to < 8.0.0

**Comment by zhengfeiwang** [comment]
related code change merged in #1253
