### ISSUE TITLE
[Feature Request] Relax version constraint for ruamel.yaml 

### ISSUE THREAD

**Issue by wangchao1230** [microsoft/promptflow#1240]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
├── ruamel.yaml [required: >=0.17.35,<0.18.0, installed: 0.17.40]   -- latest version 0.18.5, 0.18 released 2023-10-23

**Describe the solution you'd like**
relax version to < 0.19

**Comment by crazygao** [comment]
Will relax to 1.0.0 in next release
