### ISSUE TITLE
[Feature Request] Add download function to sdk

### ISSUE THREAD

**Issue by Jasmin3q** [microsoft/promptflow#1249]
**Is your feature request related to a problem? Please describe.**

The current sdk have no function for downloading intermediate output file of runs. Users cannot get the information of batch run containing images.
 
**Describe the solution you'd like**
 
Add download action to sdk. For example, pfazure.runs.download. Downloading all the images is by default.
 
**Describe alternatives you've considered**
If the customers require other ways that do not download all the images, consider generate sas token for the image and replace the dict format with sas url of each image in pfazure.runs.get_detail.

**Comment by 0mza987** [comment]
The run download function is released along with promptflow 1.2.0, please install the latest sdk and have a try:
`pip install promptflow --upgrade`

For the command usage, you can use `pfazure run download --name <run-name>` to download the run info, and then use `pf run create --source <run-info-local-folder>` to register this run as a local run record, then you can use commands like `pf run show/visualize` to inspect the run just like a run that was created from local flow.
