### ISSUE TITLE
[BUG] [VSCode Extension] Can't find tool promptflow_vectordb.tool.vector_db_lookup.VectorDBLookup.search

### ISSUE THREAD

**Issue by buchizo** [microsoft/promptflow#1252]
**Describe the bug**
My prompt flow is using vector_db_lookup. In Azure ML studio, that prompt flow is valid. However error occurred that flow opened in Visual Studio Code as follows:

```
Can't find tool promptflow_vectordb.tool.vector_db_lookup.VectorDBLookup.search
The package may not be installed in your Python environment.
```

**How To Reproduce the bug**
1. Create prompt flow include `vector db lookup` of Azure AI Search on Azure ML Studio ( ml.azure.com )
2. Download flow.dag.yaml and other files.
3. Open flow using Visual Studio code + promptflow extension.
4. `vector_db_lookup` node has error.

![image](https://github.com/microsoft/promptflow/assets/1254213/4dbf8aab-3983-4868-8775-43ac72e72205)

**Environment Information**
 - promptflow installed version:1.0.0
 - promptflow-tools installed version: 0.1.0b15
 - Operating System: Windows 11 x64 23H2
 - Python Version: Python 3.9.18
 - VS Code version: 1.84.2
 - Prompt Flow extension version: v1.5.0

**Additional context**
Prompt flow GUI editor in Azure ML Studio can add vector db lookup node, but Visual Studio code can not add it.
![image](https://github.com/microsoft/promptflow/assets/1254213/53b242bb-b706-4fe7-a61a-78522fb5c9e4)

Where is `promptflow_vectordb.tool.vector_db_lookup.VectorDBLookup`?

**Comment by brynn-code** [comment]
Hi @buchizo, sorry for the inconvience, the package needs to be installed manually in your environment, please install the `promptflow-vectordb`.

**Comment by buchizo** [comment]
@brynn-code I got it! Thank you so much. I could use vector lookup node after installed `promptflow-vectordb`. If possible, I want to see dependency packages in solution files of prompt flow. e.g. requirements.txt.

**Comment by brynn-code** [comment]
No problem. @jiazengcindy is working on add the dependency to requirements, the issue will be closed once the task done.

**Comment by jiazengcindy** [comment]
Hi @buchizo,  `promptflow-vectordb` have been added to the requirements.txt, please check, thanks very much!

**Comment by jiazengcindy** [comment]
Close this bug since task has been completed.
