### ISSUE TITLE
[Feature Request] Remind customer to upgrade sdk once we detect customer's version is not latest.

### ISSUE THREAD

**Issue by ishinzhang** [microsoft/promptflow#1256]
**Is your feature request related to a problem? Please describe.**
One customer report to us, that they encounter "can't find connection" error after config connection provider as azureml for the machine. Then they get unblocked by upgrading sdk.

**Describe the solution you'd like**
Is it possible to remind customer there is a new version, please upgrade. It can help unblock them for some issues.

**Describe alternatives you've considered**
In error message, remind customer to upgrade, which is more straightforward. But it is hard to tell if this issue can be unblocked by upgrading. After talking to @wangchao1230 , we can remind customer once for each 7 days.

**Additional context**

**Comment by wangchao1230** [comment]
We are considering introduce prviding such upgrade notice.
