### ISSUE TITLE
[BUG]Failed to  load the tool yaml files  if in the yaml files in sub-directory

### ISSUE THREAD

**Issue by unanao** [microsoft/promptflow#1257]
**Describe the bug**
Mkdir a sub-directory to manage the tools yamls. The tool yaml in sub-directory is not loaded by promptflow VSCode plugin.

for example, the tool yaml dirctory is below :
```
$ tree yamls/
yamls/
├── xxx.yaml
├── yyy
│   ├── yyy1.yaml
│   └── yyy2.yaml
└── zzz.yaml
```

The yyy1 and yyy2 tool will failed to be aoded.
 

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. mkdir sub-directory in the yaml
2.define the tools yaml in the sub-directory

**Expected behavior**
the yaml file will be loaded by the vscode plugin

**Screenshots**
It's clear, no need of screenshots

**Running Information(please complete the following information):**
 - Promptflow Package: [1.0.0]
 - Operating System:[MacOS 12.21]
 - Python Version : [ python==3.9]

**Additional context**
No

**Comment by 16oeahr** [comment]
Hi @unanao , could you share your python tool package so that I can look into the issue?

I suspect that the `list tool method` is not correctly written.
As pointed out in point 4 of this [doc](https://microsoft.github.io/promptflow/how-to-guides/develop-a-tool/create-and-use-tool-package.html), you may want to update your list func if you change the folder structure.
![image](https://github.com/microsoft/promptflow/assets/46446115/515b34ef-e3ef-4bf8-a7f2-c7d490097a0f)

**Comment by unanao** [comment]
Hi @16oeahr.  In the he [doc](https://microsoft.github.io/promptflow/how-to-guides/develop-a-tool/create-and-use-tool-package.html) , explain the MANIFEST.in

MANIFEST.in: This file is used to determine which files to include in the distribution of the project. Tool YAML files should be included in MANIFEST.in so that your tool YAMLs would be packaged and your tools can show in the UI.

I generate tools by the generate_tool_package_template.py scripts. But the generated MANIFEST.in  , the code not include the sub-directory. (I have pulled a request, fix this, and test ok. )

Reproduce step: 
1. generate a new tools
2. mkdir a sub-directory under yamls
3. write a tool yaml under subdir, then  can reproduce。
If you can't reproduce, I create a demo tool to reproduce the problem.  As our tool is internal api and sdk,  may be not useful.



> Hi @unanao , could you share your python tool package so that I can look into the issue?
> 
> I suspect that the `list tool method` is not correctly written. As pointed out in point 4 of this [doc](https://microsoft.github.io/promptflow/how-to-guides/develop-a-tool/create-and-use-tool-package.html), you may want to update your list func if you change the folder structure. ![image](https://private-user-images.githubusercontent.com/46446115/286518642-515b34ef-e3ef-4bf8-a7f2-c7d490097a0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzUwMDEsIm5iZiI6MTcwMTMzNDcwMSwicGF0aCI6Ii80NjQ0NjExNS8yODY1MTg2NDItNTE1YjM0ZWYtZTNlZi00YmY4LWE3ZjItYzdkNDkwMDk3YTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA4NTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNGUzZTY2MmQxZDAwYjk5ZGIzZWU1NDM4ZGU2ODk3ODllOWNmZTVhZWUxMTc2NzI1NDM5MGJiZTZlNDVlODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._dFIe6vEGoEeREPT6A5zb7GnWQv8GUloYdgIOaXzCbs)

**Comment by unanao** [comment]
@16oeahr  ok.  In fact，if a tool project has lots of tools,  manage yaml is needed.  
> Thank you for your information. It's worth noting that the location of YAML files is not restricted to the yamls folder or its subfolders; they can be placed anywhere. Consequently, your pull request might not address other scenarios. However, users are encouraged to modify their MANIFEST.in based on their specific needs. It's also important to mention that tool YAMLs are about to deprecate in the near future. As such, your pull request might not be aligned with our upcoming changes. Truly appreciate your collaboration.
