### ISSUE TITLE
openapi rest api 

### ISSUE THREAD

**Issue by ggcking** [microsoft/promptflow#1260]
**Is your feature request related to a problem? Please describe.**
Currently, pf can be called through the "/score" endpoint. Can it be encapsulated into an OpenAPI-compliant interface?

```[tasklist]
### Tasks
```

**Comment by wxpjimmy** [comment]
@ggcking could you elaborate more on this "OpenAPI-compliant interface"? better to give some examples.  Currently the /score endpoint is already defined with swagger following OpenAPI spec.

**Comment by ggcking** [comment]
just like call openai's api, the request body like "{   "model":"gpt-3.5-turbo",
    "stream": false,
    "messages": [
        {
            "role": "system",
            "content": ""
        },
        {
            "role": "user",
            "content": "hello"
        }
    ]
}"

**Comment by wxpjimmy** [comment]
oh, seems what you want is openai interface, not openapi interface :)

We don't have plan to support openai interface out-of-box, you can build your flow with this interface if you want.  BTW, we do have a plan to support a new interface which is similar to openai interface but is more general and powerful, there might be a little difference between this new interface with the openai one.

**Comment by ggcking** [comment]
I wish the new interface can compatible with the openai interface!
