### ISSUE TITLE
[BUG] connections folder not generated after running pf build --format docker

### ISSUE THREAD

**Issue by joaquinrz** [microsoft/promptflow#1274]
**Describe the bug**
Running `pf flow build --source promptflow --output pf_docker --format docker` does not generate a connections folder in the output folder.

This causes `docker build` to throw an error:

`ERROR: failed to solve: lstat /var/lib/docker/tmp/buildkit-mount1136518113/connections: no such file or directory`

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Install promptflow and tools `pip install promptflow promptflow-tools keyrings.alt`
2. Verify promptflow is installed `pf -v` -> 1.0.0
3. Create connection: `pf connection create --file ./promptflow/azure_openai.yaml --set api_key=<my_api_key> api_base=<my_api_base> --name open_ai_connection`
4. Generate output folder: `pf flow build --source promptflow --output pf_docker --format docker`
5. Build Image: `docker build pf_docker -t myapp_pf:dev`

**Expected behavior**
After running `pf flow build --source promptflow --output pf_docker --format docker` I am expected to see a connections folder, however this is not being generated:

<img width="285" alt="image" src="https://github.com/microsoft/promptflow/assets/16692906/4ff86b6b-cfd6-4933-8540-da81b18acc10">

I noticed that the `Dockerfile` is expecting a connections folder because `COPY ./connections/* /connections/`

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.0.0
 - Operating System: Ubuntu 20.04.6
 - Python Version using `python --version`: 3.10.8

**Additional context**
N/A

**Comment by YingChen1996** [comment]
Hi, @joaquinrz .The fix is merged https://github.com/microsoft/promptflow/pull/1242 and will be released in the next stable version.

The connection folder is generated in the flow/dist/connection folder for now. You can update the Dockerfile COPY ./flow/dist/connections/* /connections/ as a workaround for now.
