### ISSUE TITLE
[Feature Request] Docs for env variables

### ISSUE THREAD

**Issue by ArtyomZemlyak** [microsoft/promptflow#1385]
**Is your feature request related to a problem? Please describe.**
Add documentaton for supported env variables.
It's needed for example for butch run for set number of workers:
```yaml
environment_variables:
  PF_WORKER_COUNT: "1"
```

**Describe the solution you'd like**
A clear and concise description of env variables, which can be used in different places of promptflow.

**Describe alternatives you've considered**
Can be very helpfull adding this variables to `.yaml` template files.
Or more good: add UI generator for all `.yaml` files in VSCode Extension. And also add supported env variables to it.

**Comment by codingrabbitt1** [comment]
Hi @ArtyomZemlyak , we have supplemented the documentation about environment variables. https://github.com/microsoft/promptflow/blob/main/docs/how-to-guides/faq.md

Additional, support for configuring environment variables in flow.dag.yaml is under development.

**Comment by ArtyomZemlyak** [comment]
Hi @codingrabbitt1 , looks good! 
Thanks!

**Comment by swiecki** [comment]
> Hi @ArtyomZemlyak , we have supplemented the documentation about environment variables. https://github.com/microsoft/promptflow/blob/main/docs/how-to-guides/faq.md
> 
> Additional, support for configuring environment variables in flow.dag.yaml is under development.

Is there any option for the temp file storage to also be configured?
#1501

**Comment by thy09** [comment]
Already merged.
