### ISSUE TITLE
[BUG] How can I use openai v1 in a custom runtime?

### ISSUE THREAD

**Issue by joshuaphelpsms** [microsoft/promptflow#1438]
**Describe the bug**

I am trying to get a runtime up with a custom environment that pulls from `mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:latest`. I am also pip installing a package that I created that requires openai `1.3.7`. The container will not start due to the following error: 
```sh
Traceback (most recent call last):
  File "/azureml-envs/prompt-flow/runtime/bin/prt", line 5, in <module>
    from promptflow.runtime._cli.prt import main
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/__init__.py", line 9, in <module>
    import promptflow.tools  # noqa: F401
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tools/__init__.py", line 1, in <module>
    from .aoai import AzureOpenAI  # noqa: F401
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tools/aoai.py", line 10, in <module>
    from promptflow.tools.common import render_jinja_template, handle_openai_error, parse_chat, to_bool, \
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tools/common.py", line 8, in <module>
    from openai.error import APIError, OpenAIError, RateLimitError, ServiceUnavailableError, Timeout, APIConnectionError
ModuleNotFoundError: No module named 'openai.error'
```

While investigating, I was able to successfully create a runtime with a custom environment that uses `mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:latest` and not pip installing any other packages. However, I received a notification that I was not using the latest features. How can I upgrade to the latest features when I'm already pulling from latest?

![Screenshot 2023-12-08 at 4 11 50 PM](https://github.com/microsoft/promptflow/assets/88395136/6bd017aa-0ecd-4ca9-b1b9-d1ce0ec4e4a5)

It appears that the latest `promptflow-runtime-stable` uses these package versions:
```txt
openai=0.27.8
promptflow=1.0.2.dev3
promptflow-contentsafety= 0.0.9
promptflow-sdk =0.0.1
promptflow-tools= 0.1.0b10
promptflow-vectordb =0.0.1
```

I originally upgraded my pip package to use `openai==1.3.7` because when I am developing with prompt flow in VSCode and pip install `promtpflow` and `promptflow-tools`, the openai version get updated. 
 
How can I use openai v1 both locally and in the ml workspace?

**Comment by chenslucky** [comment]
promptflow-tools supports openai 1.x from version 1.0.0. You can use command "pip install promptflow-tools>=1.0.0" to fix this error.

**Comment by joshuaphelpsms** [comment]
That works for me. Thank you for the quick response.
