### ISSUE TITLE
[BUG] Doc is unclear on flow init from existing code

### ISSUE THREAD

**Issue by jiaochenlu** [microsoft/promptflow#1439]
**Describe the bug**
1.The CLI example is very confusing here... what does the prompt template refer to? It wasn't until I drill down into the example that I figured out it was pointing to a file...
<img width="755" alt="image" src="https://github.com/microsoft/promptflow/assets/32232238/a932999f-f531-4b9b-9d56-bd650718e65c">

2.The doc does not explain the KEY:VALUE construct, causing confusion when encountering the error below. It is understood that a prompt parameter should be defined in the function, but this clarity is only achieved by delving into the example flow as well....
<img width="676" alt="image" src="https://github.com/microsoft/promptflow/assets/32232238/daa601bb-d045-4c91-88d4-51732b152760">

3.In the [example](https://github.com/microsoft/promptflow/blob/main/examples/flows/standard/customer-intent-extraction/intent.py), cannot find the md file... another question is no information mentioning what kind of prompt file type are supported here, is only Jinja supported, or are there other options available?
<img width="641" alt="image" src="https://github.com/microsoft/promptflow/assets/32232238/8071b31c-50df-4cdb-b7f4-3d971c608e39">

**Comment by ttthree** [comment]
@wangchao1230 to check.

**Comment by 0mza987** [comment]
Assigned to @lalala123123 to take a look.
