### ISSUE TITLE
[Feature Request]  Reducing the dependencies of promptflow

### ISSUE THREAD

**Issue by unanao** [microsoft/promptflow#1481]
**Is your feature request related to a problem? Please describe.**
Prompt flow have too many dependencies。 Install it need too much times, a fresh install sometimes more  than 10 minutes. 

**Describe the solution you'd like**
Promptflow have lots of module。But In many scenarios, only a few modules are used。

Firstly, If have unused dependencies,  remove them is a good solution
secondly, Uses can choose the using modules is a  another solution.

**Comment by wangchao1230** [comment]
Thanks for the feedback! @unanao 

Could you share the command & a log of your pip install log? 
You can get the pip.log with something like: `pip install opentelemetry-api --log pip.log`

Do you have any suggestions on the module that you think should be moved as extra?

**Comment by unanao** [comment]
Thanks! @wangchao1230 
The attachment [build-log.txt](https://github.com/microsoft/promptflow/files/13680362/build-log.txt) is  our build/packaging of the Docker image, including the log of pip install. Maybe it meets your requirements?   

About extra modules, here is our usage，May not be typical, for reference only.
**Tools**， we only use the Python and Prompt tools。 Other tools ，such as embedding/LLM/search ... ...,  we develop the our own promptflow tools to call our own services.
**Connections**， we also have not use, on one hand we can only use CustomConnecton, a little inconvenient. On the other hand，integrate with our configuration center is also  a little inconvenient

> Thanks for the feedback! @unanao
> 
> Could you share the command & a log of your pip install log? You can get the pip.log with something like: `pip install opentelemetry-api --log pip.log`
> 
> Do you have any suggestions on the module that you think should be moved as extra?

**Comment by wangchao1230** [comment]
Thanks for sharing the build log, I noticed the main reason is pip install is slow for you.  

I tried starting a github codespace using this [dockerfile](https://github.com/microsoft/promptflow/blob/main/.devcontainer/Dockerfile).
The pip install step takes about **40 sec** to complete.  You can also give it a try with this [link](https://codespaces.new/microsoft/promptflow?quickstart=1)

I suppose you are in china and using an non-official index. Is there any issue with the **network connection of your build server**? Does it always slow for pip installs?

The packages required by promptflow are all introduced for feature requirment. 
Some of them might be able to move to extras, but there will still a bunch remains, so It won't provide much help on your case.

**Comment by unanao** [comment]
@wangchao1230  Thank you very much for your reply. We will package a Docker image containing Prompflow to solve this problem.  

> Thanks for sharing the build log, I noticed the main reason is pip install is slow for you.
> 
> I tried starting a github codespace using this [dockerfile](https://github.com/microsoft/promptflow/blob/main/.devcontainer/Dockerfile). The pip install step takes about **40 sec** to complete. You can also give it a try with this [link](https://codespaces.new/microsoft/promptflow?quickstart=1)
> 
> I suppose you are in china and using an non-official pip index. Does your build server always slow for pip installs? From the log the connection speeds looks ok, but the install of each package is slow.
> 
> The packages required by promptflow are all introduced for feature requirment. Some of them might be able to move to extras, but there will still a bunch remains, so It won't provide much help on your case.

**Comment by wangchao1230** [comment]
@unanao Greate to know you take that option to solve the promblem. 
Thanky for reaching out to us. I will close this issue.
