### ISSUE TITLE
Configure HOME_PROMPT_FLOW_DIR [Feature Request]

### ISSUE THREAD

**Issue by swiecki** [microsoft/promptflow#1501]
**Is your feature request related to a problem? Please describe.**
if HOME_PROMPT_FLOW_DIR is not writable, promptflow will not run. For example in AWS Lambda the home dir is not writable, only /tmp/ is.

**Describe the solution you'd like**
I know promptflow uses files to save state. Can I please tell it where to put those files?

**Describe alternatives you've considered**
I'm considering monkey patching HOME_PROMPT_FLOW_DIR after loading the promptflow package.

**Additional context**
To avoid XY problem, here's my situation: I have a lambda function that uses the python SDK to load and run several flows. Maybe there is a better way to be running flows from python.

**Comment by zhengfeiwang** [comment]
Hi @swiecki , thanks for your feedback! We will discuss this, and PROBABLY support configuring `HOME_PROMPT_FLOW_DIR` with an environ to make it work in your scenario. Let's use this issue to track.

**Comment by zhengfeiwang** [comment]
Hi @swiecki , we just released [promptflow 1.3.0](https://pypi.org/project/promptflow/1.3.0/) earlier this week, carring related change. You can configure the PF home directory now with environment variable `PF_HOME_DIRECTORY`.

will close this issue, and feel free to comment/re-open this if you run into any problem. Happy coding with promptflow, cheers!
