### ISSUE TITLE
[Feature Request]Add a Text Stream is over Event to SSE in the docker deployment 

### ISSUE THREAD

**Issue by mymro** [microsoft/promptflow#1552]
**Is your feature request related to a problem? Please describe.**
Currently there is no clear way to determine when the Text transmission when using SSE (streaming) is over. It is mostly guess work.

**Describe the solution you'd like**
Add an event that is sent after the response from the LLM is complete. 

**Describe alternatives you've considered**
Guessing.

**Comment by zzn2** [comment]
Hello @mymro,
Thanks for reaching out for us.

For stream mode, the HTTP response is sent back using [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding). The client side knows when the data is fully sent from the server.

Additionally, there are 3rd party libraries (like [sseclient-py](https://github.com/mpetazzoni/sseclient)) which can iterate over the http response as events.
The client code can simply consume the events using a `for` loop like below:
```python
client = sseclient.SSEClient(response)
for event in client.events():
    pprint.pprint(json.loads(event.data))
```

The `for` loop ends automatically when there are no more events. Under the hood, it is determined by the end of the trunced stream. In other words, the end of event stream is determined by the server side, not a guess work.

**Comment by zzn2** [comment]
We will close this issue as no further action is required.
