### ISSUE TITLE
Promptflow Schema not up to date

### ISSUE THREAD

**Issue by danielsc** [microsoft/promptflow#1553]
**Describe the bug**
Promptflow Schema not up to date

**How To Reproduce the bug**
Create a new Promptflow using the VSCode extension.
Add the schema reference as per [the documentation](https://microsoft.github.io/promptflow/how-to-guides/quick-start.html?highlight=azuremlschemas#how-to-edit-the-flow):
`$schema: https://azuremlschemas.azureedge.net/promptflow/latest/Flow.schema.json`

several fields show up as invalid:
![image](https://github.com/microsoft/promptflow/assets/8079390/4d244820-62d5-4dc9-b9ed-b107903807eb)

**Running Information(please complete the following information):**
promptflow                       1.2.0
Executable '/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/bin/python'
Python (Darwin) 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ]

**Comment by brynn-code** [comment]
Thanks, will update today.

**Comment by brynn-code** [comment]
@danielsc What's the `id` and `name` in your screenshot? seems they are not included in our schema.

**Comment by brynn-code** [comment]
Schema updated.
