### ISSUE TITLE
[BUG] [VSCode Extension] Failed building docker container: unrecognized arguments: --user-agent prompt-flow-extension/1.7.0 (win32; x64) VSCode/1.85.1

### ISSUE THREAD

**Issue by StoyanStAtanasov** [microsoft/promptflow#1570]
**Describe the bug**
Failed to build docker container for simple flow

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. New flow: chat template
2. build container

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
2. ![image](https://github.com/microsoft/promptflow/assets/49271294/e6fb8884-7aca-4ace-a019-f22b630f001e)

3. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: 1.2.0
 - Operating System: Windows 11
 - Python Version using `python --version`: Python 3.8.10
 - VS Code version: 1.85.1
 - Prompt Flow extension version: prompt-flow-extension/1.7.0 (win32; x64) VSCode/1.85.1
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 {"code":2,"killed":false,"signal":null,"cmd":"c:\\Users\\StoyanAtanasov\\workspace\\promptflow-test\\.venv\\Scripts\\python.exe -m promptflow._cli._pf.entry flow build --source c:\\Users\\StoyanAtanasov\\workspace\\promptflow-test\\another-flow --output c:\\Users\\StoyanAtanasov\\workspace\\promptflow-test\\docker-output --format docker --user-agent \"prompt-flow-extension/1.7.0 (win32; x64) VSCode/1.85.1\"","stdout":"","stderr":"usage: pf [-h] [-v] {flow,connection,run,config,tool} ...\r\npf: error: unrecognized arguments: --user-agent prompt-flow-extension/1.7.0 (win32; x64) VSCode/1.85.1\r\n"}
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by D-W-** [comment]
Hi @StoyanStAtanasov , thanks for reporting! We'll fix this in next SDK release (1.3.0). For workaround, you can run build in CLI instead of from extension:
```bash
pf flow build --source c:\Users\StoyanAtanasov\workspace\promptflow-test\another-flow --output c:\Users\StoyanAtanasov\workspace\promptflow-test\docker-output --format docker 
```  
Here's doc about this: https://microsoft.github.io/promptflow/how-to-guides/deploy-a-flow/deploy-using-docker.html
