### ISSUE TITLE
Question about chat history 

### ISSUE THREAD

**Issue by sersoage** [microsoft/promptflow#1572]
I am unable to limit the chat history does anyone know how to do it?

**Comment by brynn-code** [comment]
Hi, @sersoage, by 'limit the chat history', does that mean limit chat history to specific messages, like the last N lines? If so, we'd like to know which scenario you would like to have that, the 'pf test --interactive' or anywhere else?

**Comment by sersoage** [comment]
Yes last 3 for example, i tried with this
{% for item in chat_history[-3:] %}
user:
{{ item.inputs.question }}
assistant:
{{ item.outputs.answer }}
{% endfor %}
In the prompt, but it is not working.
I am running prompt flow from from ml.azure portal

**Comment by D-W-** [comment]
Hi @sersoage , we currently only track prompt flow SDK/CLI issues here. For UI feature ask, feel free to create OCV in portal here: 
![image](https://github.com/microsoft/promptflow/assets/7776147/8f976ffe-0667-4ba8-ae1a-7b279f0f436b)
For your original question, I'd like to clarify that prompt flow UI only provides authoring experience for chat flow. Our SDK/CLI provides ability to customize chat history in chat flow, here's the [related doc](https://microsoft.github.io/promptflow/how-to-guides/develop-a-flow/develop-chat-flow.html)
BTW, the prompt change you provided should also work, you can check the trace tab in outputs for actual messages sent to LLM.
![image](https://github.com/microsoft/promptflow/assets/7776147/f9d8cc96-2227-40c0-bba3-47e7d1211776)
