### ISSUE TITLE
[BUG] Can not have the same display name in 2 flows

### ISSUE THREAD

**Issue by spygi** [microsoft/promptflow#1610]
**Describe the bug**
An author can not have 2 *flows* with the same *display name*. 

Original use-case (#1459) is to be able to update an existing flow so that you don't have to create a bunch of flows with slightly different names. Workaround suggested was to archive the old flow and create another one with the same name. This bug is about this workaround.

This behavior of flows is confusing/restricting for users for 2 reasons:

- even archived flows are taken into account and you can not completely purge them at the moment.
- it is inconsistent behavior to how **runs** behave, as it is allowed to have 2 **runs** with the same name

**How To Reproduce the bug**

Run 2 times: 
`pfazure flow create --flow flow.dag.yaml --set display_name=CUSTOM_NAME type=chat -w $AZURE_AI_PROJECT_NAME -g $AZURE_RESOURCE_GROUP`

The second time fails with 

```Create flow failed with FlowOperationError: Remote flow folder 'CUSTOM_NAME' already exists under 'Users/819a3fe1-c31a-4c1c-881f-94918943b2f3/promptflow'. Please change the flow folder name and try again.```

NB: even if you edit the name in the UI of the first flow and try again it results in the same error. It seems like the UI does not change the underlying folder name of where the flow is stored, only the title -> see bug #1611 

**Expected behavior**

Running the command multiple times is allowed as this is the display name,not the name/id. 

At least the behavior between flows and runs should be consistent or if anything flows being "drafts" should be more relaxed in how they are named.

**Screenshots**

<img width="1395" alt="Screenshot 2023-12-27 at 17 55 10" src="https://github.com/microsoft/promptflow/assets/4732694/d2b5156b-b8b3-41b2-8312-f6a3a123f3eb">

**Running Information(please complete the following information):**
 - Promptflow: promptflow                       1.1.0
 - Operating System
$ uname -a
Linux c206cc41a3f4 6.5.11-linuxkit # 1 SMP PREEMPT_DYNAMIC Mon Dec  4 10:03:25 UTC 2023 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

FROM mcr.microsoft.com/devcontainers/python:3.11 
 - Python Version: Python 3.11.6

**Additional context**

In contact about this with @0mza987 

Original feature request was to be able to update a flow: #1459

**Comment by D-W-** [comment]
Hi @spygi , I think the main difference between UI and CLI is we provides keep editing experience in UI but not in CLI. We'd like to know your user scenario on flow authoring experience. Could you update here so we can better understand and provide support for it?

**Comment by spygi** [comment]
Hi @D-W- and thanks for picking this up.

I clarified that the original use-case #1459  was to be able to update an existing flow so that you don't have to create a bunch of flows with slightly different names. Workaround suggested was to archive the old flow and create another one with the same name. This bug is about this workaround.

I added you also to a chat where we have discussed more about this use-case.

**Comment by 0mza987** [comment]
Hi @spygi ,

When creating a flow to azure workspace, we created a flow folder in workspace file share with the display name, updating flow display name or archiving the flow won't resolve this error because that file share folder name does not get impacted.

We are planning to add a new parameter `remote-path` for `pfazure flow create` command to allow users to specify the file share flow folder name created in workspace instead of using the flow display name.

**Comment by spygi** [comment]
> because that file share folder name does not get impacted.

Yes exactly. My initial thought was that folder name needs to be updated too but probably we don't want to use a user-generated name there.

Instead of 

> We are planning to set file share folder name to be "local flow folder name + timestamp"

wouldn't it be simpler to create the folder name with the flow id/name instead? This is unique and server generated. The user can still create multiple flows with the same display name. Additionally the folder name does not need to change if the user changes the display name.

**Comment by 0mza987** [comment]
Hi @spygi,

> My initial thought for the fix was that the folder name needs to be updated too when you edit the display name - but maybe we don't want to use a user-generated name for the folder?

This is a azure portal related feature ask and I believe you have already created a feedback.

> wouldn't it be simpler to create the folder name with the flow id/name instead?

Using flow id/name which is a uuid will make users unable to track the file share flow folder, while local folder name + timestamp could make it somewhat meaningful. Even if users change the display-name server side only needs to update the meta data of a flow and there should be no file copy operations at all.

**Comment by spygi** [comment]
> This is a azure portal related feature ask and I believe you have already created a feedback.

Indeed, renaming the flow was just a workaround I was given, it's not related to the original issue. We can track the fix for the workaround there.

Coming back to the original issue here, it is CLI related and the question is: why *runs* can have the same display name but *flows* not? Why is the behavior different there?

**Comment by 0mza987** [comment]
I thought this question is already answered by my previous reply, but I could clarify it again:
It's a bug because we used the display name to create a file share folder to upload the flow content, and as a fix, we will use local flow folder name + timestamp as the remote file share folder name and then you can create multiple flows with the same display-name.

**Comment by spygi** [comment]
I was missing the acknowledgement that it is actually a bug - thank you
