### ISSUE TITLE
[BUG] Edit flow from the UI misbehaves

### ISSUE THREAD

**Issue by spygi** [microsoft/promptflow#1611]
**Describe the bug**
When you edit the title of a flow from the UI, the underlying folder is not renamed as well.

This results in various errors e.g. in the UI

<img width="790" alt="Screenshot 2023-12-27 at 15 34 55" src="https://github.com/microsoft/promptflow/assets/4732694/ca0471b5-c314-4c92-8934-22c696d19e0e">

or in the CLI

```
pfazure flow create --flow flow.dag.yaml --set display_name=CUSTOM_NAME type=chat -w $AZURE_AI_PROJECT_NAME -g $AZURE_RESOURCE_GROUP
[2023-12-27 16:44:32,845][promptflow._cli._utils][INFO] - Use default credential.
Create flow failed with FlowOperationError: Remote flow folder 'CUSTOM_NAME' already exists under 'Users/819a3fe1-c31a-4c1c-881f-zhgsdajdgs/promptflow'. Please change the flow folder name and try again.
```

**How To Reproduce the bug**

- Create a flow and then edit the name.
- Check the folder name in the `Files` section.

**Expected behavior**

When you edit a flow the folder name should be changed as well. Otherwise users can not create a flow with the old name anymore resulting in a lot of zombie flows. See feature request in #1459 

**Running Information:**

Promptflow: promptflow 1.1.0

Operating System
$ uname -a
Linux c206cc41a3f4 6.5.11-linuxkit # 1 SMP PREEMPT_DYNAMIC Mon Dec 4 10:03:25 UTC 2023 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 12 (bookworm)
Release: 12
Codename: bookworm

FROM mcr.microsoft.com/devcontainers/python:3.11

Python Version: Python 3.11.6

**Additional context**

In contact about this with @0mza987 

Original feature request was to be able to update a flow: #1459 and was given this idea as a workaround.

**Comment by D-W-** [comment]
Hi @spygi , we are only tracking prompt flow CLI/SDK issues here. For UI issues, please file OCV in UI:
![image](https://github.com/microsoft/promptflow/assets/7776147/a9e0d2ac-9bcb-4636-a1b1-4cb1c8d52626)

I need to clarify that when editing display name in UI, the folder name won't change is a by design behavior because our UI provides a keep editing experience and display name is a meta data so it won't change folder name.
We'll keep follow this issue for CLI experience: https://github.com/microsoft/promptflow/issues/1610

**Comment by spygi** [comment]
Hi @D-W- and thanks for the feedback. I will open a feedback on the UI then for the UI.

Just note that there is no equivalent feature in the CLI for this: you can not edit the flow name as `pfazure flow create --set display_name...` only creates flows, does not update them.
