### ISSUE TITLE
[Feature Request] pf run remove

### ISSUE THREAD

**Issue by ZhiliangWu** [microsoft/promptflow#1648]
**Is your feature request related to a problem? Please describe.**
Currently, `run` are managed by subcommands under [`pf run`](https://microsoft.github.io/promptflow/reference/pf-command-reference.html#pf-run). However, it is not possible to remove runs if they are not needed any more. 

**Describe the solution you'd like**
Add a command `pf run remove --name` to remove a specific run using its name.

**Comment by stewartadam** [comment]
+1 would be nice to have a auto-clean based on "older than X days"

**Comment by D-W-** [comment]
Hi @ZhiliangWu @stewartadam , we currently have `pf run archive --name` to archive a run and it won't be shown in run list view.
Does that meet your needs? Or you want to delete the run and all it's data permanently from disk?

**Comment by stewartadam** [comment]
Remove from disk in my case

**Comment by D-W-** [comment]
Thanks @stewartadam , we'll use this issue to track `pf run remove/delete` feature request. Batch deletion can be supported with user script on top of `pf run remove/delete`. We have no plan to support batch run deletion in near future. If you still need auto-clean provided by prompt flow in your scenario. Please open another issue for it.

**Comment by ZhiliangWu** [comment]
Hi @D-W-, thanks for your reply. Similar to @stewartadam, I would want to remove it from my disk. 

Currently, all runs seem to be saved under `.promptflow/.run` if I develop locally. Are there any way to remove the runs manually before you release the `pf run remove/delete`. I have tried to delete the corresponding folder but they got recreated again automatically (with empty contents).

**Comment by crazygao** [comment]
pf run delete will be prepared in 1.4.0
