### ISSUE TITLE
[BUG] Odd behavior with path validation for `data` and `flow` path fields of run schema

### ISSUE THREAD

**Issue by stewartadam** [microsoft/promptflow#1650]
**Describe the bug**
When creating a run YAML template, the `data` and `flow` fields are paths that should point to the input dataset and flow respectively. When running a flow locally, PromptFlow appears to inconsistently resolve these local paths relative to the directory of the run YML configuration file and the current working directory (of the shell/script calling `pf`).

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Run `repro.sh` from the reproduction repo here - https://github.com/stewartadam/pf-reldir-repro
2. The last case is expected to fail, but succeeds.

**Expected behavior**
Both the `data` and `flow` fields are consistently parsed relative to config directory.

**Observed behavior**
The `data` field is always resolved relative to the config YML and `flow` is resolved relative to config directory OR current working directory - this could lead to ambiguity. Conversely, when authoring an Azure run configuration, the `flow` needs to be relative to the repo root.

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`:  1.1.1
 - Operating System: MacOS 14.2.1 (23C71)
 - Python Version using `python --version`: Python 3.9.18

**Additional context**
The documentation could use additional detail on the what directory to base the `data` and `flow` fields from.

**Comment by D-W-** [comment]
Hi @stewartadam , thanks for reporting! Both `data` and `flow` should be parsed relative to the YAML file since they are wrote in YAML file. The reason why `flow` also supports parse relative to current working directory is because our schema validation on `flow` is loose. We'll fix it in next release.

**Comment by stewartadam** [comment]
Thanks for the quick response!
