### ISSUE TITLE
[BUG] Activate feature, cannot treat string type 'yes', 'no' correctly

### ISSUE THREAD

**Issue by lisagreenview** [microsoft/promptflow#1651]
**Describe the bug**
If you want to use output from a node with the string of "yes" or "no" it won't work. Guessing Yes/No is treated like True/False.
![image](https://github.com/microsoft/promptflow/assets/10419778/288132bb-a9e2-49dc-a475-8aee0e53c0ca)

It could be limitation of YAML file, but shall we honor the field type, and make sure string value is quoted with '' or ""?
![image](https://github.com/microsoft/promptflow/assets/10419778/2f70d9cd-c4e5-4cb7-8950-8c28be688044)

**Comment by thy09** [comment]
This seems to be an extension behavior that write yaml as `is: yes`, while what we expect is `is: 'yes'`, here is the example:
```
  activate:
    when: ${inputs.input_text}
    is: yes
```

**Comment by PeiwenGaoMS** [comment]
The latest version (1.4.0) of promptflow has been released, utilizing version 1.2 of yaml, where terms like 'yes'/'no' are no longer interpreted as booleans.

After testing and verification, the issue has been resolved. You can download the latest version to try it out.
![image](https://github.com/microsoft/promptflow/assets/111329184/f1a9e10c-52bd-43d0-ad67-2fe656950fdd)
![image](https://github.com/microsoft/promptflow/assets/111329184/508ab809-9d11-466d-97b2-31bff2ebe07a)
![image](https://github.com/microsoft/promptflow/assets/111329184/2c848b6a-d319-4fb1-aec1-44de2d026dac)

I will close this issue. Thank you~
