### ISSUE TITLE
[BUG] Detail relative pathing requirements

### ISSUE THREAD

**Issue by stewartadam** [microsoft/promptflow#1694]
**Describe the bug**
Further to #1650, when `-f` is specified and then other CLI arguments are provided to override fields, the behavior of the path resolution changes. Arguments like `--data` normally are relative to `$PWD` but once `-f` is specified, I'm guessing the CLI arguments get merged on top of the schema properties which makes the pathing relative to that file instead.

It would be nice to have this quirk documented (or adjusted so that paths in CLI arguments are always relevant to `$PWD` which is probably [closer to user expected behavior for path arguments](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) of CLI tools in general).

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. `pf run create --data path/to/data --flow path/to/flow ...` vs `1. pf run create -f configs/runspec.yml --data ../path/to/override/relative/to/yml`

**Expected behavior**
Paths passed via CLI arguments are usually relative to the working directory. If not, that deviation from typical CLI tool behavior should be documented in the `--help` output and in the documentation.

**Screenshots**

**Running Information(please complete the following information):**
- Promptflow Package Version using pf -v: 1.1.1
- Operating System: MacOS 14.2.1 (23C71)
- Python Version using python --version: Python 3.9.18

**Additional context**

**Comment by crazygao** [comment]
Yes, this should be a bug. --data inputs should relative to $PWD, and we'll convert that path to relative to the yaml file internally.

**Comment by crazygao** [comment]
Tracking PR https://github.com/microsoft/promptflow/pull/1702

**Comment by crazygao** [comment]
Hi @stewartadam ,
after some discussion, we think it is better to reserve current --data ../path/to/override/relative/to/yml and make more documentation for this. A solid reason is that it is more straightforward to make you understand this is just a yaml replacement of the runspec file. If you write code against this method, you'll experience the same behavior with you run the flow through pf commands.

**Comment by crazygao** [comment]
Hi, we have added some new comment in the `pf run create --help` for better explaination.

**Comment by stewartadam** [comment]
@crazygao did this change apply to pfazure as well? I'm seeing difference in pathing between creating runs locally or on Azure.

It looks like when creating runs on Azure, the path for `--data` and others must be relative to PWD instead of flow YML location.
