### ISSUE TITLE
[BUG] Flow Operation `create_or_update()` Has Misleading Function Name

### ISSUE THREAD

**Issue by mindlessroman** [microsoft/promptflow#1708]
**Describe the bug**
The name of the function `create_or_update()` in `/src/promptflow/promptflow/azure/operations/_flow_operations.py` suggests one can update a flow. However, as it is implemented for `1.1.1` it is only a `create` operation and not an update. This also occurs in `1.2.0` and `1.3.0`.

This issue may only show up if one explicitly declares the display name, since the default behavior is to append a unix-y timestamp at the end of the flow's folder name ([as seen on line 155 of `_flow_operations.py`](https://github.com/microsoft/promptflow/blob/ee636fc644e6a5a41f9aa473d7befe1f099beea2/src/promptflow/promptflow/azure/operations/_flow_operations.py#L155)) .

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
> NOTE: All the global variables are valid, but I'm not including the contents

1. Create connection to an AML workspace:
  ```python
   credential = DefaultAzureCredential()
   pf = PFClient.from_config( 
       credential=credential,
       path=WORKSPACE_CONFIG_PATH
   )
   ```
2. Upload properly set-up `data` of type `from azure.ai.ml.entities import Data`: `pf.ml_client.data.create_or_update(data)`
3. Upload the flow:
  ```python
   standard_display_name = "some-name"
   pf.flows.create_or_update(
        flow=f"./{FLOW_IDENTIFIER}/standard",
        display_name=standard_display_name
    )
   ```
4. Make changes to the flow, as you would while developing
5. Run the same `create_or_update()` command from  step 3
6.  Receive an error:
   ``` text
FlowOperationError: Remote flow folder 'some-name' already exists under 'Users/<UUID>/promptflow'. Please change the flow folder name and try again.
   ```

**Expected behavior**
I would expect if the function name had "update" that updates were possible. If the advice is to create a new flow with different timestamps even if you explicitly declare the name of the flow, that should be made clear and the function name should be changed.

It should be explicit to either only be create in the function name OR the update feature needs to be rolled out. 

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.1.1 (WSL); 1.2.0, 1.3.0 (Mac)
 - Operating System: [e.g. Ubuntu 20.04, Windows 11] WSL 1 on Windows 10; Mac 14.2.1
 - Python Version using `python --version`: [e.g. python==3.10.12] python 3.10.12 (WSL);  python 3.11.4 (Mac)

**Additional context**

**Comment by 0mza987** [comment]
Thanks for the feedback, we do have plan to support flow update within this interface but it's not implemented yet.
Considering changing interface is a breaking change that we want to avoid, I will update the function docstring and command reference doc to clarify that the flow update functionality is yet to be implemented.

**Comment by mindlessroman** [comment]
> Thanks for the feedback, we do have plan to support flow update within this interface but it's not implemented yet. Considering changing interface is a breaking change that we want to avoid, I will update the function docstring and command reference doc to clarify that the flow update functionality is yet to be implemented.

That'd be awesome! Excited that it will be an upcoming feature. Thank you!
