### ISSUE TITLE
[BUG] (ValueError) client_id should be the id of a Microsoft Entra application.

### ISSUE THREAD

**Issue by kachely** [microsoft/promptflow#1716]
**Describe the bug**
Hi Team,
I always found an error in prompt flow when running command `pf flow build --source . --output docker --format docker`
**Error message:**
 _Generate meta for source 'call_llm_model.py' failed: Failed to load python module from file '/home/vsts/work/1/s/TitanCopilot/chart_generator/docker/flow/call_llm_model.py': (ValueError) client_id should be the id of a Microsoft Entra application._
It appears after I add a logging model into prompt flow. It uses the `ClientSecretCredential(tenant_id_logging, client_id_logging, client_secret_logging)` for getting the credential. I do not have any client_id variable in my code. So I guess there is some conflict with the prompt flow authentication.
Could you please help debug?

**Code in my logging model:**
```
from azure.identity import ClientSecretCredential
from azure.monitor.ingestion import LogsIngestionClient
from azure.core.exceptions import HttpResponseError
import config
from datetime import datetime

class AzureInsightLogger:
    def __init__(self):
        self.dce_endpoint = config.DCE_ENCPOINT
        self.dcr_immutableid = config.DCR_IMMUTABLEID
        self.stream_name = config.STREAM_NAME
        self.credential = self.get_azure_credential()
        self.client = LogsIngestionClient(endpoint=self.dce_endpoint, credential=self.credential, logging_enable=True)

    def get_azure_credential(self):
        tenant_id_logging = config.LOGGING_AZURE_TENANT_ID
        client_id_logging = config.LOGGING_AZURE_CLIENT_ID
        client_secret_logging = config.LOGGING_AZURE_CLIENT_SECRET
        return ClientSecretCredential(tenant_id_logging, client_id_logging, client_secret_logging)

```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Every time I build the prompt as docker file
2. Run `pf flow build --source . --output docker --format docker`

**Expected behavior**
Non error message with a docker file created.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

**Comment by brynn-code** [comment]
where does the 'config' load from? Seems there is some external config file exists in your flow.

**Comment by kachely** [comment]
![image](https://github.com/microsoft/promptflow/assets/20835886/b0513f6e-ad72-4c7a-b561-a21ddb44a5a5)
Yes, I have a config.py which stores some configuration.
![image](https://github.com/microsoft/promptflow/assets/20835886/9ed627c3-c59e-4195-910d-d6d1f978f908)

**Comment by brynn-code** [comment]
Hi, we don't set this 'LOGGING_AZURE_CLIENT_ID' in promptflow, is it possible to share more details? Does it have a value or None or something else, and can we repro it if directly run your code locally without setting the environment variable?

**Comment by brynn-code** [comment]
Offline synced, close the issue.
