### ISSUE TITLE
[BUG] `additional_includes` is not properly handled with `pf flow serve`

### ISSUE THREAD

**Issue by bwilliams2** [microsoft/promptflow#1726]
Any files listed in `additional_includes` within flow.dag.yaml are not available in the expected directory when running `pf flow serve`.

Reproduction
Using the example flow at https://github.com/microsoft/promptflow/tree/main/examples/flows/standard/flow-with-additional-includes with `pf flow serve` results in a ValueError exception.

```
pf flow serve --source .
```

```
  File "/.pyenv/versions/3.11.5/lib/python3.11/site-packages/promptflow/_sdk/_utils.py", line 487, in _merge_local_code_and_additional_includes
    raise ValueError(f"Unable to find additional include {item}")
ValueError: Unable to find additional include ../web-classification/classify_with_llm.jinja2
```

Expected Behavior
It is expected that the `additional_includes` behavior is the same as that during `pf flow test` or `pf flow create` with the files available in the same directory as the source code files.

**Comment by brynn-code** [comment]
Thanks for the feedback, will fix this issue in the coming version

**Comment by brynn-code** [comment]
Will fix in: https://github.com/microsoft/promptflow/pull/1733/files

**Comment by brynn-code** [comment]
Close as 1.4.x released.
