### ISSUE TITLE
[Feature Request] Make browser launch optional for `pf flow serve`

### ISSUE THREAD

**Issue by bwilliams2** [microsoft/promptflow#1734]
Currently running `pf flow serve` automatically launches a browser window with no configuration option to turn it off. Adding a configuration option to disable browser launching would reduce unnecessary clutter and improve development and testing workflows that are API driven.

Desired Solution
Command line argument flag that disables browser
`pf flow serve --source . --browser false`

Alternatives
Currently no alternatives exist as browser launch seems to be hardcoded in current serve app code.

https://github.com/microsoft/promptflow/blob/a5e4b98e005b42efaae0855b8cc7f07671626211/src/promptflow/promptflow/_cli/_pf/_flow.py#L505-L507

**Comment by brynn-code** [comment]
Hi @bwilliams2, we accept this feature request, thanks for your feedback, it would be brought in the next coming version.

**Comment by brynn-code** [comment]
`--skip-open-browser` store true parameter is added here: #1743

**Comment by bwilliams2** [comment]
Great thanks for the quick improvement

**Comment by brynn-code** [comment]
Close as 1.4.x released.
