### ISSUE TITLE
[BUG]Unexpected Node Activation

### ISSUE THREAD

**Issue by chenyugithub365** [microsoft/promptflow#1777]
**Describe the bug**
The `embedding` node depends on the output of the `knowledge_search_route` node. However, even when the `knowledge_search_route` node is bypassed, the `embedding` node is unexpectedly activated, causing anomalies in the entire process.

**How To Reproduce the bug**
The issue occurs 100% of the time. When executing the process of the `loop_output_route` node, the `embedding` node is always unexpectedly activated; however, there are no issues when executing the process of the `knowledge_search_route` node.

**Expected behavior**
When the process is only for chat communication, only the `loop_output_route` node should be activated.

**Screenshots**
![企业微信截图_20240118173337](https://github.com/microsoft/promptflow/assets/128603989/2024ae97-4b1d-43ae-9b4a-372cf008cf9b)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 
 - Operating System: 
 - Python Version using `python --version`:

**Additional context**

**Comment by PeiwenGaoMS** [comment]
Hi @chenyugithub365 , please provide flow.dag.yaml and logs, I will investigate further.

**Comment by chenyugithub365** [comment]
> Hi @chenyugithub365 , please provide flow.dag.yaml and logs, I will investigate further.

Hi @PeiwenGaoMS , it seems that I have found the issue. The problem exists within the Promptflow in AzureAI Machine Learning Studio, whereas there is no similar issue in VS Code.
![企业微信截图_20240119154345](https://github.com/microsoft/promptflow/assets/128603989/8f004d66-e553-491f-954a-2e26ff54d32d)
[ChatFlow__log.txt](https://github.com/microsoft/promptflow/files/13986030/ChatFlow__log.txt)
[flow.dag.yaml.txt](https://github.com/microsoft/promptflow/files/13986033/flow.dag.yaml.txt)

**Comment by PeiwenGaoMS** [comment]
It seems that the `flow.dag.yaml` you provided does not match the screen shoot of AzureAI Machine Learning Studio. From the screen shoot, the `emdding` node does not have activate config, but it exists in your yaml.
![image](https://github.com/microsoft/promptflow/assets/111329184/861e23a7-2f7d-4160-9644-682703e87b6c)
![image](https://github.com/microsoft/promptflow/assets/111329184/c4d6e420-1ed4-47d6-8b93-8c976964f132)

So you are saying that the same flow has issues running in AML, but it will work in VS Code? Or did you find an issue with the definition of your flow?

**Comment by thy09** [comment]
BTW, when you are using AzureAI Machine Learning Studio, you can download the flow folder and check whether the yaml is the same as in extension.

**Comment by chenyugithub365** [comment]
@PeiwenGaoMS 
Ah, I apologize, I uploaded the wrong yaml file. That was a test file where I brainstormed some solutions to a problem. The idea was to add an activation condition to the embedding, knowledge_search, and knowledge_integration nodes: ${route.output} = knowledge_search.
Yes, it runs correctly in VS Code.

Actually, the problem can be identified from the diagram; the embedding was indeed activated incorrectly. I will now upload a new yaml file.

![企业微信截图_20240120093042](https://github.com/microsoft/promptflow/assets/128603989/23cbcfe7-afd1-442f-a534-353a24d20fa9)
[ChatFlow__.log.txt](https://github.com/microsoft/promptflow/files/13996134/ChatFlow__.log.txt)
[flow.dag.yaml.txt](https://github.com/microsoft/promptflow/files/13996135/flow.dag.yaml.txt)

**Comment by chenyugithub365** [comment]
@thy09 Yes, I have checked that the yaml file is consistent with the diagram.

**Comment by PeiwenGaoMS** [comment]
Hi @chenyugithub365 , we can see in the second yaml file, the activate config for the `embedding` node is as shown in the image below. Both 'when' and 'is' are empty strings, which means the activation condition will always be met, and the node will always execute.
![image](https://github.com/microsoft/promptflow/assets/111329184/14863cf2-26b1-4b08-93e5-0a8015cbf273)

I'm guessing you may have filled out the activate config for that node before and then deleted the contents of the box. Currently, this behavior does not actually remove the activate config from the flow yaml file in AzureAI Machine Learning Studio, we will make changes in the future to address this issue. In the meantime, as a workaround, you can manually remove the activate config by clicking "**Raw file mode(原始文件模式)**" in the interface to open and edit the yaml file. 
![image](https://github.com/microsoft/promptflow/assets/111329184/1826537b-88a4-4edc-86b3-04ca43a786e6)

**Comment by chenyugithub365** [comment]
@PeiwenGaoMS 

Yes, I verify and confirm that it is the reason you mentioned. Thank you.
