### ISSUE TITLE
[BUG] Incomplete steps for deployment of flow using Docker for Visual Studio Code Extension

### ISSUE THREAD

**Issue by bhavykhatri** [microsoft/promptflow#1783]
**Describe the bug**
Steps are not clear for which button to click in VS Code Extension. Fix #1782 
![image](https://github.com/microsoft/promptflow/assets/26280748/e554ad5f-4313-4622-b0d1-1bf3aeca0937)

**How To Reproduce the bug**
1. Happens for documentation on web

**Expected behavior**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: On Edge Browser  documentation[e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Comment by 0mza987** [comment]
Thank you for your valuable contribution to our project! Your efforts have helped improve our documentation. We appreciate the time and effort you've put into this. Please feel free to contribute again in the future. Your input is always welcome!
