### ISSUE TITLE
[Contribution Request] Update License for `promptflow-tools` to Match `promptflow`

### ISSUE THREAD

**Issue by mindlessroman** [microsoft/promptflow#1797]
**Is your contribution request related to a problem? Please describe.**
Since the `promptflow` package and the `-tools` package [both roll up to an MIT license](https://github.com/microsoft/promptflow/blob/main/LICENSE), it would make sense that the [wheel for the `-tools`](https://github.com/microsoft/promptflow/blob/main/src/promptflow-tools/setup.py) would have the same license information as [the non-tools package](https://github.com/microsoft/promptflow/blob/main/src/promptflow/setup.py). 

**Detail the functionality and value.**
[Prompt flow's metadata/license on pypi.](https://pypi.org/project/promptflow/)
![image](https://github.com/microsoft/promptflow/assets/7254163/0c62fa58-7e58-4d53-a100-633e4298e3f9)

[Prompt flow tools metadata/license on pypi.](https://pypi.org/project/promptflow-tools/)
![image](https://github.com/microsoft/promptflow/assets/7254163/a997a932-e274-4d6b-8d11-aa38c89da5bf)

**Additional context**
Add any other context or screenshots about the contribution request here.

**Comment by mindlessroman** [comment]
(incoming PR)

**Comment by mindlessroman** [comment]
#1798

**Comment by chjinche** [comment]
The change looks good to me! Thanks a lot @mindlessroman
