### ISSUE TITLE
[Feature Request] Disable Storing Intermediate outputs 

### ISSUE THREAD

**Issue by geoss** [microsoft/promptflow#1800]
**Is your feature request related to a problem? Please describe.**
In the current implementation of Promptflow, all intermediate outputs are stored by default. This results in a significant amount of data being written to disk, as reported by heavy users. For instance, a run of 8000 rows results in a 1.23GB data artifact, despite the actual output being only 4MB. Additionally, each input, prompt, etc., are written to a jsonl, which can be redundant.

As a result, users find themselves having to manually clean up their systems regularly to avoid running out of disk space. This is especially problematic for users with limited storage capacity, such as those using a 2TB VM.

**Describe the solution you'd like**
This feature request proposes the addition of a toggle to turn off storing intermediate outputs, especially for batch runs. This would help manage disk space more efficiently. 

**Describe alternatives you've considered**
An alternative is easy way to grab output files and delete everyting else.  I was recently made aware of CLI tool that will delete and entire run, but this throws out the baby with the bathwater.  That is, I want to grab the output file prior to deleteing the run.

Another alternative is the option to direct the output file to a location other than the directory containing all the run metadata.

**Additional context**

**Comment by D-W-** [comment]
Hi @geoss , thanks for reporting this. I'd like to clarify a few things with you. Do you want to persist run record for runs without intermediate outputs? For example, do you want to `list/show/visualize/etc` this kind of run? Many of prompt flow features are relying intermediate data. 
If you just want to batch run a flow and get output (probably also get metrics). We might support this by create a run without a run record. Which means this kind of run can not be `list/show/visualize/etc`. 
Here's an example:

SDK
```python
          run: Run = pf.run(
              flow="path/to/flow",
              data="path/to/data",
              disable_intermediate_data=True
          )

          # outputs & metrics are available through the run object.
          # output will be list of lines run outputs
          output: list = run._to_dict()["outputs"]
          # sample: [{'output': 1, 'line_number': 1}, {'output': 2, 'line_number': 2}]
          # metrics will be dict of metrics
          metrics: dict = run._to_dict()["metrics"]
          # sample: {'accuracy': 0.5}
          
          # get this kind of run will return error
          with pytest.raises(RunNotFoundError):
              pf.runs.get(run.name)

```

CLI:
```cmd
pf run create --flow path/to/flow --data path/to/data --disable-intermediate-data
```
Sample output
```
{
    "name": "run_name",
    "created_on": "2023-12-26T15:28:10.099618",
    "status": "Completed",
    "display_name": "display_name",
    "description": null,
    "tags": null,
    "properties": {
        "system_metrics": {
            "total_tokens": 0,
            "prompt_tokens": 0,
            "completion_tokens": 0,
            "duration": 5.92971
        }
    },
    "flow_name": "flow_name",
    "data": "path/to/data",
    "output": [
        {'output': 1, 'line_number': 1}, 
        {'output': 2, 'line_number': 2}
    ],
    "metrics": {
        "accuracy": 0.5
    }
}
```

Does this meet your needs?

**Comment by geoss** [comment]
Hi sorry for the slow response.  I missed this and just got a reminder.  Yes, I think "--disable-intermediate-data" would make sense.    For system metrics I think latency is also a useful data point (avg time per row) and success rate (count of failed rows/total rows).  I'm not sure if those stats require the full intermediate output.  They're in the logs now.   Thanks again and sorry for the slow response.

**Comment by D-W-** [comment]
Hi @geoss , I'd like to understand more about your scenario. Since our run's concept is a reproducible, so we stored necessary data(snapshot, inputs, run meta) to persist the run. 
![image](https://github.com/microsoft/promptflow/assets/7776147/f6ab52ed-0769-492b-adb5-8ccc3510d708)
If you don't want to persist run info in your machine, does batch run flow tests meet your need? 
```python
df = pd.read_json("path/to/data", dtype=object, lines=True)
results = []
for _, row in df.iterrows():
    result = pf.test(flow="path/to/flow", inputs=row.to_dict())
    results.append(result)
print(results)
```

Or, we have exposed batch engine to execute flow in batch:
```python
from promptflow.batch import BatchEngine


batch_engine = BatchEngine(flow_file="absolute/path/to/flow")
with tempfile.TemporaryDirectory() as temp_dir:
    result = batch_engine.run(
        input_dirs={"data": "absolute/path/to/data"},
        inputs_mapping={"xxx": "${data.xxx}"},
        output_dir=Path(temp_dir),
    )
```

Does those existing features suit your need?

**Comment by geoss** [comment]
Yes I think these should meet my needs as long as we don't replicate all of
the input data and output data multiple times.  What's the difference
between the above and doing a batch run via the GUI?  Thanks again.

**Comment by D-W-** [comment]
By GUI do you mean the VS Code extension? The batch run in VS Code extension/CLI/SDK used `BatchEngine` as inner implementation. Besides performing a batch run, batch run API is designed to persist the run (and it's inputs/outputs), so that other runs can [reference the data](https://microsoft.github.io/promptflow/how-to-guides/manage-runs.html#create-a-run) from this run.

Compared to the for loop with `pf.test` API, `BatchEngine` provides concurrent execution capabilities which will execute each line  in a new process. If performance is not an issue, you can also choose to run multiple `pf.test`.
