### ISSUE TITLE
Explicit Versioning of the `$schema`

### ISSUE THREAD

**Issue by ZhiliangWu** [microsoft/promptflow#1810]
**Is your feature request related to a problem? Please describe.**
Currently, the `$schema` of flow YAML and run YAML are using the `latest` as versioning, such as `https://azuremlschemas.azureedge.net/promptflow/latest/Flow.schema.json` and `https://azuremlschemas.azureedge.net/promptflow/latest/Run.schema.json`. To ensure consistent references and easy version identification, it would help to keep a version tag in the URI. E.g., the underlying `$schema` is using `http://json-schema.org/draft-07/schema#` with version `draft-07`.

**Describe the solution you'd like**
In parallel to `latest` pointing to the most recent schema version, release the exact versions of the schema, history and respective changelogs.

**Comment by wangchao1230** [comment]
@ZhiliangWu Do you mean you would like some schema url like this?
https://azuremlschemas.azureedge.net/promptflow/v1/Flow.schema.json

**Comment by crazygao** [comment]
Hi, @ZhiliangWu , this https://azuremlschemas.azureedge.net/promptflow/v1/Flow.schema.json is ready for use.
