### ISSUE TITLE
[BUG] Missing out-of-the-box tools

### ISSUE THREAD

**Issue by simon-v-swyftx** [microsoft/promptflow#1825]
**Describe the bug**
The standard DB tools appear to have disappeared.
I've tried reinstalling/upgrading `promptflow-tools` package.
Unsure how to get them back.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a new conda environment
2. Check versions of promptflow and promptflow-tools

**Expected behavior**
Expected:
<img width="1264" alt="image" src="https://github.com/microsoft/promptflow/assets/109499378/04902b5c-954a-4aae-8d87-f5dbd2bd8725">

**Screenshots**
Actual:
<img width="1264" alt="image" src="https://github.com/microsoft/promptflow/assets/109499378/9fcd1f6d-1f68-43dd-a791-2199b780150a">

**Running Information(please complete the following information):**
```terminal
promptflow                       1.4.1
Python (Darwin) 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 09:45:58) [Clang 14.0.6 ]
Python 3.12.1
```

**Comment by DaweiCai** [comment]
Have you installed the promptflow-vectordb package following this doc: https://microsoft.github.io/promptflow/reference/tools-reference/vector_db_lookup_tool.html  ?

**Comment by simon-v-swyftx** [comment]
Derp yes you are correct, sorry!
