### ISSUE TITLE
[BUG]When running the project using Docker, an exception occurs: "Connection 'xxxxxxx' is not found."

### ISSUE THREAD

**Issue by chenyugithub365** [microsoft/promptflow#1841]
**Describe the bug**
Hello everyone, after completing my PromptFlow, I tried to deploy it using Docker but encountered an issue: "Connection 'xxxxxxx' is not found."

**How To Reproduce the bug**
1.Build command used: pf flow build --source "D:\work\source code\AIGC_Flow\chat" --output dist --format docker
![1 构建的文件](https://github.com/microsoft/promptflow/assets/128603989/7dff5052-aa77-4ed1-97d9-4cfe70722e49)

2.Connection configuration has been created.
![2 连接](https://github.com/microsoft/promptflow/assets/128603989/0c28e58d-bce7-4593-893d-e9cec3fb03fe)

3.Details of the connection configuration.
![3 连接的配置内容](https://github.com/microsoft/promptflow/assets/128603989/402eeee8-bfbb-425e-98bf-df1ed02c6c40)

4.Dependency package check for the Docker image.
![4 依赖包检查](https://github.com/microsoft/promptflow/assets/128603989/9d3b2663-67de-4b77-aac7-2603bde30dee)

5.Error encountered when calling the Docker image after it is started.
![5 调用错误](https://github.com/microsoft/promptflow/assets/128603989/02e7180b-1d32-40a6-95b1-c6f6fb84c049)

6.Logs of the Docker image after it is started.
[logs.txt](https://github.com/microsoft/promptflow/files/14040316/logs.txt)

**Expected behavior**

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.2.0
 - Operating System: CentOS Linux 7
 - Python Version using `python --version`: Python 3.9.16

**Additional context**

**Comment by YingChen1996** [comment]
Hi, @chenyugithub365 , thanks for reporting the issue, could you please share your build dockerfile and run file in runit?

**Comment by chenyugithub365** [comment]
Hello, @YingChen1996 , you need the Dockerfile and runit file, right? These files are unmodified and generated by Promptflow.
[runit.zip](https://github.com/microsoft/promptflow/files/14046295/runit.zip)
[Dockerfile.txt](https://github.com/microsoft/promptflow/files/14046298/Dockerfile.txt)

**Comment by YingChen1996** [comment]
btw, make sure docker run your container like below to set your connection key:
![image](https://github.com/microsoft/promptflow/assets/26239730/494221cf-41c0-4fa2-b31f-ab1746512e30)

**Comment by chenyugithub365** [comment]
I can provide the project code and the complete built files, but I have desensitized some files: dist\connections and chat\python_enterprise_website_knowledge_search.py and dist\flow\python_enterprise_website_knowledge_search.py. I don't think this should affect the troubleshooting of the problem.

[chat.zip](https://github.com/microsoft/promptflow/files/14046962/chat.zip)
[dist.zip](https://github.com/microsoft/promptflow/files/14046963/dist.zip)

The command to start the Docker image is: 
docker run -p 8080:8080 -e AZURE_OPENAI_JAPANEAST_API_KEY=xxx -e AZURE_OPENAI_WESTUS_API_KEY=xxx -d chat:latest

**Comment by YingChen1996** [comment]
it seems there're typo in your requirements.txt `pywin32==306`: not match version, actually docker is for linux/mac environment.

For the issue, I can repro now. I think maybe it's because some package issue. When I only keep the 2 packages in requirement.txt, it can create connection successfully. I will follow up with folks to continue investigate.
![image](https://github.com/microsoft/promptflow/assets/26239730/8cd67e1e-8d72-4c66-8627-8980b1d65af4)

![image](https://github.com/microsoft/promptflow/assets/26239730/e019f5a6-d185-4dba-bdbe-bcdfeece8eb6)

**Comment by YingChen1996** [comment]
the root cause is that `kering_pass.cfg` is not generated by keyrings.alt, maybe you need double check your package list in requirement.txt
![image](https://github.com/microsoft/promptflow/assets/26239730/717bd32d-4fb6-4fe8-b3aa-1dfefd05c074)

correct one should be 
![image](https://github.com/microsoft/promptflow/assets/26239730/e952cf13-824b-4bcc-a065-f34100949754)

**Comment by chenyugithub365** [comment]
Great, your discovery is excellent. It seems that too many dependency packages were imported. I exported all the packages in the virtual environment. The dependency packages pywin32==306 and pywin32-ctypes==0.2.2 were manually removed when creating the image, so there was no impact.

I will reduce the number of dependency packages.

**Comment by chenyugithub365** [comment]
Hi, @YingChen1996 , I have successfully resolved the issue based on your guidance. The solution is to streamline the dependencies configured in the requirements.txt file (in fact, only promptflow and promptflow-tools need to be retained). Thank you very much.
