### ISSUE TITLE
Flow docker build failure

### ISSUE THREAD

**Issue by vladfeigin** [microsoft/promptflow#1868]
When building a docker with: `docker build dist -t flow-name`  the following error occurs:
     
      psutil could not be installed from sources because gcc is not installed. Try running:
      sudo apt-get install gcc python3-dev
      error: command 'gcc' failed: No such file or directory
I'm running in Python virtual environment with Python version 3.9.6 on Mac

Adding `RUN apt-get update && apt-get install -y gcc python3-dev`  to Dockerfile resolves the issue.

**Comment by YingChen1996** [comment]
Thanks for reporting the issue. I have added gcc dependency in this pr: https://github.com/microsoft/promptflow/pull/1840/files
