### ISSUE TITLE
[Contribution Request][promptflow-azure-ai-language] Update package documentation and example flows.

### ISSUE THREAD

**Issue by murraysean** [microsoft/promptflow#1900]
**Is your contribution request related to a problem? Please describe.**
Azure AI Language has developed a promptflow custom tool package `promptflow-azure-ai-language` to expose Language capabilities to users. This contribution request updates the package's docs and examples per the contribution guidelines listed [here](https://microsoftapc.sharepoint.com/teams/PromptFlow/SitePages/contribution-guidance-for-ms-internal-contributors.aspx#how-to-contribute-sample-flow-%F0%9F%8E%A2). 

Please see this older [issue](https://github.com/microsoft/promptflow/issues/1096) and [PR](https://github.com/microsoft/promptflow/pull/1097) for contribution level 1.

**Detail the functionality and value.**
Updated documentation and example flow use-cases for the `promptflow-azure-ai-language package`.

**Additional context**
See current PR [here](https://github.com/microsoft/promptflow/pull/1901).

**Comment by brynn-code** [comment]
Hi @murraysean , we have both examples and docs added, please reach here:
Example: https://github.com/microsoft/promptflow/tree/main/examples/flows/integrations
Docs: https://microsoft.github.io/promptflow/integrations/tools/azure-ai-language-tool.html

**Comment by murraysean** [comment]
Hi @brynn-code, this is an update to the existing docs and examples. I have recently updated the PyPI package and want the docs/examples in the Promptflow repo to reflect the changes. So users can see the most up-to-date information.
