### ISSUE TITLE
[BUG] After conda activate pf, command pf -v failed

### ISSUE THREAD

**Issue by mydim** [microsoft/promptflow#1993]
**Describe the bug**
After conda activate pf, command **pf -v** failed

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1.conda create --name pf
2. conda activate pf
3. pip install promptflow promptflow-tools
4. pf -v

**Expected behavior**

**Screenshots**

![image](https://github.com/microsoft/promptflow/assets/10175766/e09b1318-6b7d-4177-8198-d63606c2d6a5)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

**Comment by 0mza987** [comment]
Hi @mydim , 

I could not repro this bug in my machine. Seems `promptflow` is not installed in your environment, can you please check current env with `pip list`? If promptflow is not in there, try install with `pip install promptflow promptflow-tools`. If it still cannot be installed, please paste the screenshot and lets see what the logs are.
