### ISSUE TITLE
[BUG] promptflow-tools not appearing inside VS Code.

### ISSUE THREAD

**Issue by tkuralt** [microsoft/promptflow#2005]
**Describe the bug**
promptflow-tools not appearing inside VS Code.
See screenshots: 
![image](https://github.com/microsoft/promptflow/assets/43473098/2defe28e-48d8-4c95-b62d-8f4d2fca1ff3)

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Installed: pip install promptflow promptflow-tools
2. Restarted VS Code
3. Created new PromptFlow project (used Chat flow with template)
4. In the tools sections I am missing embedding tools and others that are included in promprflow-tools package. I can only access LLM, Python and Prompt (see screenshot above).

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.5.0
 - Operating System: Windows 11
 - Python Version using `python --version`: 3.12.0

**Additional context**
I have also tried to follow these steps: https://microsoft.github.io/promptflow/how-to-guides/faq.html#installed-tool-not-appearing-in-vscode-extension-tool-list

**Comment by tkuralt** [comment]
Has this issue been checked already? there is also error when executing `pf tool list:`
![image](https://github.com/microsoft/promptflow/assets/43473098/54ec2db4-d38f-400e-8caa-cbe772564032)

I would like to know if this is an issue with version 1.5.0 or is it just something wrong with my configuration.

**Comment by jeff-ywang** [comment]
I have encountered the exact same issues as above with Python 3.12. The issues went away when I downloaded Python to 3.11.

**Comment by lumoslnt** [comment]
Hi @tkuralt @jeff-ywang, the fix has been released in pf 1.6.0, you can upgrade the package to the latest version to verify if the issue has been resolved. Thanks!

**Comment by jeff-ywang** [comment]
I am no longer seeing the issue with Python 3.12 and promptflow 1.7
