### ISSUE TITLE
[BUG] PromptFlow Run details UI in AML is unresponsive

### ISSUE THREAD

**Issue by danigian** [microsoft/promptflow#2008]
**Describe the bug**
The Azure ML UI for viewing PromptFlow Run details gets unresponsive when the run is including thousands of small files.

**How To Reproduce the bug**

1. With pfazure, submit a run including around 7k small files
2. Run will succeed, but when navigating the Azure ML UI, things get unresponsive

**Expected behavior**
AML doesn't try to load immediately all the files, but lazily get them (e.g. `load more...` button might be added)

**Comment by 0mza987** [comment]
Hi @danigian,

Thanks for the feedback, we need to clarify that github issues are mainly for promptflow SDK/CLI issues. For azure related issues (especially UI experience), please create user feedback on AML workspace:

<img width="442" alt="image" src="https://github.com/microsoft/promptflow/assets/2572521/9d64930e-80e6-4853-9b7c-ec7e4a8c9e8b">
