### ISSUE TITLE
[BUG] pfazure: Custom image for a flow is not honored when submitting a Flow

### ISSUE THREAD

**Issue by danigian** [microsoft/promptflow#2009]
**Describe the bug**
We currently have a **working** Flow based on a custom container image (from now on named `v1`).
`v1` is based on promptflow-stable `20240111.v2` and includes promptflow python sdk v1.4.1
Everything works fine.

We decide to update the image for the Flow to a `v2` based on promptflow-stable `20240205.v2` and pf python sdk v1.5.0
Image is created fine and can be used without any issue using the UI experience and manually modifying the environment in flow.dag.yml.

When submitting a run with the same flow.dag.yml using pfazure, the old image is used for the run (regardless of the content of `environment` field in flow.dag.yml)

**Expected behavior**
New image is taken into account when submitting the flow run. 

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.5.0
 - Operating System: ubuntu-latest from GH Actions
 - Python Version using `python --version`: 3.9.18

**Comment by danigian** [comment]
I am using automatic runtime

**Comment by D-W-** [comment]
Offline synced, the root cause was we used same automatic runtime session for same flow. We'll change the behavior to use user id, flow folder name and environment (image, python requirements) to decide session id to avoid the issue.
