### ISSUE TITLE
pfazure connection similar to pf connection

### ISSUE THREAD

**Issue by ZhiliangWu** [microsoft/promptflow#2013]
**Is your feature request related to a problem? Please describe.**
When we develop with promptflow locally, we can create connections using `[pf connection create`](https://microsoft.github.io/promptflow/reference/pf-command-reference.html#pf-connection). Meanwhile, if we want to run the flow in Azure Machine Learning workspace, we need to go through the UI to click all necessary steps. 

**Describe the solution you'd like**
Similar to all commands under `pf connection`, we can have `pfazure connection create --subscription <> --resource-group <> --workspace <>` to create a connection in an AML workspace. `pfazure connection list`to list all available connections in the AML workspace.

**Describe alternatives you've considered**
Clicking in the UI.

**Comment by wangchao1230** [comment]
+ @cloga

**Comment by cloga** [comment]
Hi @ZhiliangWu ,
Connection is Azure resource, we have dedicate SDK to provide control plane (CRUD) operation of them, here is example code: 
https://github.com/azure/azure-sdk-for-python/blob/main/sdk/ai/azure-ai-resources/tests/connections/e2etests/test_connection_operations.py

@MilesHolland who working on connection CRUD support in Azure SDK.

**Comment by cloga** [comment]
@ZhiliangWu 
We don't have plan now, PF azure mainly focus on the data plane operation for Azure resources, for control plane things we would recommend to use Azure SDK directly. For connection case, pf azure focus on consume connection in prompt flow runtime.
