### ISSUE TITLE
Flow Deployment in external application

### ISSUE THREAD

**Issue by surendransuri** [microsoft/promptflow#2019]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

The flow created using the prompt flow can it be deployed in other external applications?

**Comment by D-W-** [comment]
Hi @surendransuri , we have ability to deploy prompt flow to local/cloud services. You can reference [here](https://microsoft.github.io/promptflow/how-to-guides/deploy-a-flow/index.html) for docs.

**Comment by surendransuri** [comment]
Hi, we have tried deploying prompt flow in external application like AKS and it was successfully deployed there. But while during inference it was not giving proper results.

Tried both post and get methods:

![image](https://github.com/microsoft/promptflow/assets/94795305/98efb7d3-ba8a-41f8-ab86-7ccefdf199e0)

![image](https://github.com/microsoft/promptflow/assets/94795305/4ad037a6-b572-4d7c-97e2-152127e2a41e)

Please guide for inferencing the deployed model
