### ISSUE TITLE
Uploading additional docs for Q&A in Azure Prompt Flow

### ISSUE THREAD

**Issue by surendransuri** [microsoft/promptflow#2022]
**Describe the bug**
A clear and concise description of the bug.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1.

**Expected behavior**

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

I have deployed a Q&A model to the endpoint. During creation of the flow initial some of the documents were uploaded and indexes created from that. Now I need to add some more additional files to that datastore and add more indexes. How to achieve this without redeploying the model.

**Comment by D-W-** [comment]
Hi @surendransuri , prompt flow itself did not provide ability to update the model after deployed. But I think this can be achieved by making your code can dynamically load files. E.g. load indexes dynamically instead of hard code the index file path.

**Comment by surendransuri** [comment]
Can you please share the code snippet/reference for achieving this dynamically loading the files.

**Comment by D-W-** [comment]
The specific code is related to your business scenario, but the idea is generally like this:
```python
container_client = blob_service_client.get_container_client(container_name)

# Initialize FAISS index
index = faiss.IndexFlatL2(128)  # Assuming 128-dimensional vectors

# Download blobs
for blob in container_client.list_blobs():
    print(f"Downloading blob {blob.name}...")
    blob_client = blob_service_client.get_blob_client(container_name, blob.name)
    blob_data = blob_client.download_blob().readall()

    # Load blob data into a numpy array
    vector_data = np.frombuffer(blob_data, dtype=np.float32)

    # Reshape the data into a 2D array where each row is a vector
    vector_data = vector_data.reshape(-1, 128)

    # Add vectors to the FAISS index
    index.add(vector_data)
```
Since we don't have plan to support this in prompt flow. I'm closing this issue.
