### ISSUE TITLE
Promptflow SDK code example doesn't run

### ISSUE THREAD

**Issue by Shruti-codes** [microsoft/promptflow#2023]
**Describe the bug**
Code example from https://github.com/microsoft/promptflow/blob/main/examples/tutorials/get-started/quickstart-azure.ipynb fails to run. Running below code  gives error.
```
base_run = pf.run(
    flow=flow,
    data=data,
)
print(base_run)
```
![image](https://github.com/microsoft/promptflow/assets/30073239/10e5cbcc-f3da-48cb-aaec-33644a240426)

**Running Information(please complete the following information):**
 - Promptflow Package Version  = 1.5.0
 - Visual Studio Code Promptflow SDK
 - Python Version = 3.9.18

**Library Installation**
promptflow[azure]
promptflow-tools

**Comment by D-W-** [comment]
Hi @Shruti-codes , I could not repro your issue in 1.5.0, could you run `!pip show promptflow` in notebook to check the prompt flow version?  
![image](https://github.com/microsoft/promptflow/assets/7776147/abb6db0e-990a-4b85-84ec-35680f073d5c)

**Comment by Shruti-codes** [comment]
Hi, I am closing the issue as I could run the previous code after reinstalling promptflow. Thanks.
