### ISSUE TITLE
[BUG] [VSCode Extension] Package not installed

### ISSUE THREAD

**Issue by tvanvalkenburg** [microsoft/promptflow#2024]
I am getting an error saying "Can't find tool promptflow_vectordb.tool.common_index_lookup.search". The image below shows that the package is installed, along with `promptflow` and `promptflow-tools`. The text printed to the terminal is the output of `pip list` in the same virtual environment in which the flow is being executed.

![image](https://github.com/microsoft/promptflow/assets/43729867/b931b6cf-8ee1-476d-8962-32ba1d4c22c2)

Running on Mac OS Sonoma 14.3.1.

**Comment by Kevinlee49** [comment]
It seems to be a duplicate of #788

And if you use the Vector Index Lookup tool, it has been deprecated. Therefore, I recommend you to upgrade to the new index lookup tool. 

It is well written in this link.
https://learn.microsoft.com/en-us/azure/ai-studio/how-to/prompt-flow-tools/index-lookup-tool

**Comment by D-W-** [comment]
Hi @dans-msft @Adarsh-Ramanathan , could you help confirm @Kevinlee49's comment? Thanks!

**Comment by tvanvalkenburg** [comment]
> It seems to be a duplicate of #788
> 
> And if you use the Vector Index Lookup tool, it has been deprecated. Therefore, I recommend you to upgrade to the new index lookup tool.
> 
> It is well written in this link. https://learn.microsoft.com/en-us/azure/ai-studio/how-to/prompt-flow-tools/index-lookup-tool

I believe that I am using the index lookup tool. My code is below:

```
- name: lookup_question_from_indexed_docs
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
```

This is the code that is auto-generated in the Studio when adding an IndexLookup:

![image](https://github.com/microsoft/promptflow/assets/43729867/d1292e55-d0b4-4516-989d-6e74e7f449a1)

![image](https://github.com/microsoft/promptflow/assets/43729867/59a10870-eeb4-4934-b8e5-649b35e886fd)

**Comment by Kevinlee49** [comment]
My index lookup looks like this 

![image](https://github.com/microsoft/promptflow/assets/86863395/243f6e03-e2aa-4cda-ad95-128dabe7d759)

**Comment by Adarsh-Ramanathan** [comment]
@tvanvalkenburg, can you share the full output of running `pip list`? I suspect you're missing one or more dependencies - maybe from forgetting to install promptflow-vectordb's `azure` exta? Running `pf tool list` and looking for errors in the output could also be useful.

**Comment by tvanvalkenburg** [comment]
> @tvanvalkenburg, can you share the full output of running `pip list`? I suspect you're missing one or more dependencies - maybe from forgetting to install promptflow-vectordb's `azure` exta? Running `pf tool list` and looking for errors in the output could also be useful.

The output of `pip list` is attached.
[piplist.txt](https://github.com/microsoft/promptflow/files/14356661/piplist.txt)

**Comment by Adarsh-Ramanathan** [comment]
@tvanvalkenburg - can you also run `pf tool list` and share the output?

**Comment by tvanvalkenburg** [comment]
I've attached the output
[pf_tool_list.txt](https://github.com/microsoft/promptflow/files/14371056/pf_tool_list.txt)

**Comment by Adarsh-Ramanathan** [comment]
@tvanvalkenburg , can you run `pip install promptflow-vectordb[azure]` and see if that resolves your issue?

**Comment by tvanvalkenburg** [comment]
I tried this previously and got an error. I've tried it again just now to confirm: 

![image](https://github.com/microsoft/promptflow/assets/43729867/29e8b51a-897d-4fe0-8493-36c69b433a20)

**Comment by Adarsh-Ramanathan** [comment]
This is the likely source of the issues that you're seeing. What python version are you using?

**Comment by Adarsh-Ramanathan** [comment]
That's strange - I ran `pip install promptflow-vectordb[azure]` in a python 3.11.6 container to verify, and it does work for me. Do you have any custom index sources configured in your environment, by any chance?

In any case, based on your `pip list` output, the only packages you're missing from the azure extra are azure-keyvault and azureml-rag. Can you try manually installing them?

```
azure.keyvault>=4.2.0
azureml.rag[azure,azure_cosmos_mongo_vcore,cognitive_search,faiss,milvus,pinecone]>=0.2.23
```

**Comment by tvanvalkenburg** [comment]
So I think we may be onto something. 

Firstly, I have been using Python installed through `pyenv`. I think that this may be the cause of problem related to not being able to find `promptflow-vectordb[azure]`. 

I've tried installing the packages in a container build on the official Python 3.11.6 image, and pip is able to find the packages. However, when trying to run the install I get the following error:

![image](https://github.com/microsoft/promptflow/assets/43729867/101735c6-f708-4df3-aafb-1640f69e3d4d)

**Comment by Adarsh-Ramanathan** [comment]
It's strange that pip is attempting to install azureml-rag 0.2.23 instead of 0.2.25, which is the latest version that's compliant with that version constraint.

I set up container with pyenv, ran `pyenv install 3.11.6` followed by `pyenv global 3.11.6`, `pip install promptflow promptflow-tools`, and `pip install promptflow-vectordb[azure]`; everything ran without errors, including installing `azureml-rag 0.2.25`.

Is there anything else different about your environment that you think would be helpful in getting a repro going?

**Comment by tvanvalkenburg** [comment]
Unfortunately it doesn't work. I tried in a fresh Python 3.11.6 container

**Comment by tvanvalkenburg** [comment]
An update on this issue. I ran into a similar problem trying to install the `az ml` CLI. The problem with the CLI was that there is no arm64 wheel for `azureml-dataprep-rslex`. More details can be found at this issue: https://github.com/Azure/azure-cli/issues/28600.

I got around the problem with the CLI by installing an older version, as is documented in the issue linked above. However, I am still not able to make it work when trying to install `promptflow-vectordb`.

**Comment by tvanvalkenburg** [comment]
I was able to solve the issue by creating a conda environment with x_86 architecture. Within that environment I am able to install the required packages without issue. It appears that the problem is that the Azure ML Python SDK has gaps on Apple's ARM chips.

**Comment by orasik** [comment]
I'm having the same issue.

I tried with multiple python versions [3.8, 3.9, 3.10, 3.11, and 3.12].

I have also tried in Apple M1 and Ubunute 22, same issue.

Tried with venv and conda, same issue.


```
pip install 'promptflow-vectordb[azure]'
```

Error 
```
ERROR: Cannot install azureml-dataprep because these package versions have conflicting dependencies.

The conflict is caused by:
    azureml-dataprep 5.2.1 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.2.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.6 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.5 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.4 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.3 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.2 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.1 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.0.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 4.14.1 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.14.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.10 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.9 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.8 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.1 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.3 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.1 depends on dotnetcore2<4.0.0 and >=3.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
