### ISSUE TITLE
[Feature Request] Deploy multiple flows into same endpoint/single container?

### ISSUE THREAD

**Issue by Porkechebure** [microsoft/promptflow#2100]
**Is your feature request related to a problem? Please describe.**
Nowhere in docs is found how to deploy more than one prompt flow that responds on the same endpoint in the fashion of:

localhost:8080/indexingflow

localhost:8080/chatwithdata

localhost:8080/summary

and so on.

**Describe the solution you'd like**
As with any WebAPI, you should be able to deploy all the flows in a single container or endpoint (even with [Development Server](https://microsoft.github.io/promptflow/how-to-guides/deploy-a-flow/deploy-using-dev-server.html) or [any other](https://microsoft.github.io/promptflow/how-to-guides/deploy-a-flow/index.html) development option)

The idea is to have a single endpoint to call and not to have multiple containers or whatever each one with a single prompt flow in it.

**Describe alternatives you've considered**
Couldn't find one.

**Additional context**
The same have been asked [here](https://learn.microsoft.com/en-us/answers/questions/1532923/deployment-of-prompt-flow) but no response was given up to this day.

**Comment by brynn-code** [comment]
Hi @Porkechebure , thanks for reaching us, currently promptflow does not support multiple flow in one endpoint, but I believe you are able to run multiple image on one container's different ports like app service or managed online endpoint. The port default to 8080 in the DockerFile exported. 
![image](https://github.com/microsoft/promptflow/assets/24237253/54a6ceef-00a2-467f-84cd-646a703636e0)
For example, if you are using our script to deploy flow on app service, after changing the port in DockerFile, update the corresponding port config for app service should work.
![image](https://github.com/microsoft/promptflow/assets/24237253/b832c51e-1cf1-4601-941a-ad610735c16c)

**Comment by Porkechebure** [comment]
> ur script to deploy flow on app service, after changing the port in DockerFile, update the corresponding port config for app service should work.

It would make much sense to have a unique endpoint with various routes and each one is a flow.
Beside this I don't understand what you're saying.

You mean running a single container and publish inside all the flows each one with a different port?

**Comment by brynn-code** [comment]
Yes, that's it. As promptflow not support deploy multiple flow with unique routes for now.

**Comment by Porkechebure** [comment]
> Yes, that's it. As promptflow not support deploy multiple flow with unique routes for now.

Well, thanks. Got it.
Better than nothing I guess :)

**Comment by raphattack** [comment]
@brynn-code sorry to revive this thread, but I wanted to better understand your answer.

> As promptflow not support deploy multiple flow with unique routes for now.

Is it not possible to have two unique flows for two unique endpoints?
- flow_1 to endpoint /flow1
- flow_2 to endpoint /flow2

If that is not possible, is it possible to add an endpoint that is not connected to a flow?
- flow_1 to endpoint /flow1
- /ping endpoint, no flow connected

Our internal k8s infrastructure configures a liveness/readiness probe on the /ping endpoint, so this is mandatory for us. Our service will not start without the presence of the /ping endpoint. 

Is there an example of how we can achieve this with promptflow?

Is there a `python` example that is equivalent to this command?
```
promptflow.core._serving.app:create_app()
```

Is the endpoint name configurable? Apologies for all of the questions, we have just started exploring promptflow and it has been very powerful so far, we are just trying to see how configurable it is for our use case.
