### ISSUE TITLE
[BUG] Defaults aren't getting saved in the `flow.dag.yaml` in the Promptflow UI (AML Studio)

### ISSUE THREAD

**Issue by prasann** [microsoft/promptflow#2133]
**Describe the bug**

For a flow, when we fill in the default value through the UI it gets persisted. However, I don't see that information in the `flow.dag.yaml`. This causes issue, if we download the flow files and start to work within VSCode.

This seems to be a recent issue, I have seen this working in the past. 

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:

- Create a flow (Standard)
- Update the default value of the input
- Save the flow
- Switch to the `raw file mode` 
- The file doesn't have the defaults populated.

**Expected behavior**

- the `raw file` of `flow.dag.yaml` should have the default property setup.

**Screenshots**

<img width="863" alt="UIMode" src="https://github.com/microsoft/promptflow/assets/380340/c2ce75cc-7fe3-4c44-9a20-2ce2e56c487e">
<img width="849" alt="FileMode" src="https://github.com/microsoft/promptflow/assets/380340/f91b8b82-b55e-41d5-8472-56d170951d89">

**Running Information(please complete the following information):**
Happens in the Prompflow inside the AML studio.

**Additional context**

**Comment by 0mza987** [comment]
Hi @prasann,

Thanks for your feedback. For azure portal related feedback, please refer to [Frequency asked questions (FAQ) — Prompt flow documentation](https://microsoft.github.io/promptflow/cloud/azureai/faq.html) and create feedback on azure portal, thanks!
