### ISSUE TITLE
[Feature Request] Allow custom handling of errors

### ISSUE THREAD

**Issue by adamdougal** [microsoft/promptflow#2160]
**Is your feature request related to a problem? Please describe.**
We have a instance of Azure OpenAI deployed with provisioned throughput. If the call to this instance fails, due to this instance being fully utilized, we'd like to be able to fallback to a pay-as-you-go instance. We'd like to be able to do this fully in Prompt Flow.

**Describe the solution you'd like**
The ability to continue the flow on error and handle the error in a custom way.

**Describe alternatives you've considered**
To work around this for now, we will need to either:
- Deploy a copy of our flow that calls the pay-as-you-go Azure OpenAI instance and handle the fallback in the calling application
- Deploy a custom service that sits between Prompt Flow and Azure OpenAI to foward requests and handle errors

**Additional context**
This is just one use case. There are many more instances where custom handling of errors would be desirable.

**Comment by 0mza987** [comment]
Hi @adamdougal,

Thanks for your feedback. Sounds like you could use a costomized python node to send LLM calls and handle the error if it hits rate limit error(instance being fully utilized). Here is a basic example about how to send LLM calls in a python node:  [promptflow/examples/flows/standard/basic-with-connection/hello.py at main · microsoft/promptflow](https://github.com/microsoft/promptflow/blob/main/examples/flows/standard/basic-with-connection/hello.py)

Please let me know if this method aligns with your requirements. If not, kindly provide more details about your use case and the specific features you would like to have when referring to "custom handling of errors." This information will help us gain a better understanding of your scenario and assist you further.

**Comment by adamdougal** [comment]
Heya @0mza987! Thanks for your response. That's a good point, that certainly adds a third option. However, I think the ideal solution wouldn't require us to move away from the built in OpenAI tool. It would also make it harder to add and evaluate prompt variants.

**Comment by 0mza987** [comment]
@adamdougal  

> It would also make it harder to add and evaluate prompt variants.

Could you share more details about this? The example I provided above also contains a prompt node (hello_prompt). To my understanding, you can modify/add variants for the prompt node and the usage should not be much different from a prompt node connected with a build-in llm node.

**Comment by adamdougal** [comment]
Hi @0mza987

Sorry I didn't get a chance to look at this again until now. What I mean is if I can use the LLM node type, I can add extra variants, even getting it to generate variants for me. When I do that, I can then view the outcome of each variant easily in the outputs tab:
 
![image](https://github.com/microsoft/promptflow/assets/1589887/c79f5882-bcd5-4748-bc80-c552b7bdffb5)
_(this prompt asks the LLM to write a joke on the inputted topic)_

I don't believe this is possible if I now use a custom python implementation. It's also then more code that I need to maintain.

Please correct me if I'm wrong and if this is still achievable. Thanks

**Comment by adamdougal** [comment]
Hey @0mza987, do you have any feedback based on my last message? Thanks

**Comment by 0mza987** [comment]
Hi @adamdougal , sorry for the late reply since this issue has been in `closed` status. 

For your question, yes you can do that, just create different variants for the `prompt` node, here's a sample:

![image](https://github.com/microsoft/promptflow/assets/2572521/8ebe40e1-0f8f-4b0d-80da-2f8c73aed52b)

![image](https://github.com/microsoft/promptflow/assets/2572521/7cff5d3d-7268-4f91-96d1-158943740974)

And after the run is successful:

![image](https://github.com/microsoft/promptflow/assets/2572521/f0f107b8-0b7f-4965-aade-70afbca46b49)

**Comment by adamdougal** [comment]
Gotcha, thanks!
