### ISSUE TITLE
[Feature Request] Add `status` field to the output of `runs.get_details` 

### ISSUE THREAD

**Issue by prasann** [microsoft/promptflow#2173]
**Is your feature request related to a problem? Please describe.**
For each run currently, the `get_details` returns the inputs and outputs. It is good to have the `status` of the run as well. I don't see any other option right now to fetch the status of the run.

**Describe the solution you'd like**
Would like to have `status` as a column in the `DataFrame` returned as part of `get_details` method.

**Describe alternatives you've considered**
Currently, we are looking to use the Azure ML SDK and trying to download the run output from there. This seems to be a tedious process, since we have to merge the outputs with the flow_artifacts ourselves to get the status of each run.

**Additional context**

I did went about debugging the code, and have some observations.

For the `pfazure` runs. I see the endpoint `BulkRuns/{run_name}/childRuns` has the status field filled up. So seems to be straightforward for the `pfazure` runs. 

For the local runs, i don't see a straightforward option. Happy to raise a PR if i get some support on this.

**Comment by 0mza987** [comment]
Hi @prasann, 

Just want to confirm, did you mean the status of the entire batch run or the status of each child run? The endpoint you mentioned gets the status of latter ones.
