### ISSUE TITLE
[Feature Request]Support use several connections in one LLM node to allow bigger parallel count and faster batch run

### ISSUE THREAD

**Issue by luxiong-ms1** [microsoft/promptflow#2183]
**Is your feature request related to a problem? Please describe.**
Normally, we may have several GPT connections in several regions. However, we can only use one connection in one LLM node in promptflow. For batch runs with large dataset, it might take a long time to wait for the run to be completed. 

**Describe the solution you'd like**
Allow multiple GPT connections for one LLM node. For each flow, it might randomly or evenly select one from them. Therefore, we can utilize multiple connections to speedup batch run.

**Describe alternatives you've considered**

**Additional context**

**Comment by 0mza987** [comment]
Hi @luxiong-ms1 ,

Thanks for your feedback. Sounds like you could use a costomized python node to pass multiple connections and send LLM calls with different connection, randomly or normally, anyhow you like. Here is a basic example about how to send LLM calls in a python node: [promptflow/examples/flows/standard/basic-with-connection/hello.py at main · microsoft/promptflow](https://github.com/microsoft/promptflow/blob/main/examples/flows/standard/basic-with-connection/hello.py), it's a single conenction sample but it's straightforward to modify it to be a multi-connection type sample.

Or do you mean you want prompt flow to support multiple connection usage for built-in LLM node? If that's the case, please elaborate on your user scenario then we can have a better understanding and discuss internally. Thanks.
