### ISSUE TITLE
[BUG] Cannot use load_flow in AzureML prompt flow

### ISSUE THREAD

**Issue by khchan** [microsoft/promptflow#2194]
**Describe the bug**

Using the `load_flow` method to call nested flows within a current flow.does not work in both the:
* Azure ML workspace environment (web promptflow UI)
* When deployed as a real-time endpoint

The exact same flow works when running the flow in VSCode.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:

Azure ML workspace environment (web promptflow UI):
1. Create a sample flow in Azure ML 
2. Create a folder in that flow and nest a flow inside it
3. Use `load_flow` to call it from the parent flow
4. Calling the flow returns an error: Connections in the child flow can't be found

When deployed as a real-time endpoint:
1. Deploy the provided sample flow
2. Calling the flow returns an error

**Expected behavior**
I should be able to invoke flows with `load_flow` in the Azure ML environment.

**Screenshots**
I have a basic flow that calls a sub-flow (containing the sample joke flow) in a folder:
<img width="360" alt="Screen Shot 2024-03-01 at 1 29 03 PM"
 src="https://github.com/microsoft/promptflow/assets/1270511/e8ebd70a-0ac1-4f1b-a14b-c43435a96e16">

The flow consistently fails, saying the connection is not found, despite being defined (and working) in the outer flow:
<img width="1119" alt="Screen Shot 2024-03-01 at 1 36 12 PM" src="https://github.com/microsoft/promptflow/assets/1270511/8fbbb583-b409-4bb5-babf-d40db1bd20d5">

If I comment out the code that uses `load_flow`, I can confirm the connection works from the parent flow:
<img width="1662" alt="Screen Shot 2024-03-01 at 1 47 04 PM" src="https://github.com/microsoft/promptflow/assets/1270511/4f9855f1-1bdc-4c45-86d8-db94a5b17823">

When I deploy the flow to a real-time endpoint in Azure ML to see if it's just an issue with the web UI I get a different error:
```
➜  ~ curl --location 'https://test-load-flow.eastus.inference.ml.azure.com/score' \
--header 'azureml-model-deployment: test-load-flow-3' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <token>' \
--data '{
    "topic": "cats"
}'
{"error":{"code":"UserError","message":"Source /var/runit/promptflow-ingress/subjoke does not exist"}}
```

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`:
   - I am using the default environment from Azure ML: `1.6.0rc4`
 - Operating System: 
   - Azure ML Workspace
 - Python Version using `python --version`: 
   - `3.9.16`

**Additional context**
The sample code can be found here:
[test-load-flow.zip](https://github.com/microsoft/promptflow/files/14465236/test-load-flow.zip)

**Comment by D-W-** [comment]
Hi @khchan, we don't support sub-flows and the promptflow package is designed to use in user's local machine instead of running in the cloud. `load_flow` has an assumption that all flow's connection should exist in user's local machine. But when executes in the cloud, those connections are not stored in the runtime machine. Which lead to the error above.

Here's a work around for your case: make connection a input and directly call built-in tool with that object.
Here's sample code:

```python
from promptflow import load_flow, tool
from promptflow.connections import AzureOpenAIConnection

from jinja2 import Template
from promptflow.tools.aoai import chat

# The inputs section will change based on the arguments of the tool function, after you save the code
# Adding type to arguments and return value will help the system show the types properly
# Please update the function name/signature per need

# In Python tool you can do things like calling external services or
# pre/post processing of data, pretty much anything you want


@tool
def echo(input: str, my_connection: AzureOpenAIConnection) -> str:
    # subjoke = load_flow("./subjoke")
    # print(subjoke.context)
    # print(subjoke.context.connections)
    # subjoke_output = subjoke(topic=input, connection=my_connection)

    # instead of load sub flow as a flow, directly call tools here
    # load prompt
    with open("subjoke/joke.jinja2", "r", encoding="utf-8") as f:
        tmpl = Template(f.read(), trim_blocks=True, keep_trailing_newline=True)
        prompt = tmpl.render(topic=input)
    
    # directly call tool function with connection object
    output = chat(
        connection=my_connection,
        prompt=prompt,
        deployment_name="gpt-35-turbo",
        max_tokens=256,
        temperature=0.7,
    )
    return output
```
 
![image](https://github.com/microsoft/promptflow/assets/7776147/0e2da85d-c5a0-468d-838f-822121fe105c)
