### ISSUE TITLE
[BUG] DECENT DOCUMENTATIONS

### ISSUE THREAD

**Issue by Porkechebure** [microsoft/promptflow#2195]
**Describe the bug**
A clear and concise description of the bug.

BUG:
 You want A clear and concise description of the bug.
I want A clear and concise description of the promptflow and how to deploy it.

I want to add a qdrant connection and there is no way to understand how to configure the azure openay yaml or wherever else put the damn connections

**How To Reproduce the bug**
Use prompt flow,
get stuck with useless docs.
**Expected behavior**
A documentation made for devs that guide you to deploy something that actually works

**Comment by brynn-code** [comment]
Hi @Porkechebure , thanks for reaching us, as the doc https://microsoft.github.io/promptflow/how-to-guides/deploy-a-flow/deploy-using-docker.html#connections mentioned, when build as an image, promptflow will export the connection used in your flow, that azure openai yaml is just an example, your qdrant connection yaml could be find in the build result folder.

To make it work, just config the relevant environment variable when running the image, for example, if you see 
_api_key: ${env:**MY_CONNECTION_API_KEY**}_  in the qdrant connection yaml exported, then run the image with env var set via below command should work:
```
docker run -p 8080:8080 -e MY_CONNECTION_API_KEY=<secret-value> <image>
```

**Comment by Porkechebure** [comment]
Those docs sucks and the docs are uncomplete.

It's the same as here:
https://github.com/microsoft/chat-copilot/issues/880

You build stuff and put up a superficial quick documentation. It doesn't work like this
