### ISSUE TITLE
Need http/https/socks proxy to requests openai API

### ISSUE THREAD

**Issue by joshua-xia** [microsoft/promptflow#2239]
**Is your feature request related to a problem? Please describe.**
can NOT connect to openai from some location

**Describe the solution you'd like**
provide http/https/socks proxy  setting and connect via proxy server

**Comment by D-W-** [comment]
Hi @joshua-xia , if you have a proxy server, you can configure the server address as your connection's base url:
![image](https://github.com/microsoft/promptflow/assets/7776147/55c5d74f-0c06-4b12-a93e-bddd151897f6)

**Comment by D-W-** [comment]
Also, since openai used HTTPX to make requests, configuring proxy in environment variable is also supported: https://www.python-httpx.org/environment_variables/

**Comment by joshua-xia** [comment]
> Also, since openai used HTTPX to make requests, configuring proxy in environment variable is also supported: https://www.python-httpx.org/environment_variables/

I tested the solution:
1. pip install httpx[socks]
2. set env HTTP_PROXY and HTTPS_PROXY = socks5://proxy_server:port
3. pf flow test --flow ./my_chatbot --interactive

It works, and base_url in yaml file is unnecessary.

Thanks, and I close this issue
