### ISSUE TITLE
[Feature Request] Support directly specifying the input data of a flow in Web UI for batch run instead of specifying it through an additional evaluate flow.

### ISSUE THREAD

**Issue by CodeFree-xzk** [microsoft/promptflow#2241]
**Is your feature request related to a problem? Please describe.**
When we click run in Web UI, we can't specify the input data such as a .jsonl file for batch run. Normally, if we want to specify the input data for a flow in Web UI, we need to click evaluate and then select the data, but this will create an additional evaluate flow. Is there any way to directly specify the input data of the flow and run the flow?

**Describe the solution you'd like**
When we click run, we can directly select the input data instead of specifying it through an additional evaluate flow.

**Describe alternatives you've considered**

**Additional context**

**Comment by D-W-** [comment]
Hi @CodeFree-xzk , you can also create a batch run without evaluation, the evaluation tab is optional:
![image](https://github.com/microsoft/promptflow/assets/7776147/9bbe499b-4219-4c8e-bfa5-b38a337c284b)

Also, for Studio UI issue, please refer to [Frequency asked questions (FAQ) — Prompt flow documentation](https://microsoft.github.io/promptflow/cloud/azureai/faq.html) and create feedback on azure portal, thanks!
