### ISSUE TITLE
[Feature Request] Get the input count and the success/fail count of a node in a batch run by python code

### ISSUE THREAD

**Issue by CodeFree-xzk** [microsoft/promptflow#2272]
**Is your feature request related to a problem? Please describe.**
We found that in the dashboard view of the jobs page we can see the completed/failed count of each node and the line, However, we want to calculate the success rate of a node or the line. So we may need to get the counts by python code.  Is there any methods that we can get the get the counts by python code?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhengfeiwang** [comment]
hi @CodeFree-xzk , thanks for your feedback! currently, we have not exposed such API to get the node or line level information; but these informations are already stored locally, so it's possible to collect them from the disk - let me briefly introduce that:

1. for each run, you can get its output path from run object; by default, it's a path under `~/.promptflow/.runs`, named with its run name, and you can get its precise value via  CLI command `pf run show --name <run>`

![image](https://github.com/microsoft/promptflow/assets/38847871/34430cf3-7496-4df4-9347-235c2b279d51)

2. navigate to that folder, there will be two folders `node_artifacts` and `flow_artifacts`, which contains the informations about nodes and lines. there are same numbers of JSON files as the lines, each one corresponds to a line, and you can get what you expect (status, output and something else) from those files.
3. then it's your turn to collect what you need and transform them with your magic!


besides, we are working on some new features related to line level metrics with telemetry, which will expose some APIs to retrieve something related to your ask; but I cannot get you a precise timeline for now.

please take a look on the collection from run local storage first, and feel free to let me know if that does not work fine with your case, and I can explain more on what we are doing.
