### ISSUE TITLE
[BUG] Error in View output page

### ISSUE THREAD

**Issue by anandchugh** [microsoft/promptflow#2295]
**Describe the bug**
Create a prompt flow run. 
Open Viewoutput for that run. Error is shown in viewoutput

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1.Create a promptflow run with flow containing one output field
 ```
Status:
    type: string

```
**Expected behavior**
View output page show should the output correctly.

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/3197424/2ba2ca41-4bb2-413a-98b2-3b722c6a7c50)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**
Prompt flow contains Status as one of the output column. But when status is added as one of the output column then error occurs

**Comment by brynn-code** [comment]
I've assign to expert responsible for promptflow in Azure workspace. Besides, github issue mostly track the open source version promptflow, for things related to promptflow in Azure workspace, refer to this [guide](https://microsoft.github.io/promptflow/cloud/azureai/faq.html#how-to-create-feedback-for-azure-portal-experience) to open the OCV(one customer voice) specific for azure.

**Comment by brynn-code** [comment]
Just confirmed with our teammates, we'd like you convert the issue to ocv, as we are able to get some workspace information from the ocv, which is important for log querying and not proper to share through github.

**Comment by jieqiu0129** [comment]
The issue has been fixed and is in the process of deployment. You can retry it after one week.
