### ISSUE TITLE
Fix docs cli example to give the promised run details table output

### ISSUE THREAD

**Issue by bobbyo** [microsoft/promptflow#2299]
**Is your contribution request related to a problem? Please describe.**
The current docs give a CLI example that does not work, because it uses the wrong command.
The linked PR fixes the docs with the correct command.

**Detail the functionality and value.**
Users following the promptflow docs will be frustrated because the example does not give the promised output.

**Additional context**
A quick-fix added while I was using the docs.

PR: https://github.com/microsoft/promptflow/pull/2298

**Comment by wangchao1230** [comment]
Thanks for reporting and send the Pull requests ! Let me close this item.
