### ISSUE TITLE
[BUG] EvaluationRun Failed

### ISSUE THREAD

**Issue by Kevinlee49** [microsoft/promptflow#2300]
I got an error during the EvaluationRun phase. The FlowRun job preceding this step completed successfully. However, I received the following error message during the EvaluationRun: "**_UserError: Tool load failed in 'relevance_score': (ConnectionNotFound) Connection '' not found, available connection keys dict_keys([])._**" As a result, the outputs were generated using input mapping with multiple inputs. Unfortunately, the output does not include the relevance_score. You can check the screenshot that question, context, answer, and gpt_relevance are not defined. Do you have any insights into what might be causing this problem?

<img width="868" alt="2024-03-11_16-19-36" src="https://github.com/microsoft/promptflow/assets/86863395/2dcbb8c2-d3dd-404c-9f71-6cabeb84ef59">
<img width="387" alt="Snag_16738e0" src="https://github.com/microsoft/promptflow/assets/86863395/62d305f6-4238-499a-9abe-510c82bc9fd5">
<img width="387" alt="Snag_1686d39" src="https://github.com/microsoft/promptflow/assets/86863395/8fd4c27f-31aa-4884-a7c9-8a7bcaa0e182">

![image](https://github.com/microsoft/promptflow/assets/86863395/604dea2b-dc91-4a43-8c22-ab39fadc061c)

**Comment by brynn-code** [comment]
Hi @Kevinlee49 , for this issue, we may need more information about your flow, and as mention before, we encourage user open OCV(one customer voice) for promptflow in Azure portal, please follow this [guide](https://microsoft.github.io/promptflow/cloud/azureai/faq.html#how-to-create-feedback-for-azure-portal-experience) to re-create the problem you met, thanks. (If you are a microsoft internal user, you could also use StackOverflow internal version directly.)

**Comment by Kevinlee49** [comment]
@brynn-code Thank you for reply, I already left some reports 2-3 weeks ago in OCV for prompt flow in Azure portal. However, no one replied my problems until now. That's why I keep leaving issues here.

**Comment by brynn-code** [comment]
Just confirmed with our teammates, they will investigate this UI issue #2297 . And for this one we may need a new ocv, as ocv will give the workspace information which is import for log querying and not proper to share through github, I'm sure the ocv should triage to our team directly instead of our partner team, I'll keep this one open until your new ocv got replied and tracked.

**Comment by Kevinlee49** [comment]
@brynn-code I just created three more OCV, hopefully they will contact me about these issues in this time :)

**Comment by brynn-code** [comment]
Don't worry, I'll keep an eye on this issue to keep contact with you until the ocv got tracked.

**Comment by brynn-code** [comment]
@Kevinlee49  I'll close this issue if you don't mind, I've seen the ocv you opened be triaged to our team member yesterday, their fix is under release, our PM will contact you once the fix released to all region.
