### ISSUE TITLE
[BUG] Link broken to prompt template documentation when running LLM node with incorrect prompt template

### ISSUE THREAD

**Issue by corticalstack** [microsoft/promptflow#2308]
**Describe the bug**
- A prompt flow with LLM nodes is defined.
- The prompt flow is then run in test mode within VSCode locally.
- The prompt definition itself does not use the expected prompt template format, i.e. 'system:\n','user:\n','assistant:\n','function:\n'
- The error message states "The Chat API requires a specific format for prompt definition, and the prompt should include separate lines as role delimiters: 'system:\n','user:\n','assistant:\n','function:\n'......." and includes a link to the prompt template documentation. 
- The link is broken.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Run a flow with an LLM node in chat mode with an incorrect prompt template format.

**Comment by brynn-code** [comment]
Thank you for the feed back. We will update the https://aka.ms/pfdoc/chat-prompt .

**Comment by chjinche** [comment]
hi @corticalstack this link has been fixed, please have a try. Thanks for reporting this.
