### ISSUE TITLE
[Feature Request] Support for using AML datastore uri for Image fields with GPT4V model

### ISSUE THREAD

**Issue by anandchugh** [microsoft/promptflow#2317]
**Is your feature request related to a problem? Please describe.**
We are using prompt flow to get attributes of images. Some of the images are quite big and before sending prompt with image data to LLM step we want to resize images. 
There are two possibilites
1) We can resize image on the fly
2) Process all images before, resize them , store them in aml data store . Use the aml data store uri in the LLM  step.

Currently using aml data store uri is not supported in the Image field.

**Describe the solution you'd like**
We would like to use the aml data store uri as an input to the image field.

**Describe alternatives you've considered**
As an alternative we are doing resizing as preprocessing step and then passing resized image to LLM step. But this resizing occurs every time when we run experiment and it adds to the overall runtime of experiment.

**Additional context**

**Comment by guming-learning** [comment]
Hi @anandchugh , thanks for reaching us. Your request is specifically for **batch run** on Azure right? I don't see that explicitly pointed out in the issue :)
