### ISSUE TITLE
[BUG] `pip install git+https://github.com/promptflow/src/promptflow` doesn't work starting from today

### ISSUE THREAD

**Issue by WeichenXu123** [microsoft/promptflow#2328]
**Describe the bug**
`pip install git+https://github.com/promptflow/src/promptflow` doesn't work starting from today

**How To Reproduce the bug**
OS: Ubuntu 18.04.6 LTS
Python 3.9,
Run the following command:
```
pip install git+https://github.com/promptflow/src/promptflow
```
Error occurs:
```
Collecting git+https://github.com/promptflow/src/promptflow
  Cloning https://github.com/promptflow/src/promptflow to /tmp/pip-req-build-cjsxzz18
  Running command git clone --filter=blob:none --quiet https://github.com/promptflow/src/promptflow /tmp/pip-req-build-cjsxzz18
  remote: Not Found
  fatal: repository 'https://github.com/promptflow/src/promptflow/' not found
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/promptflow/src/promptflow /tmp/pip-req-build-cjsxzz18 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/promptflow/src/promptflow /tmp/pip-req-build-cjsxzz18 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Expected behavior**
Installation from promptflow github master branch should work.

**Screenshots**
N/A

**Running Information(please complete the following information):**
 - Promptflow Package Version `pip install git+https://github.com/promptflow/src/promptflow`
 - Operating System: Ubuntu 18.04.6 LTS
 - Python Version using 3.9

**Additional context**
MLFlow CI failure link: https://github.com/mlflow-automation/mlflow/actions/runs/8249475031/job/22595381170#step:10:42

**Comment by brynn-code** [comment]
Sorry that I put the wrong dev url, I've add the pr here: https://github.com/mlflow/mlflow/pull/11410  @WeichenXu123

**Comment by brynn-code** [comment]
Close as pr merged, please have another try when you have time!
