### ISSUE TITLE
[BUG] Validate and parse input failed

### ISSUE THREAD

**Issue by kamzz1107** [microsoft/promptflow#2342]
**Describe the bug**
Getting the below error while creating the python tool in Azure prompt flow. The resources are created using Azure AI Studio.
Validate and parse input failed: Generate tool meta failed for python tool. Meta file '.file_name.tmp.py' can not be found.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. add python tool
2. try to validate the python tool

**Expected behavior**
Ideally the tool should be validated.

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906] using Azure portal
 - Operating System: Windows 11

**Comment by brynn-code** [comment]
Hi @kamzz1107 , seems you are using a reeeeally old version of runtime, is it possible for you to have another try with a newer runtime? The promptflow version in recent runtime time should be 1.7.0rcx ...

**Comment by kamzz1107** [comment]
Hi @brynn-code  I am using Automatic runtime (Serverless compute). The runtime seems to be the latest. Is there anyway I can check the runtime version in serverless compute?

**Comment by kamzz1107** [comment]
<img width="415" alt="image" src="https://github.com/microsoft/promptflow/assets/33276290/5db5c2c9-2822-45f0-ab4a-47b8c9203c88">
this is the promptflow version

**Comment by brynn-code** [comment]
Got it, then the promptflow version is 1.7.0.rc2, that's the latest one, we will try to repro the bug you report and get back to you soon.

**Comment by brynn-code** [comment]
Thanks for reaching us, we have reproduce the bug and investigating..

**Comment by brynn-code** [comment]
@kamzz1107 Which region does your ai project locate in? Region is able to see via Azure portal. 
![image](https://github.com/microsoft/promptflow/assets/24237253/1d99cd28-8331-40c3-830a-de4724313aef)

**Comment by brynn-code** [comment]
@kamzz1107 There is a regression from our partner compute team, they have reverted their changes, the mitigation steps are:
- For compute instance runtime, user needs to **DELETE** the compute instance and re-create a new one. (delete, not restart)
- For automatic runtime, user needs to **STOP** the runtime and start a new one. (stop, not reset)
