### ISSUE TITLE
[Feature Request] Update Python version in the Azure ML runtime

### ISSUE THREAD

**Issue by TimCargan** [microsoft/promptflow#2343]
Is it possible to select or update the Python version used in the Azure runtime? The current Azure runtime still uses Python 3.9. Our flows have dependencies that need Python 3.10 or later. While they run locally and in our CI/CD pipeline, running them in an Azure ML workspace would be beneficial.

Creating a custom Docker image independent of azureml/promtflow/promflow-rutime-stable appears infeasible. We've tried updating the Python version within the conda environment defined in the Dockerfile. However, it seems you install a custom PromptFlow runtime, causing freezing and reinstalling all libraries with pip to fail.

**Comment by TimCargan** [comment]
Hi, is this an issue that will not be addressed?

**Comment by hecescam** [comment]
Hi!! I also need to run my flows on Python 3.10 or later. I have tried many ways to create a custom environment to update the Python version but then it is not possible to create the runtime using this custom environment. Do you think it would be possible to give a solution to this problem? It would be really beneficial for me.

**Comment by dazfuller** [comment]
How come this has been closed before any response from the team? We're currently moving a number of components away from 3.9 and could really do with keeping the runtime consistent across services.

Is this something which we can expect to see?

**Comment by ebotiab** [comment]
Hi, any update on this??
