### ISSUE TITLE
[Feature Request] Cannot filter from complete dataset in View output page

### ISSUE THREAD

**Issue by anandchugh** [microsoft/promptflow#2394]
**Is your feature request related to a problem? Please describe.**
View output page doesnot allow to filter from complete dataset. If shows 25 records per page and allows to filter from 25 records only.
There is no way to see the record with failed instances. We have to many browse each page and see any instace failed in those 25 records.
Also, goint to next page takes a lot of time. If I have dataset of 10000 records then it may take lot of time to see the error records.

**Describe the solution you'd like**
Filter and sorting funcitonality should work on complete dataset rather than per page(25 recods)

**Describe alternatives you've considered**
We can download manyally and find the record number of failed instance but to see the trace for the failed instance there is no other option other than going to the page in View output

**Additional context**

**Comment by 0mza987** [comment]
Hi @anandchugh ,

Just to confirm, is your feedback related to azure portal experience? If that's the case, please check this link and create feedback there [Frequency asked questions (FAQ) — Prompt flow documentation](https://microsoft.github.io/promptflow/cloud/azureai/faq.html#how-to-create-feedback-for-azure-portal-experience)

Github issue mainly focus on non-portal user experience issue.
