### ISSUE TITLE
[Feature Request] Have "pf flow build` command accept custom commands to be added to the generated Dockerfile for the flow

### ISSUE THREAD

**Issue by chenmliu** [microsoft/promptflow#2438]
**Is your feature request related to a problem? Please describe.**

In my current customer engagement, I have a use case for adding custom commands (to mount a secret and add one more `pip install` in the Dockerfile generated by the `pf flow build` command. Basically, I need to change the following generated command in the Docker file:

```
RUN conda create -n promptflow-serve python=3.9.16 pip=23.0.1 -q -y && \
    conda run -n promptflow-serve \
    pip install -r /flow/requirements.txt && \
    conda run -n promptflow-serve pip install keyrings.alt && \
    conda run -n promptflow-serve pip install gunicorn==20.1.0 && \

    conda run -n promptflow-serve pip cache purge && \
    conda clean -a -y
```

to have these new steps:

| Step | Command |
| --- | --- |
| Mount a secret | `--mount=type=secret,id=gitlabpat GITLAB_PAT=$(cat /run/secrets/gitlabpat)` |
| pip install a package from a private GitLab repo | `pip install ffmodeltestbed --extra-index-url https://__token__:${GITLAB_PAT}@$gitlab_repo` |

So the line will become the following:

```
ARG gitlab_repo

RUN --mount=type=secret,id=gitlabpat \
    GITLAB_PAT=$(cat /run/secrets/gitlabpat) && \
    conda create -n promptflow-serve python=3.9.16 pip=23.0.1 -q -y && \
    conda run -n promptflow-serve \
    pip install -r /flow/requirements.txt && \
    conda run -n promptflow-serve pip install keyrings.alt && \
    conda run -n promptflow-serve pip install gunicorn==20.1.0 && \
    conda run -n promptflow-serve pip install ffmodeltestbed --extra-index-url https://__token__:${GITLAB_PAT}@$gitlab_repo && \
    conda run -n promptflow-serve pip cache purge && \
    conda clean -a -y
```

I was hoping that `pf flow build` command accepts some argument for passing in my custom commands, but wasn't able to find anything relevant by running `pf flow build --help`.

My current workaround is to either overwrite the generated Dockerfile or insert my custom commands.

**Describe the solution you'd like**

Would be great if `pf flow build` command provides a way to pass in custom commands to be added to the Dockerfile, even better if I can specify where in the Dockerfile to insert my commands, so the commands will be executed in the desired order.

**Describe alternatives you've considered**

Post-generation edit - Provide a way to easily edit the generated Docker file. Something cleaner than using bash commands like `cp -f` to overwrite the file or locating the lines to insert the commands.

**Comment by elliotzh** [comment]
Hi @chenmliu, thank you for the feature request!

We have ever considered this feature but doesn't have a plan to support it by providing parameters in `pf flow build` for now.

1. As you have already pointed out, we have generated a Dockerfile, which you can do any updates you want based on.
2. for the update you have mentioned:
    1. you can add custom dependent packages with below attribute in yaml, and `pf flow build` will pick them automatically: [doc](https://microsoft.github.io/promptflow/cloud/azureai/quick-start/create-run-with-automatic-runtime.html?highlight=python_requirements_txt#specify-pip-requirements-for-automatic-runtime)
```yaml
environment:
  python_requirements_txt: requirements.txt
```
    2. for secret management, I personally have ever tried to use Docker secrets to manage them without updating `Dockerfile` so that I can avoid dump the secret to host disk: [doc](https://docs.docker.com/engine/swarm/secrets/)

**Comment by chenmliu** [comment]
Thank you for the reply, @elliotzh 

Just to clarify, for 2ii ("I personally have ever tried to use Docker secrets to manage them without updating `Dockerfile`") - did you mean updating the Dockerfile is always required for using secrets?

**Comment by elliotzh** [comment]
Sorry, I have misunderstood some of your requirements.
1. you have already mounted secrets to `/run/secrets/gitlabpat` but need to refer it in a `pip install` command;
2. updating `requirements.txt` doesn't meet your requirement as secret has not been exported to a variable when installing `requirements.txt`;
3. actually you may hope that you can custom the **prefix** of `pip install requirements.txt`, like your example:
```docker
RUN --mount=type=secret,id=gitlabpat \
    GITLAB_PAT=$(cat /run/secrets/gitlabpat) && \
    conda create -n my_env python=3.9.16 pip=23.0.1 -q -y && \
    pip install -r /flow/requirements.txt
```
instead of 
```docker
RUN conda create -n my_env python=3.9.16 pip=23.0.1 -q -y && \
   pip install -r /flow/requirements.txt
```

Sorry, this is kind of out of our scope. The recommended workaround is to update the built docker file.

**Comment by chenmliu** [comment]
Thank you for clarifying and confirming, @elliotzh :)
