### ISSUE TITLE
[Feature Request] pf autocomplete

### ISSUE THREAD

**Issue by sashokbg** [microsoft/promptflow#2446]
**Is your feature request related to a problem? Please describe.**

When working with the pf cli it would be very useful to have sh autocompletion

Please excuse me if I missed it in the documentation, but when searching I could not find any auto complete.

**Comment by wangchao1230** [comment]
Thanks for the feeback, @sashokbg !

We don't have sh autocompletion support yet. We will track this as a new feature request.

**Comment by sashokbg** [comment]
Hello, @wangchao1230 I would like to give it a go. Do you have any examples of python autocomplete that I can use ?
Maybe we can base it on the one in aws cli: https://github.com/aws/aws-cli/blob/develop/awscli/completer.py ?

**Comment by sashokbg** [comment]
Or maybe we can use this lib to generate auto completions based on argparse ?
https://github.com/kislyuk/argcomplete

**Comment by wangchao1230** [comment]
Hello @sashokbg, thanks for the suggestion on solution! 
I would prefer the argcomplete one, like how [azure-cli](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/az.completion.sh) does this.


If you are interested, feel free to submit a PR to us. 
Our bandwith is already booked for previous planned items, and may take some time to pick this up from our side.
Thanks!
