### ISSUE TITLE
[BUG] [VSCode Extension] when running an individual node and using dictionary elements as a node input leads to error 'not able to access the property'

### ISSUE THREAD

**Issue by HosseinHeris** [microsoft/promptflow#2472]
**Describe the bug**
A clear and concise description of the bug.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:

1. Create a python node with its output as dictionary 
2. Access the elements of the dictionary as an input to other nodes. 
3.  Run the complete flow (this works)
4. Now try running the individual node with an input referencing the dictionary.  Prompt flow will give error. The frequency is always. 
Example error: "Flow test failed with InvalidReferenceProperty: Flow execution failed. Invalid property 'topK' when accessing the node 'ConfigLoader'. Please check the property and try again."

For example I created a config loader node, which loads configuration as dictionary. 
![image](https://github.com/microsoft/promptflow/assets/47231097/f6acffa1-1aae-416a-a4c4-1dbd30c78117)

In other nodes, I am accessing the elements as ConfigLoader.output.specificelement

<img width="635" alt="image" src="https://github.com/microsoft/promptflow/assets/47231097/f993c603-e5aa-45c6-a99f-7600a624cbc0">

As mentioned, the whole flow runs but when running this individual node, the following error appears:
'Flow test failed with InvalidReferenceProperty: Flow execution failed. Invalid property 'topK' when accessing the node 'ConfigLoader'. Please check the property and try again.'

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
<img width="1049" alt="image" src="https://github.com/microsoft/promptflow/assets/47231097/6bb84443-6d5c-4849-b90b-06afb7b008fe">

6. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: **1.2.0**
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]: **windows 11**
 - Python Version using `python --version`: [e.g. python==3.10.12] **3.9.18**
 - VS Code version. **1.86.1**
 - Prompt Flow extension version. **1.1.4.0**
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by lalala123123** [comment]
Hi @HosseinHeris , this issue has been fixed in the latest version of promptflow and can be updated to promptflow==1.7.0 and try again.
