### ISSUE TITLE
Add Support for gpt-4-0125-preview

### ISSUE THREAD

**Issue by iceman3000** [microsoft/promptflow#2494]
**Is your feature request related to a problem? Please describe.**
Latest OpenAI model under the "gpt-4-turbo-preview" alias is not available to be used

**Describe the solution you'd like**
Add the gpt-4-turbo-preview alias so that promptflow can always point to the latest gpt4 turbo model. Otherwise, add the gpt-4-0125-preview for specific selection.

**Describe alternatives you've considered**
Use a custom python node and make the OpenAI call myself.

**Additional context**
None - I'm curious why this option hasn't been added yet given this model has been out for months?

**Comment by D-W-** [comment]
Hi @iceman3000 , could you describe more where do you want to add "gpt-4-turbo-preview" alias? For built-in node, I think you can specify it in YAML like this:
![image](https://github.com/microsoft/promptflow/assets/7776147/a8b5461d-3af4-491e-a0a7-4895bdbd429a)

**Comment by naiyunzhang** [comment]
We will allow input model name manually the dag editor. You can set any model name in the flow.dag.yaml file you want as a workaround for now.

**Comment by naiyunzhang** [comment]
You can input any model name in the `model` input box now
