### ISSUE TITLE
[Feature Request] Make tokens_per_message part of a configuration file

### ISSUE THREAD

**Issue by shuther** [microsoft/promptflow#2508]
**Is your feature request related to a problem? Please describe.**
While experimenting with mistral, I am facing the error: 

> Failed to calculate metrics due to exception: cannot access local variable 'tokens_per_message' where it is not associated with a value.

**Describe the solution you'd like**
tokens_per_message is set by the model name in the [util.py](examples/flows/standard/autonomous-agent/util.py)
The proposition is to overwrite/set it in the flow.day.yaml under the _inputs_ section
This will also help when experimenting with new openAI models

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by YingChen1996** [comment]
Hi, @shuther, thank you for reaching out to us. We will use an internal task to track sample improvement.

**Comment by YingChen1996** [comment]
The pr has merged and we have set tokens_per_message  as flow input
