### ISSUE TITLE
[BUG] Failed to serialize inputs - VScode extension (warning)

### ISSUE THREAD

**Issue by shuther** [microsoft/promptflow#2509]
**Describe the bug**
Each time I click on _Inputs_ or _outputs_ of the flow, I am getting the warning message below. is it expected?

> 2024-03-26 19:19:01 +0100   97541 execution.flow     WARNING  Failed to serialize inputs or output for flow run because of cannot pickle 'generator' object.The inputs and output field in api_calls will be None.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Fresh install
2. Create a new chat flow.
3. Open the flow.dag.yaml in the visual mode
4. click on the inputs box

**Expected behavior**
no warning

**Screenshots**
<img width="906" alt="Screenshot 2024-03-27 at 10 58 02" src="https://github.com/microsoft/promptflow/assets/33225407/dec82176-6e16-4a56-88fa-d0b87e9fc3c9">
[flow.dag.yaml.txt](https://github.com/microsoft/promptflow/files/14771435/flow.dag.yaml.txt)

**Running Information(please complete the following information):**
promptflow                       1.7.0
Executable '/opt/homebrew/opt/python@3.11/bin/python3.11'
Python (Darwin) 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)]

**Comment by D-W-** [comment]
Hi @shuther , could you provide screenshot for error message above? Did you trigger flow test for above flow? Seems the flow's not valid (OpenAI connection does not have mistral model, see the red box above).
