### ISSUE TITLE
[BUG] Fail to install dev branch

### ISSUE THREAD

**Issue by serena-ruan** [microsoft/promptflow#2589]
**Describe the bug**
A clear and concise description of the bug.
Hey friends, it seems the installation process https://github.com/mlflow-automation/mlflow/actions/runs/8498480507/job/23280874139#step:8:82 fails due to package conflicts. The error message is a little bit weird, but could you fix it in MLflow or in your repo?

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1.pip install git+https://github.com/microsoft/promptflow#subdirectory=src/promptflow

**Expected behavior**

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

**Comment by serena-ruan** [comment]
cc @brynn-code

**Comment by brynn-code** [comment]
Hey @serena-ruan, we are working on package splitting these days, we need some changes to ensure mlflow installed promptflow dev version correctly, I'll create the PR asap, thanks for the reaching out! ❤️❤️
