### ISSUE TITLE
[BUG] Ensuring system metrics is not none before checking length (Trace collector)

### ISSUE THREAD

**Issue by kevin-m-kent** [microsoft/promptflow#2644]
**Describe the bug**
I have found in testing with promptflow 1.7.0 that this trace collector will fail if the node run level system metrics are none (object of type 'NoneType' has no len()). This change will ensure it is not none before checking length (just like run.api_calls on line 265). 

I propose changing this line - https://github.com/microsoft/promptflow/blob/main/src/promptflow-core/promptflow/core/_serving/monitor/metrics.py#L216

From
```
               if len(run.system_metrics) > 0:

```
To
```

                if run.system_metrics and len(run.system_metrics) > 0:
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Add trace collector ENV variable (in this case I was using APPLICATIONINSIGHTS_CONNECTION_STRING
2. Run application, invoke promptflow
3. Observe error in logs: "failed to record metrics: object of type 'NoneType' has no len()"

**Expected behavior**
Able to collect metrics even when nodes have no system metrics recorded.

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.7.0
 - Operating System: macOS 14.4.1 (23E224)
 - Python Version using `python --version`: 3.11

**Additional context**
I am happy to make a PR to fix this, I have already made the change on my forked branch, just need to add tests.

**Comment by brynn-code** [comment]
@kevin-m-kent Thanks for the reach out about the bug, really appreciate it, please go ahead to open the pr :) 
+ @wxpjimmy for awareness.

**Comment by kevin-m-kent** [comment]
Hi - created PR here. https://github.com/microsoft/promptflow/pull/2785

I had some trouble running these tests locally, I just couldn't get pytest to run properly - it seemed there were a bunch of dependencies that need to be added to run these tests, couldn't get it to work after fiddling with poetry for a while. Is there a best practice or documentation around running these tests locally? Thank you.
