### ISSUE TITLE
List index out of range error on Open Model LLM Node 

### ISSUE THREAD

**Issue by jessegoraya** [microsoft/promptflow#2654]
When adding an Open Model LLM node in a Prompt Flow I get an error when trying to connect to my managed service (i.e. Pay as you Go) deployed Llama.  

The issue is shown in the below screenshot where you can see both the error as well as the LLama2a connection that is showing up under Connections and was setup on Azure AI Studio.  I have gotten this time a number of times including doing a full install and reinstall of promptflow as well as creating a new virtual environment.

![Open Model LLM Node Error](https://github.com/microsoft/promptflow/assets/27831702/53bf26ee-1eba-446b-8af8-49dab846ee81)

I am using PromptFlow version 1.6.0 and Python 3.11.8.

Does anyone have any ideas on how I can resolve this issue?

**Comment by brynn-code** [comment]
cc @dans-msft and @Adarsh-Ramanathan , could you please help on the open model llm issue? Thanks!

**Comment by jessegoraya** [comment]
Thank you all.  I was able to resolve the issue.  I fixed this by removing my connections that were build in my Azure Workspace.  Then I created custom connections and after a few tries this worked for creating my connection.

$schema: https://azuremlschemas.azureedge.net/promptflow/latest/CustomConnection.schema.json
name: "LLama_Service"
type: custom
configs:
key1: "test1"
endpoint_url: "<LlamaURL>"
model_family: "LLAMA"
secrets:
# Use'<no-change>' to keep original value or '<user-input>' to update it when the application runs.
key2: "<no-change>"
endpoint_api_key: "<no-change>"
