### ISSUE TITLE
[Feature Request] Support setting dimensions in embedding tool.

### ISSUE THREAD

**Issue by wenwei-lin** [microsoft/promptflow#2656]
**Is your feature request related to a problem? Please describe.**
OpenAI supports dimensions parameter since text-embedding-3. But the embedding tool doesn't support now.

**Describe the solution you'd like**
Add a dimensions parameter in embedding tool's input.

**Comment by chjinche** [comment]
Hi @wenwei-lin thanks for the issue and your contribution!

Noticed in [official doc that "dimensions" is only supported in text-embedding-3 and later models](https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-dimensions). How do you plan to handle models before 'text-embedding-3' like 'ada-002'? Have you tested if they can work with the new parameter?

BTW, please add some unit tests in your PR to make sure the change works as expected and will not cause regression to existing users.

**Comment by wenwei-lin** [comment]
@chjinche Is there any way to get the model type for Azure OpenAI deployments? Can I use model_list property?

**Comment by chjinche** [comment]
`model_list` is a deprecated contract, it is `capabilities`->"embedding:true" contract that really works. The latter contract can support custom fine tuned model in azure.

**Comment by wenwei-lin** [comment]
@chjinche A little complicated 😂
