### ISSUE TITLE
[Feature Request]Support for tool_calls

### ISSUE THREAD

**Issue by M-Hietala** [microsoft/promptflow#2741]
**Is your feature request related to a problem? Please describe.**
Promptflow is only supporting deprecated function calls: https://github.com/openai/openai-python/blob/0cbce3f6777fd8f137ed7445e9bc2f2aa5c9f5b4/src/openai/resources/chat/completions.py#L322C1-L322C53

**Describe the solution you'd like**
Add support for tool_call and using functions in that context

Here is a link to the code that adds the deprecated function info to the chat completion API call parameters:
https://github.com/microsoft/promptflow/blob/dfbdee0ccecdee3381930e114a5aa84c9586c3e1/src/promptflow-tools/promptflow/tools/aoai.py#L137

Also, this sample requires updating to handle the tool_calls:
https://github.com/microsoft/promptflow/blob/dfbdee0ccecdee3381930e114a5aa84c9586c3e1/examples/flows/chat/use_functions_with_chat_models/run_function.py#L29

**Describe alternatives you've considered**

**Additional context**

**Comment by chjinche** [comment]
Hi @M-Hietala "tools"/"tool_choice" support are under testing, and hopefully may ship in a few weeks. We will let you know when it is available to have a try!
