### ISSUE TITLE
No versions of azure-cli is compatible with promptflow 1.8.0 with azure 

### ISSUE THREAD

**Issue by ZhiliangWu** [microsoft/promptflow#2807]
**Describe the bug**
When installing `promptflow[azure]` with `azure-cli`, it is incompatible. 

```console
Because no versions of azure-cli match >2.59.0,<3.0.0
 and azure-cli (2.59.0) depends on azure-cosmos (>=3.0.2,<4.0), azure-cli (>=2.59.0,<3.0.0) requires azure-cosmos (>=3.0.2,<4.0).
And because promptflow-azure (1.8.0) depends on azure-cosmos (>=4.5.1,<5.0.0), azure-cli (>=2.59.0,<3.0.0) is incompatible with promptflow-azure (1.8.0).
And because promptflow[azure] (1.8.0) depends on promptflow-azure (1.8.0)
 and no versions of promptflow match >1.8.0,<2.0.0, azure-cli (>=2.59.0,<3.0.0) is incompatible with promptflow[azure] (>=1.8.0,<2.0.0).
So, because aml-ppt depends on both promptflow[azure] (^1.8.0) and azure-cli (^2.59.0), version solving failed.
```

As highlighted in the error message, the main issue is the dependency of azure-cosmos

**promptflow-azure (1.8.0) depends on azure-cosmos (>=4.5.1,<5.0.0)** and **azure-cli (2.59.0) depends on azure-cosmos (>=3.0.2,<4.0)**

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a new project using `poetry` with `poetry new aml-promptflow`.
2. Install and activate the virtual environment with `poetry install` followed by `poetry shell`.
3. Install `promptflow` with`azure` extras using `poetry add promptflow --extras azure`
4. Install the `azure-cli` using `poetry add azure-cli`.

**Expected behavior**
`promptflow[azure]` should be compatible with `azure-cli`

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.8.0
 - Operating System: MacOS14.4.1
 - Python Version using `python --version`: 3.9.1

**Additional context**

**Comment by ZhiliangWu** [comment]
https://github.com/Azure/azure-cli/issues/28731

**Comment by huaiyan** [comment]
Thanks @ZhiliangWu, will have a try about using same version with azure-cli.

**Comment by huaiyan** [comment]
Thanks @ZhiliangWu. `azure-cosmos` released 4.0.0 in `May 21, 2020`, which is a rather old version.
It's may not a very common practice to do backward compatibility for such old version.

**Comment by huaiyan** [comment]
Thanks @ZhiliangWu, we will have a look about it.
But basically, `azure-cosmos` released `4.0.0` in 2020, it's not a common practice to do backward compatibility support for such old version.

**Comment by huaiyan** [comment]
Hello @ZhiliangWu, there is one workaround for your situation.
You may install `azure-cli` by `pipx install azure-cli`.
Then you don't need to add it in your poetry environment but also could use `az` commands in it.

Basically, pipx installs applications in an isolated environment and makes them globally available.
You may find more details here:
https://github.com/pypa/pipx#how-is-it-different-from-pip

**Comment by ZhiliangWu** [comment]
@huaiyan Yes, that's a possible workaround if there is really no plan to update `azure-cli` being compatible with `promptflow`.  The disadvantage is that we have to manually pinning the `azure-cli` version through `pipx` commands instead of managed and resolved by `azure-cli` centrally.
