### ISSUE TITLE
[Feature Request] Enhance Testing with Serverless Computing Options

### ISSUE THREAD

**Issue by nakai-aq** [microsoft/promptflow#2817]
Currently, it seems we have two options for running test instances: using a custom computing instance or utilizing the automated runtime (preview). 
It would be greatly beneficial if we could also have the option to use serverless computing solutions, such as Azure Functions, for this purpose. 

This addition could enhance flexibility and efficiency in testing environments. 
Please consider this feature request. Thank you for your attention to this matter.

**Comment by D-W-** [comment]
Hi @nakai-aq , could you post the request in [azure portal](https://microsoft.github.io/promptflow/cloud/azureai/faq.html#how-to-create-feedback-for-azure-portal-experience)? We'll only track local SDK/CLI/Extension issue here in GitHub. Thanks!
