### ISSUE TITLE
[BUG] [VSCode Extension] VectorDB Index Lookup doesn't take the config.json variables into consideration

### ISSUE THREAD

**Issue by pgr-lopes** [microsoft/promptflow#2876]
**Describe the bug**
Vector DB index configuration is not taking into account the config.json values, you need to setup the subscription ID, AML resource name and resource group through az cli.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create an empty flow or a flow from a template
2. Configure the config.json file with the subscription id, workspace name and resource group name
3. Do `pip install promptflow-vectordb`
4. Add the Index Lookup activity to the canvas
5. Try to change the values of the _mlindex_content_ field and you will get:

![image](https://github.com/microsoft/promptflow/assets/94919141/41c65852-0655-49c0-9e31-6a014bdce6a8)

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.

<img width="860" alt="image" src="https://github.com/microsoft/promptflow/assets/94919141/a1e8d21d-ec09-445f-943d-648593edbbd3">

6. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: 1.9.0
 - Operating System: Windows 11
 - Python Version using `python --version`: 3.11.0
 - VS Code version: 1.88.1
 - Prompt Flow extension version: 1.16.1
 - Error: "Error when calling function promptflow_vectordb.tool.common_index_lookup_utils.reverse_mapping: tool_ui_callback. <locals>.wrapped() missing 3 required positional arguments: 'subscription_id', 'resource_group_name', and 'workspace_name". Please contact the tool author/support team for troubleshooting assistance."
 
**Additional context**
N/A

**Comment by pgr-lopes** [comment]
Adding the variables through cli manually works:
```
az login
az account set --subscription <subscription_id>
az configure --defaults group=<resource_group_name> workspace=<workspace_name>
```

However, after I do this, I get another error with the azure default credential which is not specified:

<img width="518" alt="image" src="https://github.com/microsoft/promptflow/assets/94919141/137957c7-4196-4c05-9676-17850c3c8bfc">

**Comment by D-W-** [comment]
Hi @dans-msft , @Adarsh-Ramanathan , could you help to take a look? Thanks!

**Comment by Adarsh-Ramanathan** [comment]
@pgr-lopes, for this error: `However, after I do this, I get another error with the azure default credential which is not specified:`, can you share the error message and a stack trace?

@D-W-, the issue in the main thread isn't an Index Lookup issue; it is that subscriptions/resourcegroups/workspaces configured in config.json are not taken into account by the runtime when invoking a dynamic list callback.
Assigning to @DaweiCai to take a look.

**Comment by pgr-lopes** [comment]
Sorry Adarsh, I missed this. The credential ended up being a problem with my system and the way the azcli communicates with the AD, it's not related to promptflow.
