### ISSUE TITLE
[Feature Request] Support for recently available Azure OpenAI embedding models & dimensions

### ISSUE THREAD

**Issue by lok-msft** [microsoft/promptflow#2885]
![image](https://github.com/microsoft/promptflow/assets/102211238/ef91ebcf-3089-4a66-a878-7a4db55e359c)

add support of below embedding models for "index lookup" tool
- text-embedding-3-large, 
- text-embedding-3-small

and new size of dimension 3072

model detail , please refer to https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#embeddings-models

![image](https://github.com/microsoft/promptflow/assets/102211238/6ec7bf5d-6599-46be-8c36-83f1d8026371)

**Comment by chjinche** [comment]
Hi @lok-msft I can list `text-embedding-3` in Azure OpenAI deployment_name. Can you clarify more about your problem?

![image](https://github.com/microsoft/promptflow/assets/49483542/b89fa770-a3af-487c-8ed8-b0d454a9c85f)
