### ISSUE TITLE
Unable to create a new connection

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#2937]
**Describe the bug**

When I click "create connection", I always get this error: Exception: Promptflow may not installed correctly. If you are upgrading from 'promptflow<1.8.0' to 'promptflow>=1.8.0', please run 'pip uninstall -y promptflow promptflow-core promptflow-devkit promptflow-azure', then 'pip install promptflow>=1.8.0'. Reach https://microsoft.github.io/promptflow/how-to-guides/faq.html#promptflow-1-8-0-upgrade-guide for more information.

I installed promptflow >=1.8.0 as the instructions said, and I am still getting the same issue.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. In the flow DAG, click "add connection"
<img width="376" alt="image" src="https://github.com/microsoft/promptflow/assets/147888261/05a55cd5-c58f-4eb1-9461-5f8dbff0bdae">

2. Enter the correct url and click "Create connection" <img width="218" alt="image" src="https://github.com/microsoft/promptflow/assets/147888261/db45bcf7-8b13-4f87-a9e8-6d46e5360484">
3. Enjoy error 
<img width="674" alt="image" src="https://github.com/microsoft/promptflow/assets/147888261/a6cfb402-9b67-4de8-aa4e-cb9d83c567f3">

**Expected behavior**
I expected a connection to be created without an error

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: Even trying to do this triggered the same error
 - Operating System: Windows 11
 - Python Version [python==3.9]

**Comment by brynn-code** [comment]
That's the DLL load failed error, seems conda env missing some path then can't find the DLLs. could you please try create a new conda env and re-install promptflow? That 'may not install correctly' is trying to handle another issue, instead of yours DLL missing one.

**Comment by tyler-suard-parker** [comment]
I am not using conda, I am just using a venv.  Is conda required?

**Comment by brynn-code** [comment]
No, whatever conda or venv, seems some paths are missing, this may caused by multiple reason, for example the env was created with admin permission and vscode running with regular permission then caused something can't be accessed by vscode. Could you please try running a pf command, like 'pf --version' from the console you set up the venv?
