### ISSUE TITLE
[VSCode Extension] How can I modify the Vscode extension to make some personal additions

### ISSUE THREAD

**Issue by saurabhgssingh** [microsoft/promptflow#2961]
**Describe the bug**
I want to make some changes to the promptflow extension. Want to add some support for once click deployment on my own infrastructure. I was not able to find extension codes. 
If someone can help me with some resources that will be helpful

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/58776330/42d4c99f-ec62-4101-aaee-17b590d99bbf)

**Additional context**
I want to add a "deploy' button to the flow in the left pane. The button on click will run a pipeline that will build the docker, and will also create a kubernetes deployment with the same image

**Comment by JYC-99** [comment]
Your request to include additional actions such as "deploy as docker image" is recognized as valuable. We will ensure it is tracked for consideration in future updates.

As for open sourcing the extension, currently, there are no plans to do so. However, we greatly value your feedback and suggestions. We're always looking to make our extension better and better.
