### ISSUE TITLE
[BUG] Running executable fails 

### ISSUE THREAD

**Issue by kenzabenjelloun** [microsoft/promptflow#2962]
Hello ! When trying to run an executable of python scripts that uses a flow as function (not using the pf build command), I got the following error with pf 1.9.0 : 

"Traceback (most recent call last): File "prepdocs.py", line 3, in File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "commands\doc_index.py", line 9, in File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "promptflow_init.py", line 19, in from promptflow._sdk._pf_client import PFClient as _PFClient File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "promptflow_sdk_pf_client.py", line 23, in from .operations import RunOperations File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "promptflow_sdk\operations_init.py", line 7, in from ._flow_operations import FlowOperations File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "promptflow_sdk\operations_flow_operations.py", line 34, in from promptflow._sdk._orchestrator import TestSubmitter File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "promptflow_sdk_orchestrator_init.py", line 5, in from .test_submitter import TestSubmitter File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "promptflow_sdk_orchestrator\test_submitter.py", line 15, in from promptflow._internal import ConnectionManager File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "promptflow_internal_init.py", line 104, in from promptflow.core._serving.utils import ( File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "promptflow\core_serving\utils.py", line 14, in from opentelemetry.propagate import extract, set_global_textmap File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "opentelemetry\propagate_init.py", line 148, in raise ValueError( ValueError: **Propagator tracecontext not found. It is either misspelled or not installed.** " 

But it works with pf 1.5 !

**Comment by wxpjimmy** [comment]
@kenzabenjelloun  could you share the opentelemetry-api and opentelemetry-sdk version installed in your runnint env?
