### ISSUE TITLE
[Feature Request] For Azure version, have components that are reusable across different flows.  Also have a dropdown for AI Search connections instead of entering URI as a string.

### ISSUE THREAD

**Issue by Tylersuard** [microsoft/promptflow#2964]
**Is your feature request related to a problem? Please describe.**
It is a little frustrating to have to enter the same information every time I create a flow.  Also I would prefer to not have to navigate away and copy a URI from my AI search account and paste it into Promptflow.

**Describe the solution you'd like**
When I create a new flow, I can choose to incorporate components created in previous flows: Connect to AI Search, use a specific prompt, etc.

For the vector index lookup component, it would be great if I could just select the correct AI search index using the dropdown box instead of having to copy-paste the URI for that resource's storage.

**Comment by brynn-code** [comment]
@dans-msft @Adarsh-Ramanathan Hi friends, please take a look at this issue, thanks in advance.
