### ISSUE TITLE
[BUG] No seed parameter advanced parameters when using LLM's Azure openAI connection in VSCode prompt flow UI

### ISSUE THREAD

**Issue by usoni1** [microsoft/promptflow#2969]
**Describe the bug**

see image. There is no seed parameter for Azure OpenAI call. 
<img width="681" alt="image" src="https://github.com/microsoft/promptflow/assets/23586503/525a8cdc-8c8f-4412-916b-4e987fa4e657">

**Comment by chjinche** [comment]
@Joouis will help update the tool spec in extension.

**Comment by Joouis** [comment]
@usoni1 Hello, `seed` parameter has been supported by the latest pre-release version of PF VSCode extension, please give a try. Of course this will be included in next official release.

![image](https://github.com/microsoft/promptflow/assets/8896124/04f14b3c-7c81-4726-8aeb-376d74190cdf)
