### ISSUE TITLE
[BUG] I can't use Azure PromptFlow without an Azure OpenAI deployment.  I can't get an Azure OpenAI deployment without filling out a long form with a company address.

### ISSUE THREAD

**Issue by Tylersuard** [microsoft/promptflow#2992]
**Describe the bug**
I am trying to test out Azure PromptFlow to see if it will be useful.  While setting up, I am using the "Q&A with your own data" template.  I try to create a vector index with Azure AI Search (which PromptFlow is still calling Cognitive Search btw).  When I try to add this search index to PromptFlow, it says that before I do that, I must create an Azure OpenAI deployment.  
![image](https://github.com/microsoft/promptflow/assets/41713505/7644dd97-835a-4674-9db0-f36e95275975)
I can't create an OpenAI deployment because I need to fill out this long form with information about my company.  I am just trying to test this out on my own, not with my company.  
![image](https://github.com/microsoft/promptflow/assets/41713505/a04dd611-5bab-40ae-aa33-fc5559ec8786)

**Expected behavior**
It would be great if PromptFlow could use a different embedding program so I don't have to fill out a form and make a request just to get access to it.

**Comment by brynn-code** [comment]
Hi @Tylersuard , thanks for reaching us, our github issue here mostly for tracking opensource promptflow issues, for Azure experience related questions, you could follow this guide: https://microsoft.github.io/promptflow/cloud/azureai/faq.html#how-to-create-feedback-for-azure-portal-experience to open an OCV, our PM will triage them 😊

**Comment by brynn-code** [comment]
Close: should track with OCV about portal experience.
