### ISSUE TITLE
[BUG] Promptflow with AI Search only allows one content field

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#2995]
**Describe the bug**
I set up Promptflow to connect to my Azure Cognitive Search Index.  I can only choose one field from the dropdown menu.  My Azure Cognitive Search index has multiple fields, all of which contain critical information.  Why did you choose to have only one field here, and how do I get around this?
**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1.Set up PromptFlow example for Q&A on your own data, and connect it with Azure AI Search/ Azure Cognitive Search 
2. Click the lookup, then click the input box for mlindex_content
3. Try to add more than one field from the Azure AI Index

**Expected behavior**
I want to be able to add as many fields from the AI search as I want, instead of just limiting myself to one.

**Screenshots**
<img width="659" alt="image" src="https://github.com/microsoft/promptflow/assets/147888261/58610df8-6fb9-48f2-8349-b1bd1dcd074e">

**Comment by brynn-code** [comment]
Hi @dans-msft , @Adarsh-Ramanathan please also take a look at this vector db tool issue, thank you!
