### ISSUE TITLE
[BUG] Rename "Activate config" to "Do not run this module unless..."

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#2996]
The current name is confusing and not descriptive.  I had no idea what it meant until I read a tutorial.
```[tasklist]
### Tasks
```

**Comment by brynn-code** [comment]
@tyler-suard-parker Thanks for reaching us, could you please elaborate more about the question, rename which "Activate config"? It would be better if you could provide a screenshot for more details.

**Comment by tyler-suard-parker** [comment]
<img width="492" alt="image" src="https://github.com/microsoft/promptflow/assets/147888261/08e1ff15-a911-4b8c-a5e3-326e0ad184ce">
@brynn-code thank you for your response.  Here is a screenshot of what I mean.  The "Activate Config" keyword at the bottom shows a boolean value.  I had no idea what that meant, I thought there was some kind of external config related to this.  I watched a tutorial, which said that this box determines whether the accompanying node is bypassed or not.  I would change that "Activate Config" title to "Run Node" or "Condition for running node" or something more descriptive and less confusing.

**Comment by jiaochenlu** [comment]
Hi @tyler-suard-parker, very appreciate your feedback and suggestion, we have created a task to track this usability improvement, will evaluate priorities and add to future plan
