### ISSUE TITLE
[BUG] [VSCode Extension] python interpreter selector not persistented to flow editor

### ISSUE THREAD

**Issue by henry-zeng** [microsoft/promptflow#302]
**Describe the bug**
A clear and concise description of the bug.
when I go to install dependencies -- select python interpterter, choose the python encv
![image](https://github.com/microsoft/promptflow/assets/16591457/d56a431b-cbbb-41a6-bdaf-304e605eac98)

then I open a flow dag yaml, the runtime is not chosen

![image](https://github.com/microsoft/promptflow/assets/16591457/b826b000-1ef8-4471-89c9-fc02f6ee2eae)

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. 

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
2. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: 0.0.102528530
 - Operating System: [e.g. Ubuntu 20.04, Windows 11] Win11
 - Python Version using `python --version`: [e.g. python==3.10.12]Python 3.9.17
 - VS Code version 1.81.1
 - Prompt Flow extension version. . 1.0.4
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by JYC-99** [comment]
Fixed with extension release 1.0.5
