### ISSUE TITLE
[BUG] Async Flow as function gives a generator instead async generator

### ISSUE THREAD

**Issue by Gzozo** [microsoft/promptflow#3069]
**Describe the bug**
I am loading a flow that calls gpt model as an async function, because i try to run it on a server. When i call the function it gives me back a generator, which is not ideal in a server environment, it will block. 

**How To Reproduce the bug**
1. Load a flow that streams with AsyncFlow.load()
2. Execute the function and await its result
3. The result's answer field is a generator object

**Expected behavior**
The result's answer object is a async generator.

**Running Information:**
 - Promptflow Package Version using `pf -v`: 1.10.0
 - Operating System: Windows 11
 - Python Version using `python --version`: 3.11

**Additional context**
I am trying to deploy one webapp for limited number of flows, to reduce costs in Azure

**Comment by thy09** [comment]
Hi @Gzozo Can you share a simple repro of your scenario? I have tried simple async function and it works:
```python
@tool
async def async_gen(conn: AzureOpenAIConnection, message):
    cli = AsyncAzureOpenAI(api_key=conn.api_key, azure_endpoint=conn.api_base, api_version=conn.api_version)
    messages = [{"role": "user", "content": message}]
    resp: AsyncIterable[ChatCompletionChunk] = await cli.chat.completions.create(messages=messages, model="gpt-35-turbo", stream=True)
    async for item in resp:
        if not item.choices:
            continue
        content = item.choices[0].delta.content
        if content:
            yield content
```

**Comment by Gzozo** [comment]
Hi @thy09 I tried the following: I created a simple chat promptflow in VSCode, with the OpenAI template, than I want to load it in my server:
```python
gpt_flow = AsyncFlow.load(f"{ROOT_PATH}promptflows/gpt")

message = 'Hello there'
chat_history = []

result = await gpt_flow(chat_history=chat_history, message=message)
```

And here is the result is not async generator. I'm still researching these promptflows, but essentially in your response, you create a tool, instead of using a built in OpenAI/LLM node?

**Comment by thy09** [comment]
Hi @Gzozo , currently the builtin LLM node is implemented by sync functions, this is why we don't have async generator returned. We need some extra dev work to convert it to an async generator. Let's keep this issue open, will update if we have some solution.

**Comment by thy09** [comment]
Added a quick fix workaround for this scenario.

**Comment by thy09** [comment]
@Gzozo The fix has been merged, you can wait for the next release(in 2 weeks) or install the main branch for workaround.

**Comment by gurvinder-dhillon** [comment]
@thy09 When running `pf flow test`, it nows gives a message to use fastapi.
But `pf flow test` does not support --engine flag.

**Comment by thy09** [comment]
@gurvinder-dhillon It sounds like another issue, could you please create a new issue with more details? Thanks.
