### ISSUE TITLE
Upgrade to Python 3.10 o3 3.11

### ISSUE THREAD

**Issue by FriederikeBrezing** [microsoft/promptflow#3152]
We would like to upgrade our code base to Python 3.10 or 3.11. 
Some packages that we would like to use, like PyRit, require Python >= 3.10.
Promptflow still recommends using 3.9.

**Describe the solution you'd like**
Promptflow should fully support Python 3.10 or higher

**Comment by D-W-** [comment]
Hi @FriederikeBrezing , we publicly support python 3.10 and 3.11. Check here for current supported versions:
![image](https://github.com/microsoft/promptflow/assets/7776147/55ff9ce8-ffef-4443-b4cf-e332a40f7976)

**Comment by FriederikeBrezing** [comment]
Hi, I had seen that but it also says that python 3.9 is recommended. 
What is the reason for that? Will it affect the performance if other versions of python are used? 

![Screenshot 2024-05-09 at 09 47 28](https://github.com/microsoft/promptflow/assets/129312652/efabe033-1688-4aa5-a8fc-b7ac11d10e94)

**Comment by D-W-** [comment]
This is a comment written before we supported Python 3.9. I will delete it to avoid confusion.

**Comment by amichel** [comment]
The Docker file in the dev container is still based on the python:3.9 image. Can it be upgraded as well?

**Comment by adam-lagoda** [comment]
@amichel same goes for the default version when building using 
`pf flow build --source ./flows/standard --output dist --format docker`

And the output Dockerfile contains 
`RUN conda create -n promptflow-serve python=3.9.16 [..]` by default
Can this be altered?
I would kindly ask @wangchao1230 to reopen

**Comment by HakjunMIN** [comment]
@wangchao1230 Hey. Please open this issue again

pf flow build --source ./flows/standard --output dist --format docker

And the output Dockerfile contains
RUN conda create -n promptflow-serve python=3.9.16 [..] by default

Please make its version configurable !!!

**Comment by adam-lagoda** [comment]
python version in the deployed image is fixed in `src/promptflow-devkit/promptflow/_sdk/data/docker/Dockerfile.jinja2`
Would be great to make this configurable, or at least parsable from the python version from the active environment that is used for the build.

**Comment by adam-lagoda** [comment]
I have added a separate issue to address this feature request
https://github.com/microsoft/promptflow/issues/3937

**Comment by adam-lagoda** [comment]
I also made a PR that solves the problem
https://github.com/microsoft/promptflow/pull/3939
