### ISSUE TITLE
[BUG] [VSCode Extension] unable to configure mlindex_content

### ISSUE THREAD

**Issue by JuhyunLee0** [microsoft/promptflow#3159]
getting error when using the promptflow extension from vscode 

`from promptflow._sdk._utils import _retrieve_tool_func_result ModuleNotFoundError: No module named 'promptflow._sdk._utils'`

when opening the dialog for the "lookup index - mlindex_content" box.

entire prompt flow was downloaded from freshly generated "QnA with your data" from Azure AI Studio

- Windows 11
- No virtual Environment
- Python 3.11.9
- pf -v 
  - "promptflow": "1.10.1",
    "promptflow-core": "1.10.1",
    "promptflow-devkit": "1.10.1",
    "promptflow-tracing": "1.10.1"

![image](https://github.com/microsoft/promptflow/assets/152219307/eaf44920-0100-4327-b30c-6e0175b3e3b8)

things that I have tried, but failed to resolve
- reinstall extension
- install "pre-release" version of the extension
- configure the prompt flow and the mlindex_content on the Azure AI studio, then import them to vscode
  - same issue rose, but on different field
  - ![image](https://github.com/microsoft/promptflow/assets/152219307/9bc5aa3a-c302-4c9d-afc5-3a7331eec8bc)

**Comment by elliotzh** [comment]
Hi @JuhyunLee0 this is an compatibility issue brought in in promptflow 1.10.1. Please downgrade your prompftlow to 1.9.0 as a workaround and we will contact extension team to fix it as soon as possible

**Comment by JuhyunLee0** [comment]
Thank you @elliotzh I was able to resolve the issue by downgrading to 1.9.0 version.

but Im now getting this error, 

`promptflow._utils.tool_utils.FunctionPathValidationError: Unable to display list of items due to 'Failed to parse function from function path: 'promptflow_vectordb.tool.common_index_lookup_utils.list_available_index_types'. Expected format: format 'my_module.my_func'. Detailed error: cannot import name 'MLClient' from 'azure.ai.ml' (unknown location)'. Please contact the tool author/support team for troubleshooting assistance.`

any help would be greatly appreciated

![image](https://github.com/microsoft/promptflow/assets/152219307/55a55a46-386d-41e1-81d1-e8659d2d8d59)

things I have tried
- downgraded all the package related to promptflow to 1.9.0
- installed `promptflow-vectordb`
- installed `azure-ai-ml`

**Comment by VRAJP-07** [comment]
Hello @JuhyunLee0 

The error which message which you've shared is because you haven't installed `promptflow_vectordb` instead you've installed `promptflow-vectordb`

I was getting same error message when I executed the promptflow, but after installing  `promptflow_vectordb` error was resolved.

After installing  `promptflow_vectordb` you can refer to this [site ](https://github.com/microsoft/promptflow/issues/2238)if you're getting any errors related to list_endpoint_names.

Feel free to ask if you need further assistance!

**Comment by pgr-lopes** [comment]
Hey. Did anyone ever get this to work? I'm getting the same error when using pf version 1.11. If I bring it back to 1.9 I get this error instead:

> promptflow._utils.tool_utils.FunctionPathValidationError: Unable to retrieve result due to 'Failed to parse function from function path: 'promptflow_vectordb.tool.common_index_lookup_utils.list_available_index_types'. Expected format: format 'my_module.my_func'. Detailed error: No module named 'azureml.rag''. Please contact the tool author/support team for troubleshooting assistance.

Tried to manually install de aml-rag library, but that didn't help. I noticed that the VectorDB activity does not show up in the tools in the PF vscode extension, so I'm wondering if this is a problem with the promptflow-tools library.

**Comment by JuhyunLee0** [comment]
I couldn't get the prompt flow tools to work, even after installing `promptflow_vectordb` instead of `promptflow-vectordb`

I actually just ended up just writing the vector DB lookup via Python code and run the prompt flow that way.

**Comment by Mandypo647** [comment]
After installing all these things I am also getting one error:
pf.flow.test failed with UserErrorException: Exception: Execution failure in 'lookup': (Exception) Exception occured in search_function_construction.

![Error_Mlindex_onLocal](https://github.com/user-attachments/assets/a2275c87-9d47-4fe1-b567-64d390bc6bd0)
