### ISSUE TITLE
[BUG] [VSCode Extension]

### ISSUE THREAD

**Issue by Owennn32** [microsoft/promptflow#3183]
**Describe the bug**
I have installed the package, but the page of install dependencies still shows "not installed"

**Screenshots**
![螢幕擷取畫面 2024-05-10 095938](https://github.com/microsoft/promptflow/assets/160827751/0cc5e445-b155-4f92-bf3b-2faf87f3101c)
![image](https://github.com/microsoft/promptflow/assets/160827751/e9e3f733-9678-41e9-8be3-ed28848d9f41)

**Environment Information**
Python Version: Python 3.9.19

Operating System: Windows 11

Prompt Flow extension version:
promptflow                               1.10.0
promptflow-azure                         1.10.0
promptflow-core                          1.10.0
promptflow-devkit                        1.10.0
promptflow-tools                         1.4.0
promptflow-tracing                       1.10.0

**Comment by linningmii** [comment]
ACK, we’re using a wrong way to detect the version of promptflow-azure, but it shall not block the usage.

We’ll fix the issue soon.

**Comment by linningmii** [comment]
@Owennn32 

We've resolved the issue, and the patch will be accessible shortly after the next upgrade of either the VS Code extension (1.20.0) or SDK (1.11.0), as both can accommodate the patch. Apologies for any confusion and inconvenience caused.

**Comment by jhcaml** [comment]
This issue is still occuring
