### ISSUE TITLE
How can I save global variables using Promptflow

### ISSUE THREAD

**Issue by dobahoang** [microsoft/promptflow#3198]
How can I save global variables using PromptFlow? Currently, I can only see the variable "chat_history".

Before calling the API, I need to collect some information such as the user's name, address, and phone number. Each time a user answers a question, the corresponding information is stored in a variable.

On the next pass, I want the chatbot to check the previous values the user has provided before deciding to call the API or ask the user for missing parameters. However, I have not found any documentation mentioning this.

Does anyone have any advice or suggestions for me?

**Comment by D-W-** [comment]
Hi @dobahoang , currently we don't support storing variables as intermediate data between flow runs. But for chat history, we'll add a doc on our recommended way to save/load it. I'll update here once the PR's out.
