### ISSUE TITLE
[BUG] Fallback to DefaultAzureCredential isn't compatible with AzureDeveloperCliCredential

### ISSUE THREAD

**Issue by pamelafox** [microsoft/promptflow#3243]
**Describe the bug**

PromptFlow currently falls back to using DefaultAzureCredential and fetching a token for the Oauth 1.0 audience. That is not compatible with all credentials in the chain, specifically, the AzureDeveloperCliCredential which is Oauth 2.0 only. This PR changes the audience value to the correct scope value, and renames variables accordingly.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Run `azd auth login` and DONT login to Azure CLI
2. Run ai-rag-chat-evaluator or other sample code that does *not* specify a credential when using the evaluators/evaluate function

PR incoming!

**Comment by D-W-** [comment]
Hi @pamelafox , code owners approved the change. Feel free to merge it.
