### ISSUE TITLE
[BUG] prompty-quickstart.ipynb run evaluation not working due to RuntimeError 

### ISSUE THREAD

**Issue by imk4novazoon** [microsoft/promptflow#3291]
**Describe the bug**
Run evaluation with PFClient throws RuntimeError 

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:

1. follow the exact instructions in [prompty-quickstart.ipynb](https://github.com/microsoft/promptflow/blob/main/examples/prompty/basic/prompty-quickstart.ipynb) up to `pf = PFClient()`
2. Run the following code: 
```
flow = "./basic.prompty"  # path to the prompty file
data = "./data.jsonl"  # path to the data file

# create run with the flow and data
base_run = pf.run(
    flow=flow,
    data=data,
    column_mapping={
        "first_name": "${data.first_name}",
        "last_name": "${data.last_name}",
        "question": "${data.question}",
    },
    stream=True,
)
```

Happens consistently.

**Expected behavior**

execute pf.run()

**Screenshots**
![Screenshot 2024-05-16 103609](https://github.com/microsoft/promptflow/assets/166835892/dd60e798-c9a8-40cf-a36c-e29249df5afc)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.10.1
 - Operating System: Windows 11
 - Python Version using `python --version`: python== 3.9.13

**Comment by lalala123123** [comment]
Hi @imk4novazoon , does this issue occur when executing the notebook or a python script?
I did not reproduce this issue when executing it in notebook. 
If you execute this code in a python script, which is by design, you need to move pf.run to __name__=="__main__"

**Comment by imk4novazoon** [comment]
Thank you @lalala123123 . That was it.
