### ISSUE TITLE
chat pdf viewer code release?

### ISSUE THREAD

**Issue by flckv** [microsoft/promptflow#3312]
Is there any plan on releasing the ui and backend that you show on the screenshot( chatbot + pdf viewer (espcially interested in the interactive pdf viewer) the recently updated part: 
[microsoft/promptflow](https://github.com/microsoft/promptflow) · [examples/tutorials/e2e-development/chat-with-pdf.md](https://github.com/microsoft/promptflow/blob/94c85e36edb22563bea20a47b07a49cf6bfa0086/examples/tutorials/e2e-development/chat-with-pdf.md?plain=1#L2)
![image](https://github.com/microsoft/promptflow/assets/103381497/23008c75-b8e9-4786-ac80-11d4536a787e)

**Comment by brynn-code** [comment]
Hi @flckv, thanks for reaching us. The UI shown in the markdown is Bing chat UI, we don't have plan to integrate it with promptflow for now.
![image](https://github.com/microsoft/promptflow/assets/24237253/96ce0ec0-46ba-44a9-8e15-3f73865e905a)

**Comment by brynn-code** [comment]
Close as not planned.
