### ISSUE TITLE
[BUG] Connection for Azure OpenAI not working when following README procedure

### ISSUE THREAD

**Issue by tvriesde** [microsoft/promptflow#3321]
**Describe the bug**
After creation of connection using the README instructions for Azure OpenAI I get error:

pf.flow.test failed with UserErrorException: Exception: OpenAI API hits NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}} [Error reference: https://platform.openai.com/docs/guides/error-codes/api-errors]

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create Codespace
2. Create OpenAI in Azure and deploy a model
3. Create connection using: pf connection create --file ./my_chatbot/azure_openai.yaml --set api_key=<your_api_key> api_base=<your_api_base> --name open_ai_connection
4. pf flow test --flow ./my_chatbot --interactive

as API_BASE i've used: Azure OpenAI Endpoint -> "https://something.openai.azure.com/"
as API_KEY i've used: Azure OpenAI Key1

Error message:
OpenAI API hits NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}} [Error reference: https://platform.openai.com/docs/guides/error-codes/api-errors]
pf.flow.test failed with UserErrorException: Exception: OpenAI API hits NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}} [Error reference: https://platform.openai.com/docs/guides/error-codes/api-errors]

azure_openai.yaml content:
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/AzureOpenAIConnection.schema.json
name: open_ai_connection
type: azure_open_ai
api_key: "<user-input>"
api_base: "<user-input>"
api_type: "azure"

I would expect that I also have to supply the deployment name but don't find the option.

**Comment by brynn-code** [comment]
Hi @tvriesde , thanks for reaching us. The 'deployment name' is not part of connection, it was on the flow node in flow.dag.yaml if you are using the llm node to make the openai call.
![image](https://github.com/microsoft/promptflow/assets/24237253/03cba896-4ceb-496e-9c02-cf298a3bf4f4)

**Comment by tvriesde** [comment]
> Hi @tvriesde , thanks for reaching us. The 'deployment name' is not part of connection, it was on the flow node in flow.dag.yaml if you are using the llm node to make the openai call. For example: ![image](https://private-user-images.githubusercontent.com/24237253/332642248-2f96cede-eac4-41de-b60f-ff1203d8a029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjE5MjgsIm5iZiI6MTcxNjM2MTYyOCwicGF0aCI6Ii8yNDIzNzI1My8zMzI2NDIyNDgtMmY5NmNlZGUtZWFjNC00MWRlLWI2MGYtZmYxMjAzZDhhMDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MmFlNGEyNTAzZDM3ZTllMTM0MDhjYzc2ZDNhN2VhOTIzNjVmNzcxMjA3MDRmMDA0ZWFiMGIxMjljOWY4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lkg-BBow0nfqbpp68T4aJ-fY4mTLK0O0vDgTJqkRu6k)

Thanks @brynn-code. Works like a charm.
