### ISSUE TITLE
[BUG] Setting OTEL_EXPORTER_OTLP_ENDPOINT causes export error

### ISSUE THREAD

**Issue by joshuaphelpsms** [microsoft/promptflow#3342]
**Describe the bug**

Running the prompt flow server and setting the environment variable `OTEL_EXPORTER_OTLP_ENDPOINT`, produces the following error and metrics and logs are not exported:

```sh
promptflow  | Failed to export batch code: 404, reason: 404 page not found
```

I believe this is due to the way the environment variables are passed to `OTLPMetricExporter` and `OTLPSpanExporter` using the HTTP/Proto.

OTLPSpanExporter expects an endpoint of:  `OTLPSpanExporter(endpoint="<traces-endpoint>/v1/traces")`
OTLPMetricExporter expects an endpoint of: `OTLPMetricExporter(endpoint="<traces-endpoint>/v1/metrics")`

See [OTEL docs](https://opentelemetry.io/docs/languages/python/exporters/#usage)

Since the code uses `OTEL_EXPORTER_OTLP_ENDPOINT` for both traces and metrics, I am unable to set this single environment variable for both. I have seen that the logs exporter will be coming soon so this should also be updated or fixed. I know that I can alternatively use `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` and` OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`, but wanted to bring this up as it is not working as I would have expected.

**How To Reproduce the bug**

1. Run an OpenTelemetry collector
2. Run the chat basic prompt flow server with the otel endpoint environment variable set `OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}`
3. Send a message and wait for a few seconds
4. check the logs

**Expected behavior**
I expect the metrics and traces to be exported

 **Running Information:**
 - Promptflow Package Version using `pf -v`:
{
  "promptflow": "1.11.0",
  "promptflow-core": "1.11.0",
  "promptflow-devkit": "1.11.0",
  "promptflow-tracing": "1.11.0"
}
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
Linux - using docker.io/continuumio/miniconda3:latest container
 - Python Version using `python --version`:
Python 3.9.16

**Comment by wxpjimmy** [comment]
>OTLPSpanExporter expects an endpoint of: OTLPSpanExporter(endpoint="<traces-endpoint>/v1/traces")
>OTLPMetricExporter expects an endpoint of: OTLPMetricExporter(endpoint="<traces-endpoint>/v1/metrics")
could you provide more details on this? I don't think the suffix is needed here if you use `OTEL_EXPORTER_OTLP_ENDPOINT`.

In the latest code, this is what promptflow supported now:
* Support trace/metrics/log exporter, you can configure it via a common `OTEL_EXPORTER_OTLP_ENDPOINT` or you can configure to enable each one separately with `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT`, `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`, `OTEL_EXPORTER_OTLP_LOGS_ENDPOINT`;
* Support both http and grpc OTLP collector,  by default it's http,  you can use a grpc server by
    * add the `opentelemetry-exporter-otlp-proto-grpc` dependency in your requirements.txt
    * configure `OTEL_EXPORTER_OTLP_PROTOCOL=grpc` 

I'll close this first, let me know whether this can meet your expectation. @joshuaphelpsms,  if not, feel free to re-open and we can continue the discussion.

**Comment by joshuaphelpsms** [comment]
Since the endpoint is passed explicitly to the OTLPMetricExporter and OTLPSpanExporter's, it must have the `/v1/traces` or `/v1/metrics` in the endpoint. 

If no endpoint is passed then it will fall back to the environment variables. See how the endpoint is currently passed to the constructor for prompt flow:

https://github.com/microsoft/promptflow/blob/main/src/promptflow-core/promptflow/core/_serving/extension/otel_exporter_provider_factory.py#L182

Looking through the [OpenTelemetry code for http/proto](https://github.com/open-telemetry/opentelemetry-python/blob/d73593d1137a3854ceff3d7c94180d2bdb8b097f/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py#L73), the order of precedence for traces would be:

1. Endpoint is passed explicitly to the constructor (must include `/v1/traces`)
2. OTEL_EXPORTER_OTLP_TRACES_ENDPOINT environment var- (must include `/v1/traces`)
3. OTEL_EXPORTER_OTLP_ENDPOINT environment var - (/v1/traces appended to the endpoint for us, so we do not include `/v1/traces`)
4. If no endpoint or environment variables are set, it defaults to `http://localhost:4318/v1/traces`


I think what you probably want is to not pass the endpoint explicitly and rely on the environment variables to set the endpoint.

**Comment by joshuaphelpsms** [comment]
FYI: I am unable to reopen the issue because it was not closed by me
