### ISSUE TITLE
How do I use a different Python version for my custom promptflow runtime on AML?

### ISSUE THREAD

**Issue by sparse-coder** [microsoft/promptflow#3344]
I am trying to build a environment on AML and want to use different python version for this custom runtime. Is there a way I can customize promptflow runtime image to use a different python version from the Dockerfile or via any other method?

**Comment by Bowen-Guo** [comment]
Please follow the steps below:
1. Build your own image following this doc: https://pypi.org/project/promptflow-python-bundle/
2. Specify the image in flow.dag.yaml: 
···
environment：
    image: <your image>
···
3. Add "flight=PFMultiContainer" in the url. For example:
https://ml.azure.com/prompts/flow/bb99fa90-4815-4dcb-b9bd-ece6974528be/1db17e33-b6a6-42d1-a092-fb81a4c5a6bd/details?wsid=/subscriptions/96aede12-2f73-41cb-b983-6d11a904839b/resourcegroups/dacai-daily-eastus/providers/Microsoft.MachineLearningServices/workspaces/dacai-daily-ws**&flight=PFMultiContainer**&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
4. Start session.

**Comment by sparse-coder** [comment]
Thank you! @Bowen-Guo 

I am able to build the env in AML but, It isn't working when I start the compute session with error being "container not ready in time".

When I debugged, I found that process inside the container says "temporary node failure".  

I also want to understand what role **flight=PFMultiContainer** plays. Could you link back to any official doc?

**Comment by berndku** [comment]
@Bowen-Guo : this works for us in the  Web UI. However, when triggering runs with the Python SDK, we see below error again. Do we have to apply **flight=PFMuliContainer** through the SDK as well and if yes, how to do so ? Thanks!

```
(Run status is 'NotStarted', continue streaming...)
(Run status is 'NotStarted', continue streaming...)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/vsts/work/1/s/llmops/common/prompt_pipeline.py", line 427, in <module>
    main()
  File "/home/vsts/work/1/s/llmops/common/prompt_pipeline.py", line 414, in main
    prepare_and_execute(
  File "/home/vsts/work/1/s/llmops/common/prompt_pipeline.py", line 271, in prepare_and_execute
    pf.runs.stream(base_run)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/promptflow/_sdk/_telemetry/activity.py", line 265, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 693, in stream
    raise InvalidRunStatusError(error_message)
promptflow._sdk._errors.InvalidRunStatusError: Failed to submit bulk run due to Automatic runtime is not ready in a fixed timespan, error: Container not started
````

**Comment by Bowen-Guo** [comment]
Hi @berndku , yes you can set environment variable PF_ENABLE_MULTI_CONTAINER="true" before submitting bulk run.

**Comment by Bowen-Guo** [comment]
Hi @sparse-coder, we are currently in the process of onboarding a new internal feature: multi-container runtime. To put it in a nutshell, the automatic runtime will have multiple docker containers, instead of a single container. This feature can help customer easily use their own images.

This is an ongoing feature and has not been fully on line. So there is no official doc yet.

Set flight "flight=PFMultiContainer" in the uri will enable this feature in the backend.

**Comment by ebotiab** [comment]
This solution gives me the following error: Session status messages: Automatic runtime is not ready in a fixed timespan, error: Container not started

**Comment by lealgamb** [comment]
Hi @Bowen-Guo , is there an update on the feature timeline and documentation? Thanks.
