### ISSUE TITLE
[BUG] promptflow 1.11.0 raises IndexError: list index out of range

### ISSUE THREAD

**Issue by marinaby** [microsoft/promptflow#3355]
**Describe the bug**
When running a promptflow which calls a second promptflow as a function, we get the following error message:
IndexError: list index out of range

../..//lib/python3.9/site-packages/promptflow/_sdk/entities/_flows/base.py:239: in __call__
    result = self.invoke(inputs=kwargs)
../..//lib/python3.9/site-packages/promptflow/_sdk/entities/_flows/dag.py:170: in invoke
    return super().invoke(inputs=inputs)
../..//lib/python3.9/site-packages/promptflow/_sdk/entities/_flows/base.py:247: in invoke
    result = invoker._invoke(
../..//lib/python3.9/site-packages/promptflow/core/_serving/flow_invoker.py:207: in _invoke
    return self.executor.exec_line(data, run_id=run_id, allow_generator_output=self.streaming())
../..//lib/python3.9/site-packages/promptflow/executor/flow_executor.py:741: in exec_line
    line_result = self._exec(
../../lib/python3.9/site-packages/promptflow/executor/flow_executor.py:1027: in _exec
    output, aggregation_inputs = self._exec_inner_with_trace(
../..//lib/python3.9/site-packages/promptflow/executor/flow_executor.py:934: in _exec_inner_with_trace
    self._exec_post_process(inputs, output, nodes_outputs, run_info, run_tracker, span, stream)
../..//lib/python3.9/site-packages/promptflow/executor/flow_executor.py:965: in _exec_post_process
    run_tracker.update_and_persist_generator_node_runs(run_info.run_id, generator_output_nodes)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <promptflow._core.run_tracker.RunTracker object at 0x7fc19063ac10>
run_id = 'f5e974a5-d55f-4208-be32-502c38d1ba9e'
node_names = ['chat_with_context', 'post_process']
    def update_and_persist_generator_node_runs(self, run_id: str, node_names: List[str]):
        """
        Persists the node runs for nodes producing generators.
    
        :param run_id: The ID of the flow run.
        :type run_id: str
        :param node_names: The names of the nodes to persist.
        :type node_names: List[str]
        :returns: None
        """
        selected_node_run_info = (
            run_info for run_info in self.collect_child_node_runs(run_id) if run_info.node in node_names
        )
        for node_run_info in selected_node_run_info:
            # Update the output of the node run with the output in the trace.
            # This is because the output in the trace would includes the generated items.
>           output_in_trace = node_run_info.api_calls[0]["output"]
E           IndexError: list index out of range
../..//lib/python3.9/site-packages/promptflow/_core/run_tracker.py:452: IndexError

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a promptflow which invokes a second flows like this
second_flow = promptflow.load_flow(flow_path)
second_flow()
2. Invoke the (first) promptflow. 

**Expected behavior**
The flow should succeed.

**Running Information(please complete the following information):**
 - Promptflow Package Version: 1.11.0
 - Operating System: macos
 - Python Version using 3.9.18

**Additional context**
This issue started after upgrading promptflow  to 1.11.0 version, in version 1.10.0 we didn't have this problem.

**Comment by D-W-** [comment]
Hi @marinaby , thanks for reporting, we are fixing this bug in attached PR. I'll update here once it got released. Please pin back to `1.10.0` before next release. Thanks!
