### ISSUE TITLE
[Feature Request] Enable search filters and search params in Index Lookup tool

### ISSUE THREAD

**Issue by huanji-sun-007** [microsoft/promptflow#3365]
**Is your feature request related to a problem? Please describe.**

The Vector DB Lookup tool is deprecated, and we are upgrading to the new Index Lookup tool. The old Vector DB Lookup tool supports search parameters and search filters, allowing us to configure these settings. However, the new Index Lookup tool does not support this functionality, preventing us from upgrading to the new tool.

**Describe the solution you'd like**
Add search parameters and search filters to the new Index Lookup tool

Already synced this feature request with @henry-zeng

**Comment by brynn-code** [comment]
Hi, @dans-msft and @Adarsh-Ramanathan , could you please take a look at this issue? thanks!

**Comment by Briwalkr** [comment]
I agree with huanji-sun-007. The missing functionality is blocking our ability to deploy applications.

**Comment by jeremycampbellaustin** [comment]
I would also like to see this feature added so that I can limit the scope of the search results to a logged in user.

**Comment by Briwalkr** [comment]
To whom is this GitHub Action trying to reach?

**Comment by Briwalkr** [comment]
From my perspective, what I need is to pre-filter the documents in the vector database based on a text field in the database and a value provided by the user. Example: I have financial documents for all companies listed on an exchange. I some cases, I need to focus my questions on a specific type of document (which is a text column in my vector database), or by company name (also a column in the vector database). Users should be able to refine the document chunks in the vector database before the hybrid/vector comparison is made to determine the top x chunks to return to the Prompt Flow/sent to the LLM to answer the question.

**Comment by shubh802** [comment]
dans-msft: Do we have any expected timeline for this feature to be implemented.
