### ISSUE TITLE
[BUG] Azure PFClient gives error, unable to run the flow on Azure

### ISSUE THREAD

**Issue by gurvinder-dhillon** [microsoft/promptflow#3370]
**Describe the bug**
/lib/python3.11/site-packages/promptflow/azure/_restclient/flow_service_caller.py:124)     base_url = os.environ.get(self.FLOW_CLUSTER_ADDRESS, default=base_url)

AttributeError: 'NoneType' object has no attribute 'split'

**How To Reproduce the bug**

No error connecting to local or cloud connections when running below code
```
from promptflow.client import PFClient
from langchain_openai import AzureChatOpenAI

pf_client = PFClient()
connection = pf_client.connections.get(name=connection_name)
AzureOpenAIEmbeddings(
                azure_deployment=deployment_name,
                openai_api_key=connection.api_key,
                azure_endpoint=connection.api_base,
                openai_api_type=connection.api_type,
                openai_api_version=openai_api_version,
                model=model,
            )
```
The above works perfectly fine.

However when i try to make this work for Azure Cloud, I get error. My goal is to run the flow and test the flow in cloud, but can't proceed because i can't access the connections.

```
from azure.identity import DefaultAzureCredential
from promptflow.azure import PFClient
credential = DefaultAzureCredential()
credential.get_token("https://management.azure.com/.default")
pf = PFClient(
    credential=credential,
    subscription_id="xxxx-www-yyy-zzz",  
    resource_group_name="sandbox",
    workspace_name="sandboxchat"
)
```

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 pf = PFClient(
      2     credential=credential,
      3     subscription_id="xxx-yyy-zzz",  # this will look like xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      4     resource_group_name="sandboxtest",
      5     workspace_name="sandbox-chat"
      7 )

File ~/.cache/pypoetry/virtualenvs/zMWScKKV-py3.11/lib/python3.11/site-packages/promptflow/azure/_pf_client.py:71, in PFClient.__init__(self, credential, subscription_id, resource_group_name, workspace_name, **kwargs)
     69 except Exception as e:
     70     raise UserErrorException(message=str(e), error=e)
---> 71 self._service_caller = _FlowServiceCallerFactory.get_instance(
     72     workspace=workspace,
     73     credential=self._ml_client._credential,
     74     operation_scope=self._ml_client._operation_scope,
     75     **kwargs,
     76 )
     77 self._flows = FlowOperations(
     78     operation_scope=self._ml_client._operation_scope,
     79     operation_config=self._ml_client._operation_config,
   (...)
     84     **kwargs,
...
--> 122     base_url = workspace.discovery_url.split("discovery")[0]
    123     # for dev test, change base url with environment variable
    124     base_url = os.environ.get(self.FLOW_CLUSTER_ADDRESS, default=base_url)

AttributeError: 'NoneType' object has no attribute 'split'
```

**Running Information(please complete the following information):**
azure-ai-ml                              1.16.1
azure-common                             1.1.28
azure-core                               1.30.1
azure-cosmos                             4.7.0
azure-identity                           1.16.0
azure-mgmt-core                          1.4.0
azure-monitor-opentelemetry-exporter     1.0.0b25
azure-search-documents                   11.4.0
azure-storage-blob                       12.20.0
azure-storage-file-datalake              12.15.0
azure-storage-file-share                 12.16.0
prompt_toolkit                           3.0.45
promptflow                               1.11.0
promptflow-azure                         1.11.0
promptflow-core                          1.11.0
promptflow-devkit                        1.11.0
promptflow-tools                         1.4.0
promptflow-tracing                       1.11.0

**Additional context**
My final goal is to run flow in azure cloud prompt flow. So if there is an alternate, please suggest. What other options do i have to pass the environment variables (keys).

**Comment by 0mza987** [comment]
You can pass the credential object directly to the PFClient, so please remove this from your code:
`credential.get_token("https://management.azure.com/.default")`

More details can refer to [Run prompt flow in Azure AI — Prompt flow documentation](https://microsoft.github.io/promptflow/cloud/azureai/run-promptflow-in-azure-ai.html) SDK section.
