### ISSUE TITLE
[BUG] Non-retryable server side error: Operation returned an invalid status 'Bad Request'.

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#3376]
This occurs during 
!pf config set trace.destination="my_destination" in the autogen agent chat trace example notebook.

I believe this error is wrong, because In the next few cells I am able to run the autogen code and see my trace in the destination resource.  The connection is working, so why am I getting this error?

**Comment by zhengfeiwang** [comment]
Hi @tyler-suard-parker thanks for reporting your issue. `pf config set trace.destination` has some network requests, so it's hard to conclude which request returns bad request. Is it possible to share some screenshots, or trace back? so that we can better investigate your issue.

**Comment by zhengfeiwang** [comment]
if possible, please try add `--debug` and retry, which will print more details and error messages; as I mentioned before, there are several requests during this process, simple bad request cannot indicate what goes wrong - I tried from my side, but cannot re-produce this.

**Comment by tyler-suard-parker** [comment]
Hello Zhengfei, for some reason the error is not occurring anymore.  Sorry for wasting your time.
