### ISSUE TITLE
[BUG] pf.config.set failed with MissingAzurePackage: "promptflow[azure]" is required for this functionality, please install it by running "pip install promptflow-azure" with your version.

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#3383]
**Describe the bug**
This one line says we need to install promptflow[azure] and promptflow-azure.  Which one should we install?  Do both pip install promptflow[azure] and pip install promptflow-azure lead to the same package?

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
Follow the instructions in readme.md: 
1. Create new venv using requirements.txt
2. pip install promptflow promptflow-tools
3. pf config set trace.destination="azureml://subscriptions/...."

**Expected behavior**
I expect to connect successfully to the trace destination.

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 
 - Operating System: Windows 11
 - Python Version using `python --version`: [e.g. python==3.9.13]

**Additional context**
Please add more detailed instructions to the examples here: 
https://github.com/microsoft/promptflow/tree/main/examples/tutorials/tracing

Not one of them includes the critical steps of installing promptflow-azure, using az-login, and configuring the trace destination.

**Comment by brynn-code** [comment]
Hi, the promptflow[azure] equals to promptflow-azure, we leave promptflow[azure] there because that's a legacy way to install required packages and we should not break the usage.

**Comment by tyler-suard-parker** [comment]
Ok, thank you.
