### ISSUE TITLE
[BUG] I only want to send 1 trace, but PromptFlow sends 4 every time

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#3384]
**Describe the bug**
I am attempting to use Promptflow tracing.  I followed the tutorial on Autogen tracing.  When I apply tracing to my code, it sends out 4 traces, 2 of which I did not create.  How can I change this behavior so it only sends out the one trace that I did create?
<img width="935" alt="2024-06-06 15_01_25-Trace View and 7 more pages - Work - Microsoft​ Edge" src="https://github.com/microsoft/promptflow/assets/147888261/043a6ca6-8598-4704-bb18-214c46703c51">

**Example code**
    tracer = trace.get_tracer("my_tracer")
    with tracer.start_as_current_span("autogen") as span:

        chat.create_agents(sock=sock)
        asyncio.run(chat.run_agents())
        sock.send("TERMINATE")
        last_message = extract_last_message_from_chat(chat)
        all_messages = extract_all_messages_from_chat(chat)

        span.set_attribute("custom", "custom attribute value")
        # recommend to store inputs and outputs as events
        span.add_event(
            "promptflow.function.inputs",
            {"payload": json.dumps(dict(message=history[-1]))},
        )
        span.add_event(
            "promptflow.function.output", {"payload": json.dumps(last_message)}
        )

**Expected behavior**
I set up only one trace, the trace called "autogen".  The words "openai_chat" do not appear anywhere in my code.

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.11.0
 - Operating System: Windows 11
 - Python Version using `python --version`: [python==3.9.12]

**Comment by brynn-code** [comment]
@tyler-suard-parker autogen itself will call openai several times to get the result/simulate the chat group turns, that's related to the inner logic of autogen which is not related to promptflow tracing.

**Comment by tyler-suard-parker** [comment]
Thank you Brynn.  How do I turn it off?  I do not want tracing on those parts, I only want it on the parts that I specify.

**Comment by brynn-code** [comment]
There is an internal workaround to achieve this, I'll leave this to our tracing expert @thy09 XD

**Comment by thy09** [comment]
Hi @tyler-suard-parker  I think you can call this internal function after `start_trace` to avoid openai_chat for workaround.
https://github.com/microsoft/promptflow/blob/96dbf33ab97a7e53b189c4b2b570742242d1f980/src/promptflow-tracing/promptflow/tracing/_integrations/_openai_injector.py#L204
```python
from promptflow.tracing._integrations._openai_injector import recover_openai_api
```
Note that this is an internal function, we do not expose a public function now.
Maybe we can have a public function for that or add an option in `start_trace`

**Comment by thy09** [comment]
@tyler-suard-parker This is an internal function, so we are not ready to expose it. We may need some discussion how to expose such APIs.
