### ISSUE TITLE
[BUG] Error when running AOAI function calling example

### ISSUE THREAD

**Issue by FlorianPydde** [microsoft/promptflow#3401]
**Describe the bug**
I am running the example provided for function calling as-is on my local machine, not on Azure. There is an error when executing a funciton. I guess there is some issue with the jinja conversation:
`pf.flow.test failed with UserErrorException: Exception: OpenAI API hits BadRequestError: Error code: 400 - {'error': {'message': "'##' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.6.name'", 'type': 'invalid_request_error', 'param': None, 'code': None}} [Error reference: https://platform.openai.com/docs/guides/error-codes/api-errors]`

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Run examples/flows/chat/use_functions_with_chat_models in interactive chat mode.
2. User query: How about London next week? -> chatbot will ask for number of days
3. User query: 5
4. Failure

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 
 {
  "promptflow": "1.11.0",
  "promptflow-core": "1.11.0",
  "promptflow-devkit": "1.11.0",
  "promptflow-tracing": "1.11.0"
}
 - Operating System: Windows 11
 - Python Version using `python --version`: Python 3.11.0

**Comment by lalala123123** [comment]
Hi @FlorianPydde , I have not reproduced this issue.
![image](https://github.com/microsoft/promptflow/assets/17938940/9ec65ba6-5c65-463d-a488-b3871401dd85)

From the error message, it appears that this error is related to the message sent to LLM. Have you ever changed the source code?

**Comment by FlorianPydde** [comment]
Thanks for getting back. I found the error. I was using an AOAI model that was NOT supporting function calling. I did the test with two others supporting it and it works as expected.
Sorry for the inconvenience.

**Comment by tyler-suard-parker** [comment]
I had this issue too, it turns out the names of agents cannot have spaces in them.
