### ISSUE TITLE
Integrate a APIM in front of deployments in PromptFlow

### ISSUE THREAD

**Issue by adampolak-vertex** [microsoft/promptflow#3409]
We will be using an APIM in front of multiple TPU deployments to serve our application. Currently PromptFlow does not have an option to connect with this type of a setup.

![image](https://github.com/microsoft/promptflow/assets/171858339/c6d8e96a-2f0f-47cf-b2b3-f3eddf229dca)
![image](https://github.com/microsoft/promptflow/assets/171858339/8e1a7fd5-09e0-4b35-9810-923a36733b01)

There should be an ability to integrate this type of architecture (APIM in front of multiple deployments) to support a PromptFlow endpoint. 

I could change the LLM module in the PromptFlow to a python request to OpenAI but then we lose our traceability that comes with the LLM module.

What would be the best way to integrate an APIM/deployment architecture with PromptFlow to maintain traceability?

**Comment by cloga** [comment]
It is known feature request tracing here: https://msdata.visualstudio.com/Vienna/_workitems/edit/2669363/

**Comment by graemefoster** [comment]
@cloga I don't have visibility into the work-item, but as a request, it would be awesome if this supported the scenario as passing a JWT as-well as an APIm subscription key.

APIm subscription Keys are not great security (shared secret, passed around over the wire, don't expire), but they are the only way to invoke Product behaviour in APIm. Products are great as they allow tailored policy for a specific scenario.

But a JWT is much better security wise.

I'd love if whatever is built into Prompt Flow offered the option of providing both. And not just for the azure open-ai scope (https://cognitiveservices.azure.com/.default) but for any application so I could use my own customer Idp in-front of APIm, and switch to Entra behind it.

Thanks,
Graeme
