### ISSUE TITLE
[BUG] [VSCode Extension]Embedding Tool Error

### ISSUE THREAD

**Issue by zanderjiang** [microsoft/promptflow#3416]
I get an error when I try to use the embedding tool via the extension:

"Can't find tool promptflow.tools.embedding.embedding
The package may not be installed in your Python environment."

But I have promptflow-tools installed.

**Environment Information**
promptflow: "1.12.0",
promptflow-azure: "1.12.0",
promptflow-core: "1.12.0",
promptflow-devkit: "1.12.0",
promptflow-tracing: "1.12.0"

python: "3.11.9"

**Comment by zanderjiang** [comment]
I've also installed:
promptflow-vectordb
promptflow-tools[azure]
promptflow-vectordb[azure]

but the problem persists.

**Comment by 0mza987** [comment]
Could you go to the conda env and use `pip list` and double check if the package is correctly installed?

Here is how to identify which conda env is being used by the extension:
![image](https://github.com/microsoft/promptflow/assets/2572521/1dc215a5-3845-412e-9fb0-a16859516b5a)

![image](https://github.com/microsoft/promptflow/assets/2572521/3c894dfb-a30f-4b3e-bb98-d71f15fce9c9)

**Comment by zanderjiang** [comment]
> Could you go to the conda env and use `pip list` and double check if the package `promptflow-tools` is correctly installed?
> 
> Here is how to identify which conda env is being used by the extension: ![image](https://private-user-images.githubusercontent.com/2572521/340170699-1dc215a5-3845-412e-9fb0-a16859516b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTcyNjUsIm5iZiI6MTcxODYxNjk2NSwicGF0aCI6Ii8yNTcyNTIxLzM0MDE3MDY5OS0xZGMyMTVhNS0zODQ1LTQxMmUtOWZiMC1hMTY4NTk1MTZiNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDkzNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQxODI0ODkxNDJhZGMxZTIwZmYwODRhN2Y4M2JhMDQ2YTU4ZTdjZjM0MmEzMzI4Nzc3MTI3NmI2NTJjMTMwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D0pas_WfcLm9yqMNEpQAZdA5tC1BPDa5zdDk5sPXX54)
> 
> ![image](https://private-user-images.githubusercontent.com/2572521/340172263-04aa1807-c4d1-4702-b591-d2d6989d87dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTcyNjUsIm5iZiI6MTcxODYxNjk2NSwicGF0aCI6Ii8yNTcyNTIxLzM0MDE3MjI2My0wNGFhMTgwNy1jNGQxLTQ3MDItYjU5MS1kMmQ2OTg5ZDg3ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDkzNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNhNjg2ZTE2MDIyZDcyNGM3MzBhYWQzZTQwNTc0N2M2ODdkOTcxM2VlOTFhMDc2YWJkZDk1MWY5YTg1NmQyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.os7534aWo73MQ49_gPVWxxw-cTZnliv9AGMbTemkuUM)



> Could you go to the conda env and use `pip list` and double check if the package `promptflow-tools` is correctly installed?
> 
> Here is how to identify which conda env is being used by the extension: ![image](https://private-user-images.githubusercontent.com/2572521/340170699-1dc215a5-3845-412e-9fb0-a16859516b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTcyNjUsIm5iZiI6MTcxODYxNjk2NSwicGF0aCI6Ii8yNTcyNTIxLzM0MDE3MDY5OS0xZGMyMTVhNS0zODQ1LTQxMmUtOWZiMC1hMTY4NTk1MTZiNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDkzNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQxODI0ODkxNDJhZGMxZTIwZmYwODRhN2Y4M2JhMDQ2YTU4ZTdjZjM0MmEzMzI4Nzc3MTI3NmI2NTJjMTMwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D0pas_WfcLm9yqMNEpQAZdA5tC1BPDa5zdDk5sPXX54)
> 
> ![image](https://private-user-images.githubusercontent.com/2572521/340172263-04aa1807-c4d1-4702-b591-d2d6989d87dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTcyNjUsIm5iZiI6MTcxODYxNjk2NSwicGF0aCI6Ii8yNTcyNTIxLzM0MDE3MjI2My0wNGFhMTgwNy1jNGQxLTQ3MDItYjU5MS1kMmQ2OTg5ZDg3ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDkzNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNhNjg2ZTE2MDIyZDcyNGM3MzBhYWQzZTQwNTc0N2M2ODdkOTcxM2VlOTFhMDc2YWJkZDk1MWY5YTg1NmQyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.os7534aWo73MQ49_gPVWxxw-cTZnliv9AGMbTemkuUM)

Hi thank you for the reply, yes promptflow-tools was correctly installed. It suddenly worked today, without me doing anything.
