### ISSUE TITLE
Set Trace Destination fails with Cosmos DB is disabled error

### ISSUE THREAD

**Issue by berndku** [microsoft/promptflow#3418]
**Describe the bug**
Set Trace Destination call against a CMK-enabled ML Workspace fails with error that Cosmos DB is disabled. 
For a CMK-enabled workspace the CosmosDB is in the managed resource-group in the customer subscription. 

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Run ```pf config set trace.destination=azureml://subscriptions/<subscriptionId>/resourceGroups/<resource-group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace-name>```
2. Retrieved error:
```
[2024-06-14 08:10:18 +0000][promptflow][ERROR] - The workspace Cosmos DB is disabled, please enable it first.
pf.config.set failed with UserErrorException: The workspace Cosmos DB is disabled, please enable it first.
```

**Expected behavior**
Trace Destination should be set correctly. 

**Running Information(please complete the following information):**
 - Promptflow Package Version:
 ```
{
  "promptflow": "1.12.0",
  "promptflow-azure": "1.12.0",
  "promptflow-core": "1.12.0",
  "promptflow-devkit": "1.12.0",
  "promptflow-tracing": "1.12.0"
}
```
 - Operating System: [Windows 11]
 - Python Version using 3.11.9

**Comment by zhengfeiwang** [comment]
Hi @berndku , thanks for reporting this. So far, CMK workspace is not supported for the trace Cosmos DB feature. According to your error, seems the error message is not clear for this - we will take a look on this.

So is it possible to avoid a CMK workspace for your scenario?

**Comment by berndku** [comment]
@zhengfeiwang : Unfortunately CMK workspace is a legal requirement on our side and we can´t avoid it. 
Yes, the error message is not clear and it is just a guess that CMK is causing this.

**Comment by zhengfeiwang** [comment]
Got it, sorry to hear that, we can use this issue to track the error message refinement work. As for supporting CMK, I recommend you to open a Feature Request issue to explicitly call out this.

**Comment by berndku** [comment]
I tried without CMK and there it is working. Closing and re-creating as feature request.
