### ISSUE TITLE
[BUG] Do now show warning messages from werkzeug

### ISSUE THREAD

**Issue by luigiw** [microsoft/promptflow#3419]
**Describe the bug**

Running `pf flow test ... --ui` starts local PFS. Command line prints out a bold warning message from werkzeug. The message is confusing and misleading. PF should consider dismiss the warning message.

![image](https://github.com/microsoft/promptflow/assets/1483379/26845743-b5b4-4f85-95a1-56577876f035)

**Comment by wangchao1230** [comment]
@luigiw This requires to install an WSGI container to disable the message, which means we need to add some dependency like gunicorn. I think we should not introduce this dependency just to avoid this warning.
