### ISSUE TITLE
I need to serve to 0.0.0.0

### ISSUE THREAD

**Issue by engrogerio** [microsoft/promptflow#3432]
I can not serve to host 0.0.0.0.

Is that possible to implement a easy way to change constant.PF_SERVICE_HOST to another value?
Today if you change _constant.PF_SERVICE_HOST, it will be overwritten to 127.0.0.1 before the server starts.

**Comment by YingChen1996** [comment]
@engrogerio ，Thanks for reporting the issue. 
May I double confirm the scenario you mentioned above is local prompt flow service (pf service start) or prompt flow serve (pf flow serve)?  And may I ask how do you change the PF_SERVICE_HOST, do you modify the corresponding source code?

**Comment by engrogerio** [comment]
My code starts the trace :

```
@trace
def chat(question: str = "What's the capital of France?") -> str:
    """Flow entry function."""

    if "OPENAI_API_KEY" not in os.environ and "AZURE_OPENAI_API_KEY" not in os.environ:
        # load environment variables from .env file
        load_dotenv()
    prompty = Prompty.load(source=BASE_DIR / "chat.prompty")
    # trigger a llm call with the prompty obj
    output = prompty(question=question)
    return output
```

I changed the PF_SERVICE_HOST like:
```
constants_file_path = os.path.abspath(promptflow.constants.__file__)
command = f'sudo chmod 755 {constants_file_path}'
exit_status = os.system(command)

search_and_replace(constants_file_path, 'PF_SERVICE_HOST = "127.0.0.1"', 'PF_SERVICE_HOST = "0.0.0.0"')
```

My scenario is: I am using promptflow on a Posit Connect deployed application.

**Comment by YingChen1996** [comment]
Hi, @engrogerio ,  you may need change your code to `os.path.abspath(promptflow._sdk._constants.__file__)` if you want to change PF_SERVICE_HOST in the source code. Btw,  we will support config host in the future.

**Comment by YingChen1996** [comment]
Add config pfs host feature and will release it in the next public version.

**Comment by engrogerio** [comment]
Hey, @YingChen1996. I want to be able to serve the /ui/traces page on 0.0.0.0 port 23333. Is that possible with this changes? Can you give a code example?
