### ISSUE TITLE
[Feature Request] Allow disabling tracing for large intermediate objects

### ISSUE THREAD

**Issue by jyeriton2** [microsoft/promptflow#3439]
**Is your feature request related to a problem? Please describe.**
Our flow involves a call to an model API that returns a very large dictionary in `json` format.
The whole flow, when implemented in pure python, takes around 5 seconds.
Owing to what we are suspecting is an internal copy mechanism, tracing causes the whole flow to take an additional 12 seconds.
 
**Describe the solution you'd like**
Allow tracing to be disabled for specific components, or for the whole flow.
 
**Describe alternatives you've considered**
We could always edit the internal promptflow code to disable tracing for our specific use case, but we'd prefer if this was possible through an exposed API.
 
**Additional context**
We've verified that the flow runs in the expected five seconds if we disable tracing by replacing the [relevant line](https://github.com/microsoft/promptflow/blob/main/src/promptflow-core/promptflow/_core/tool.py#L86) with a simple `new_f = func`.
The large return value is question comprises multiple representations of an input image. We are not able to significantly reduce the size of the dictionary due to restrictions in our development environment.

**Comment by zhengfeiwang** [comment]
@jyeriton2 thanks for reporting this. I understand your suspect is valid, as our traces have logic that serializes function inputs/outputs inside `_traced`. tagging and adding Heyi @thy09 , expert and owner of this area to take a look, maybe we do need some mechanism to disable this operation.

**Comment by thy09** [comment]
@jyeriton2 You may try  PF_DISABLE_TRACING  introduced in this PR: https://github.com/microsoft/promptflow/pull/3353/files.
Only serving scenario is confirmed, not sure whether it is your scenario.

Also it would be great if you can contribute a PR for us.

**Comment by jyeriton2** [comment]
@thy09 thank you for the suggestion. I try the method you suggested and my flow takes around 5 seconds !!

**Comment by FabianSchurig** [comment]
@jyeriton2 If you want to disable just some function you might consider using this [tracing_disabler.py](https://github.com/FabianSchurig/promptflow-tool-semantic-kernel/blob/main/promptflow_tool_semantic_kernel/tools/tracing_disabler.py)
