### ISSUE TITLE
[Feature Request] Official example for streaming PromptFlow using AutoGen

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#3443]
**Is your feature request related to a problem? Please describe.**
My company is currently using AutoGen.  We send a websocket request to an Azure web app and we get text streamed back in small chunks, around 3 characters.  This works fine for us.  We want to add promptflow.  Promptflow's streaming and AutoGen's streaming rely on completely different mechanisms.  Autogen uses websockets and Promptflow uses a generator with a "yield" statement.  I am not really sure how to integrate the two.

**Describe the solution you'd like**
An example showing simply and concisely how to create a flow that accepts a request, add a module containing a Python script which creates autogen agents and runs them, and then streams their output back to a frontend as the output is being generated.

**Describe alternatives you've considered**
I have considered just trying to stream back using autogen alone, and ignoring promptflow's streaming feature.

**Additional context**
Autogen has an example for working with Promptflow and Redis, but it appears that it only sends complete messages to Redis and not partial messages like I am hoping for.

**Comment by 0mza987** [comment]
Promptflow team currently does not have the bandwidth to integrate autogen's streaming with promptflow's built-in streaming feature.

Please feel free to try the workaround you have proposed above, and you're more than welcomed to contribute a sample to us if the proposed workaround actually works.

**Comment by tyler-suard-parker** [comment]
@0mza987 Hello Honglin.  I do not have time to integrate promptflow with our current streaming autogen implementation, so we won't be using promptflow in our current project.  Thank you for your help.
