### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Porkechebure** [microsoft/promptflow#3462]
All versions are the latest

Running pf serve

> 
> pf flow serve --source . --port 8082 --host localhost
> [2024-06-24 17:03:58,094][pfserving-app][INFO] - Static_folder: C:\Python311\Lib\site-packages\promptflow\_sdk\_serving\static
> [2024-06-24 17:03:58,096][pfserving-app][INFO] - Promptflow config: <promptflow._sdk._configuration.Configuration object at 0x0000028FF576F710>
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Python311\Lib\site-packages\promptflow\_cli\_pf\entry.py", line 162, in <module>
>     main()
>   File "C:\Python311\Lib\site-packages\promptflow\_cli\_pf\entry.py", line 158, in main
>     entry(command_args)
>   File "C:\Python311\Lib\site-packages\promptflow\_cli\_pf\entry.py", line 135, in entry
>     run_command(args)
>   File "C:\Python311\Lib\site-packages\promptflow\_cli\_pf\entry.py", line 85, in run_command
>     raise ex
>   File "C:\Python311\Lib\site-packages\promptflow\_cli\_pf\entry.py", line 57, in run_command
>     dispatch_flow_commands(args)
>   File "C:\Python311\Lib\site-packages\promptflow\_cli\_pf\_flow.py", line 76, in dispatch_flow_commands
>     serve_flow(args)
>   File "C:\Python311\Lib\site-packages\promptflow\_cli\_pf\_flow.py", line 507, in serve_flow
>     serve_flow_python(args, source)
>   File "C:\Python311\Lib\site-packages\promptflow\_cli\_pf\_flow.py", line 566, in serve_flow_python
>     app = create_app(
>           ^^^^^^^^^^^
>   File "C:\Python311\Lib\site-packages\promptflow\_sdk\_serving\app.py", line 200, in create_app
>     app.init(**kwargs)
>   File "C:\Python311\Lib\site-packages\promptflow\_sdk\_serving\app.py", line 45, in init
>     self.extension = ExtensionFactory.create_extension(logger, **kwargs)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\site-packages\promptflow\_sdk\_serving\extension\extension_factory.py", line 35, in create_extension
>     return DefaultAppExtension(logger=logger, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\site-packages\promptflow\_sdk\_serving\extension\default_extension.py", line 124, in __init__
>     self.connection_provider = pf_config.get_connection_provider()
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\site-packages\promptflow\_sdk\_configuration.py", line 172, in get_connection_provider
>     return self.resolve_connection_provider(provider, path=path)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\site-packages\promptflow\_sdk\_configuration.py", line 180, in resolve_connection_provider
>     return "azureml:" + cls._get_workspace_from_config(path=path)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\site-packages\promptflow\_sdk\_configuration.py", line 154, in _get_workspace_from_config
>     raise ConfigFileNotFound(
> promptflow._sdk._configuration.ConfigFileNotFound: We could not find config.json in: . or in its parent directories. Please provide the full path to the config file or ensure that config.json exists in the parent directories.

The damn thing doesn't work out of nowhere randomly
#3450 https://github.com/microsoft/assistant-pf-demo/issues/5

Same as here.

Also vs code extension for dag.yaml when doing "Build docker image" button produces nothing and no docker file.

FIX

**Comment by D-W-** [comment]
Seems like you configured connection provider to remote workspace but doesn't have a `config.json` for workspace info. Configure the connection provider back to local can fix your issue:

```
pf config set connection.provider=local
```

Reference here for more information: https://microsoft.github.io/promptflow/how-to-guides/set-promptflow-configs.html?highlight=connection+provider#local
