### ISSUE TITLE
[BUG] Difference in retrieved results between PromptFlow's index Lookup and AI Search Web

### ISSUE THREAD

**Issue by hyeonje-cho** [microsoft/promptflow#3463]
**Describe the bug**
There seems to be a discrepancy in the document results retrieved for the same query between Promptflow's index_lookup and AI search in Portal. The results from AI search appear to be more accurate. How can we ensure consistent results from both platforms?

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Setup Lookup index with AI search index in the promptflow 
2. Retrieve user query
3. Compare the results between promptflow and AI search web

**Expected behavior**
Same results from Promptflow's vector lookup and AI search web

**Screenshots**
AI Search Web result
![image](https://github.com/microsoft/promptflow/assets/166415789/9931c2d8-0420-43e8-af65-02596f9d3c74)

Promptflow result
![image](https://github.com/microsoft/promptflow/assets/166415789/46fb7afd-af58-4dca-948f-39ba27c8088c)
![image](https://github.com/microsoft/promptflow/assets/166415789/16872588-3588-4d3e-8758-609ce87780be)

**Running Information(please complete the following information):**
- Promptflow in ai.azure.com 
- 
**Additional context**

**Comment by D-W-** [comment]
Hi @dans-msft @Adarsh-Ramanathan , could you help to take a look of this issue? Thanks!
@hyeonje-cho , for issues when using AI Studio, you can follow this doc to file feedback: https://microsoft.github.io/promptflow/cloud/azureai/faq.html?highlight=faq#how-to-create-feedback-for-azure-portal-experience
