### ISSUE TITLE
[BUG] Unable to install LangChain > 0.2.0 with PromptFlow runtime

### ISSUE THREAD

**Issue by monuminu** [microsoft/promptflow#3474]
**Describe the bug**
Unable to install LangChain > 0.2.0 with PromptFlow runtime

**How To Reproduce the bug**
pip install langchain==0.25.0

**Expected behavior**
It should install

**Comment by brynn-code** [comment]
Hi, which error were you met when installing langchain? The langchain < 0.2.0 was limited by rag tool like vector index search, if flow was not using those tools, langchain > 0.2.0 could work even if pip warning shows as promptflow itself not depends on langchain.

**Comment by brynn-code** [comment]
Azure version related issue, close this as we have tracked the problem reported by email thread.
