### ISSUE TITLE
[Feature Request] Run Flow as Function With Variants

### ISSUE THREAD

**Issue by sashokbg** [microsoft/promptflow#3476]
**Is your feature request related to a problem? Please describe.**
I would like to be able to load a flow as a function with 'load_flow' and specify node variants within it.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Probably use the run function, but the API looks harder to use and less optimized ?

**Additional context**
N/A

**Comment by D-W-** [comment]
Hi @sashokbg , currently it's not supported to directly pass variant info in `load_flow` API. But you can set variant info after load flow as function, here's sample code:

```python
from promptflow.entities import FlowContext

flow_func = load_flow(path/to/flow)
flow_func.context = FlowContext(
    variant="${node_name.variant_id}",
)

flow_func(params)
```
