### ISSUE TITLE
[Contribution Request] Correcting some small English grammar mistakes

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#3490]
**Is your contribution request related to a problem? Please describe.**
English grammar corrections related to this PR:  https://github.com/microsoft/promptflow/pull/3489

**Detail the functionality and value.**
These are small changes, but they make a world of difference in how your software is perceived by English speakers.

**Comment by 0mza987** [comment]
Thank you for your contribution! This is highly valuable for our samples/docs, we have merged the pr and look forward to more of them in the future.
