### ISSUE TITLE
[BUG] [VSCode Extension] Not able to import modules outside of the flow directory

### ISSUE THREAD

**Issue by MingStar** [microsoft/promptflow#3495]
**Describe the bug**
I have 2 flows in my project, both of them need to import project shared code (the project module is `lib`) outside the flow working directory.

When I do that, the VS code extension always failed to load the Python nodes, with this error message  `(ModuleNotFoundError) No module named 'lib'`

Trying to set PYTHONPATH to the project workspace folder after clicking "Regenerate with advanced options" in the Python node does not seem to have effects.

This issue is similar to https://github.com/microsoft/promptflow/issues/3209

**How To Reproduce the bug**
1. set up the project like this:

```
lib/
flow1/
flow2/
```

2. create a Python node in one of the flows, which does `from lib import ...`

3. execute the flow, the ModuleNotFoundError will appear.

**Environment Information**
 - Promptflow Package Version using `pf -v`: 
 {
  "promptflow": "1.12.0",
  "promptflow-core": "1.12.0",
  "promptflow-devkit": "1.12.0",
  "promptflow-tracing": "1.12.0"
}
 - Operating System: MacOS
 - Python Version: 3.11
 - Prompt Flow extension version: 1.20.0

**Comment by simon-v-swyftx** [comment]
I'm not sure if it's just relating to the extension. I've attempted to add in a few dependencies in the `requirements.txt` file and manually uploaded the flow to Azure ML, but the compute session does not respect the requirements file, and when I go to deploy, it fails with `No module named XXX`

**Comment by D-W-** [comment]
@simon-v-swyftx , this is not related to extension. For Azure portal issue, feel free to [create a feedback ](https://microsoft.github.io/promptflow/cloud/azureai/faq.html#how-to-create-feedback-for-azure-portal-experience) for it, when filing feedback, please also attach related logs. For your case we'll need the following log
![image](https://github.com/microsoft/promptflow/assets/7776147/fc24b92e-18a0-4586-a155-f424b1d8a3b5)

**Comment by D-W-** [comment]
@MingStar let's track the issue in a central place, I've provided a workaround in #3209 , please check if it can help with your case.

**Comment by MingStar** [comment]
@D-W- apologies for the late reply. 

The issue is really with the VS Code extension, I think it assumes the flow file is called `flow.dag.yaml`, and separate flow files have to be in different sub folders. When I refactor the code according to your workarounds, the PromptFlow VS Code extension does not pick up nor display any flows.

**Comment by D-W-** [comment]
Hi @MingStar , you mentioned you added your working directory to `PYTHONPATH`.
Could you run `python -c "import sys; print('\n'.join(sys.path))"` in command line to check if the path was added? 
If not, you probably need to restart the session to make it take effect.

**Comment by MingStar** [comment]
@D-W- I did try to add the project directory to custom `PYTHONPATH` after clicking the `Regenerate with advanced options` button in the PF VSC extension, however, it seems `PYTHONPATH` was not being set properly.

Adding `PYTHONPATH=<project_dict>` **manually** in front of the generated `pfutil.py tool -f...` command in the command line returned no errors.

that got me thinking it could be a bug in the VSC extension preventing it from setting the custom `PYTHONPATH` correctly.

**Comment by MingStar** [comment]
and maybe the source code for PF VSC extension should be open sourced (as mentioned in https://github.com/microsoft/promptflow/discussions/360, it is not), so that we can all take a look at how the full `pfutil.py tool` command is constructed from the VSC extension

**Comment by MingStar** [comment]
Hi, any updates on this?

FYI, this prevents me from promoting PF further to my organisation, as developing with just one flow in a project with VSC is not realistic with many of our use cases.
