### ISSUE TITLE
Lisence issue for the dependency on docutils(GPL 3.0)

### ISSUE THREAD

**Issue by Siu-Keung** [microsoft/promptflow#3513]
Hey guys,

Our organization are going to use promptflow library in our production environment but get into trouble with a license issue. 

Our license review team shares their concerns on the license terms of promptflow, which it declares itself as **MIT** license but meanwhile it introduces a third-party library **docutils** with part of its code under **GPLv3**. This license is disallowed by our organization and in terms of its copyleft nature, **promptflow** should be under **GPLv3** too.

Unfortunately, I am not an expert in the domain of law and would like to seek help from all of you here to clarify if our license review team's understanding is correct? It's really a hard decision for us to give up promptflow at this moment coz we've spent time on it for months.

FYI the license terms of **docutils** library: https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/COPYING.txt#l144

**Comment by wangchao1230** [comment]
+ @lumoslnt who introduce the dep in this [PR](https://github.com/microsoft/promptflow/pull/1270)

**Comment by lumoslnt** [comment]
Hi @Siu-Keung, thanks for raising the problem. We inadvertently introduced the docutils package without thoroughly reviewing its licensing implications. We will remove the dependency on docutils and will seek alternative solutions.

**Comment by lumoslnt** [comment]
@Siu-Keung, are you eager to use promptflow in your production environment? We may be able to remove the dependency within the month.

**Comment by Siu-Keung** [comment]
Hi @lumoslnt, thanks for your feedbacks. We are still under non-prod develoment at this moment. Our production is planned in **Sept** this year but we might need to test the E2E integration with promptflow in advance. It will greatly facilitate our subsequent production development if the dependency issue can be settled down by this month. Thanks a lot.
