### ISSUE TITLE
[BUG] Running evaluate from promptflow.evals.evaluate  and setting  trace.destination="none" or "local" causes evaluations to not be available

### ISSUE THREAD

**Issue by pragmatical** [microsoft/promptflow#3535]
**Describe the bug**
I set trace.destination to either none or local as described in docs:
https://microsoft.github.io/promptflow/reference/pf-command-reference.html#id36
After doing this when I run evaluate it breaks at:
Traceback (most recent call last):
  File "/Users/somepath/submit_direct_search_eval.py", line 72, in <module>

Because it is looking for an azureml url - error is:
ValueError: Malformed trace provider string, expected azureml://subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>, got none

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. set trace.destination to "local" or "none"
2. Run evaluate

**Expected behavior**
Evaluations should run and results should be generated and displayed locally 

**Workaround**
Was able to get the run to work by removing the trace node from pf.yaml altogether

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 
     "promptflow": "1.13.0",
     "promptflow-azure": "1.13.0",
     "promptflow-core": "1.13.0",
     "promptflow-devkit": "1.13.0",
     "promptflow-evals": "0.3.1",
     "promptflow-tracing": "1.13.0"
 - Operating System: MacOs
 - Python Version using `python --version`: [e.g. python==3.12]

**Additional context**

**Comment by luigiw** [comment]
@pragmatical , can you share the full stack trace and evaluate() function code?
