### ISSUE TITLE
[BUG] Flow is not enabled

### ISSUE THREAD

**Issue by zyw400** [microsoft/promptflow#3543]
**Describe the bug**
Dear team, I created the flow following the instruction (https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-enable-streaming-mode?view=azureml-api-2) and set the chat module as the last one without any dependency. And I deployed the flow as an endpoint. However, the output still doesn't support streaming mode. And the returned content_type is always application/json as opposed to "text/event-stream".

**Expected behavior**

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/33538664/60cc40ad-f7cc-40e2-b502-f78907d65485)

You can see that the returned output include an "iterator" however, the logs also say stream is not enabled. I wonder if there is extra step needed to enable streaming mode. 

**Running Information(please complete the following information):**
- promptflow (1.12.0)
- promptflow-tools (1.5.0rc11)

 - Operating System: 2024-07-01T22:56:17 base: mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:latest
 - Python Version using `python --version`: python==3.9

**Additional context**

**Comment by zyw400** [comment]
Find the issue. The output of 'chat_output' that should be streamed at the deployment time, is not added to the "PROMPTFLOW_INCLUDED_FIELDS", after adding that, it can stream.

        environment_variables={
            "PRT_CONFIG_OVERRIDE": f"{config_string}",
            "PROMPTFLOW_RUN_MODE": "serving",
            "PROMPTFLOW_RESPONSE_INCLUDED_FIELDS": '[\"answer\", \"retrieved_icms\", \"retrieved_tsgs\", \"current_icm\", \"agent_output\", \"plugin_data\", \"executed_plugins_before_chat\", \"executed_plugins_after_chat\", \"base64_images\", \"plugin_executor_before_chat_output_edited_question\", \"plugin_executor_before_chat_output_plugin_data\", \"plugin_executor_before_chat_output_execute_main_chat\", \"plugin_executor_before_chat_output_chat_output_if_skip_main_chat\", \"format_default_plugins_output_current_icm\", \"format_default_plugins_output_retrieved_icms\", \"format_default_plugins_output_retrieved_tsgs\", \"plugin_executor_before_chat_output_executed_plugins\", \"chat_output\"]'
        }

**Comment by ltadjou** [comment]
Hi @zyw400,
I have the same error as you regarding streaming, I would like to know where do we specify these environment variables.

**Comment by zyw400** [comment]
![image](https://github.com/user-attachments/assets/cbac1e64-a487-46b9-92e4-2b2ffca74b99)
Hi @ltadjou , I added those in this step.

**Comment by ltadjou** [comment]
Thanks @zyw400 ,

I deployed using docker and I inserted those variable in my .env files.
