### ISSUE TITLE
[BUG] Run/debug single node doesn't work with the chat-with-pdf example

### ISSUE THREAD

**Issue by tcycherry** [microsoft/promptflow#355]
**Describe the bug**
Run/debug single node doesn't work with the chat-with-pdf example, since it depends on environment variables that was setup in the setup_env step.

**How To Reproduce the bug**
It's consistent repro:
1. Open the [chat-with-pdf](https://github.com/microsoft/promptflow/tree/main/examples/flows/chat/chat-with-pdf) example mentioned in the [e2e tutorial](https://github.com/microsoft/promptflow/blob/main/examples/tutorials/e2e-development/chat-with-pdf.md) with the vscode extension
2. Follow the tutorial to run the flow successfully
3. Then try to run a single node, which will fail by complaining a missing environment variable etc.

**Expected behavior**
Single node run/debug can work. I believe this requires some redesign of the sample but would be nice to leverage the single node debug capability.

**Screenshots**
![CleanShot 2023-09-09 at 12 52 58@2x](https://github.com/microsoft/promptflow/assets/75208397/30e34a97-92cf-4a27-8f49-8acdaed59756)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b5 
 - Operating System: macOS 13.5
 - Python Version using `python --version`: Python 3.9.17
 - VS code extension: 1.0.7

**Additional context**

**Comment by henry-zeng** [comment]
thanks for the suggestion, the time when you run the whole flow or do bulk test, the setup_env step  will set the environment variable for you in the current python process, while when you just run the single node, the env variable is not set, so the step will fail,  you can either set the open ai key to your system environment variable, and run the single step again.

we have other samples to use the OpenAI connection directly in the step which required OAI key, then you can run that node direclty.
