### ISSUE TITLE
[BUG] Not able to select embedding api in llm node

### ISSUE THREAD

**Issue by Vivihung** [microsoft/promptflow#357]
**Describe the bug**
Not able to select embedding api in llm node. Can repro with both AOAI and OAI connection.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Add an llm node in AML Studio.
2. Select any AOAI or OAI connection with embedding deployment.
3. Click on the Api dropdown. Only see "chat" and "completion"

**Expected behavior**
See embedding option in the dropdown.

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/4814277/e7dc142f-cea1-46a4-9383-b90116a3b7cf)

**Running Information(please complete the following information):**
You don't need PF CLI or the code-first experience to repro the issue.
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**
- Update or recreate the connection doesn't solve the issue.

**Comment by ttthree** [comment]
Seems to be the portal version in AzureML - @Vivihung try this embedding tool for embedding. Embedding was moved out of LLM tool.
![CleanShot 2023-09-09 at 17 49 03@2x](https://github.com/microsoft/promptflow/assets/18907/dd2ec5f3-f84f-43c0-8bc5-3c2a1f0d712e)

**Comment by Vivihung** [comment]
@ttthree, thanks! Confirmed using the Embedding node resolved the issue. Feel free to close this item.

On the other hand, it will be helpful if the platform has better forward compatibilities. For instance, when a node is changed (or moved out as a new node), the UI at least can display some warnings to guide users to migrate. Based on my personal experience, if any of the nodes (or even connection) are updated on the platform level, my flow failed with weird errors (e.g., asking Azure OpenAI model parameters when my connection is Open AI) and were hard to debug/fix.
