### ISSUE TITLE
[BUG] - Lookup task in Azure AI Studio fails with ClientAuthenticationError: Unexpected content type "text/plain; charset=utf-8" Content: 404 page not found

### ISSUE THREAD

**Issue by graemefoster** [microsoft/promptflow#3577]
**Describe the bug**
Running the lookup step using an AOAI connection that uses Entra Auth fails with "ClientAuthenticationError: Unexpected content type "text/plain; charset=utf-8" Content: 404 page not found"

The error doesn't occur when I switch to an AOAI connection using the Api Key.

3 Entra Identities (my personal user, the UAMI attached to the hub, and the System Assigned Identity for the project) all have Open AI User role against the AOAI service.

I can use the Embeddings step / execute a chat completions task from the same Prompt Flow without issues when using an AOAI connection with Entra auth.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create an Index in your AI Studio that uses an AOAI connection with Entra
2. Create a Prompt Flow
3. Create a lookup step, and reference the Index you just created
4. Run the PromptFlow. The Lookup step fails with above error.

**Expected behavior**
It should work

**Running Information (please complete the following information):**
Using Prompt Flow in Azure AI Studio

**Comment by 0mza987** [comment]
Hi @graemefoster,

For azure ai studio issue, please refer to [Frequency asked questions (FAQ) — Prompt flow documentation](https://microsoft.github.io/promptflow/cloud/azureai/faq.html) to create feedback there, thanks.

**Comment by graemefoster** [comment]
@0mza987 is the Lookup task not part of PromptFlow? From what I can tell, that task doesn't work when the AOAI connection is using Entra auth.

**Comment by aageorge** [comment]
Also running into the same issue after migrating off of API keys. Its definitively an issue with the vector DB tool, calling with a custom tool works.

**Comment by graemefoster** [comment]
@aageorge I found a way around this - FWIW it is an AI Studio issue and it's a bug in the version of promptflow_vectordb it uses.

I fixed it by explicitly changing the requirements.txt file to say
promptflow-vectordb = 2.0.12

I also was forced to add another requirement - IIRC it was related to a cosmos db import.

Hope that helps.
