### ISSUE TITLE
[BUG] PromptFlow VS Code extension cannot use CustomStrongTypeConnection in tools.

### ISSUE THREAD

**Issue by pitt-liang** [microsoft/promptflow#3578]
**Describe the bug**

VS Code extension cannot use CustomStrongTypeConnection in tools.

- CustomStrongTypeConnection is shown as not available in the extension.
- The Flow Visual Editor does not support selecting CustomStrongTypeConnection.

**How To Reproduce the bug**

Follow the official custom strong type connection example with the PromptFlow VS Code extension.

https://github.com/microsoft/promptflow/blob/main/examples/tools/use-cases/custom-strong-type-connection-package-tool-showcase/README.md

**Expected behavior**

CustomStrongTypeConnection should be available for selection in the Flow Visual Editor.

**Screenshots**

![image](https://github.com/user-attachments/assets/8b547897-16d2-46fc-a9f1-55deebf22b38)

**Running Information(please complete the following information):**

 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]

 ```plain

 $ pf -v


{
  "promptflow": "1.13.0",
  "promptflow-azure": "1.13.0",
  "promptflow-core": "1.13.0",
  "promptflow-devkit": "1.13.0",
  "promptflow-tracing": "1.13.0"
}

Executable '/opt/miniconda3/envs/pf-py39-v3/bin/python'
Python (Darwin) 3.9.19 (main, May  6 2024, 14:39:30)

```

 - Operating System: [e.g. Ubuntu 20.04, Windows 11]

```plain

$ sw_vers
ProductName:		macOS
ProductVersion:		14.4.1
BuildVersion:		23E224

```

 - Python Version using `python --version`: [e.g. python==3.10.12]

```plain
$ python --version
Python 3.9.19
```

- PromtpFlow VS Code Extension: v1.20.0
![image](https://github.com/user-attachments/assets/47a3188a-67d0-482d-b413-7de0db1362dd)

**Comment by Joouis** [comment]
@pitt-liang Thanks for reporting the regression! Please update the extension to latest `v1.20.1` to get the bug fix.
