### ISSUE TITLE
[BUG] Doesn't see "Visual editor" option when open flow.dag.yaml in VSCode

### ISSUE THREAD

**Issue by Vivihung** [microsoft/promptflow#358]
**Describe the bug**
According to the [documentation](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/planners/evaluate-and-deploy-planners/create-a-prompt-flow-with-semantic-kernel?branch=matthew-prompt-flow#visualize-the-flow-in-vs-code), there should be a "Visual editor" option when open flow.dag.yaml file in VSCode. However, I didn't see "Visual editor" in my VSCode.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Follow [this](https://review.learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/planners/evaluate-and-deploy-planners/create-a-prompt-flow-with-semantic-kernel?branch=matthew-prompt-flow#visualize-the-flow-in-vs-code) documentation to create an init flow via `pf`.
2. Once the project is created, open the `flow.dag.yaml` file in VSCode.
3. Didn't see any "Visual editor" option in the editor.

**Expected behavior**
See "Visual editor" on the top-left corner of the file editor.

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/4814277/bf018e3e-520e-4b4d-9f45-06da6863b20f)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b5
 - Operating System: Windows 11
 - Python Version using `python --version`: Python 3.11.4
 - VSCode version: 1.82.0

**Additional context**
Wonder if it's virtual env related.
- Prompt flow VSCode extension is installed.
- I use a virtual environment with VSCode workspace. promptflow and promptflow-tools are installed in the virtual env.
- I can see the Prompt flow VSCode extension complains about missing promptflow and promptflow-tools. Maybe the extension does not support virtual env?!
![image](https://github.com/microsoft/promptflow/assets/4814277/d1b6ec7f-00e4-4bdd-ac81-89b3619d44ec)

**Comment by ttthree** [comment]
@Vivihung can you share the full screen of the "Install dependencies" page?
I've tried virtual env and it worked for me so far.

![CleanShot 2023-09-09 at 17 46 49@2x](https://github.com/microsoft/promptflow/assets/18907/ac8167ce-fb78-43f6-a08a-fb3c89560d6c)

**Comment by henry-zeng** [comment]
@Vivihung  if you just update the promptflow SDK, you may need to **reload your VSCode window,** and then check the install dependecy again to see whether you venv can pickup the latest library, and then you cango to flow.dag.yaml to select the venv you have pf installed, which you should be able to see the visual editor

**Comment by Vivihung** [comment]
Thanks for your suggestions. I can see the visual editor on one of my machine (not the repro one though). Will spend a bit more time with the repro machine and share findings here.

**Comment by Vivihung** [comment]
Update on my investigation - The problem seems related to the VSCode Python extension. The reason the PF dependencies don't get detected correctly is due to the Python interpreter wasn't set to the right virtual env, and cannot be updated.

An easy way to identify this issue is to open a python file in VSCode. If the Python interpreter in the VSCode status toolbar (in bottom of the VSCode window) shows warning even selecting the right env python from the command bar, then you hit this issue.

My way to resolve it is
1. Uninstall all VSCode extensions that depends on the Python extension.
2. Uninstall Python extension.
3. Close VSCode.
4. Clean up VSCode caches [[ref](https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai)].
5. Reinstall VSCode Python extension and the Prompt flow extension.
6. Open the code in VSCode.
