### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JalajMadaan** [microsoft/promptflow#3588]
**Describe the bug**
Not able to start the runtime in promptflow interface - it is giving error after long run

![Screenshot 2024-07-26 135732](https://github.com/user-attachments/assets/44ca3251-ab4d-4822-ab97-377684cd81be)

**Comment by 0mza987** [comment]
Hi @JalajMadaan ,

For azure portal related issues, please refer to [Frequency asked questions (FAQ) — Prompt flow documentation](https://microsoft.github.io/promptflow/cloud/azureai/faq.html#how-to-create-feedback-for-azure-portal-experience) to give a feedback there, thanks.
