### ISSUE TITLE
[DOC] Promptflow concepts page would be better with definitions before details

### ISSUE THREAD

**Issue by BurtHarris** [microsoft/promptflow#3589]
**Describe the bug**
Learning promptflow, I start with concepts.   Since things like flows, tools, connections, etc. are promptflow specific terms, 
I think it would be good to provide some definitions in the concepts/index.md.

I'd be happy to submit some PRs to do this, as I learn...

**Additional context**
Hello team.   I'm a retired Microsoft dev.   I worked on Microsoft's first NLP application, Microsoft English Query, which shipped in SQL Server 2000.

Documentation only bug.

**Comment by 0mza987** [comment]
Hi @BurtHarris 

Thanks for your feedback, you are very welcome to submit a PR to add some descriptions in `concept/index.md`, please link the pr once you finished, we will review and merge it.

Thanks very much!
