### ISSUE TITLE
[Contribution Request] Tutorial on Continuous Monitoring using ML Pipelines

### ISSUE THREAD

**Issue by loubigard** [microsoft/promptflow#3602]
Hi team, I would like to propose a tutorial about creating a pipeline for continuous monitoring.
It describes an advanced use case of [running flows in ML pipelines](https://github.com/microsoft/promptflow/tree/main/examples/tutorials/run-flow-with-pipeline).
Continuous monitoring is necessary to maintain the quality, performance and efficiency of Generative AI applications.  
These factors directly impact the user experience and operational costs.  

It will run evaluations on a basic chatbot flow, then aggregate the results to export and visualize the metrics.
This contribution is a sharing from ISE Dragon Crew's CodeWith engagement.
PR: #3644

**Comment by D-W-** [comment]
@loubigard thanks for the contribution! For your scenario, we recommend putting under [integration folder](https://github.com/microsoft/promptflow/tree/main/examples/flows/integrations). Let's discuss more in the PR.

**Comment by D-W-** [comment]
Merged in this PR: https://github.com/microsoft/promptflow/pull/3644
