### ISSUE TITLE
[BUG] unable to run basic-chat sample

### ISSUE THREAD

**Issue by metang** [microsoft/promptflow#361]
**Describe the bug**
install 0.1.0b5. Run basic chat test and failed with error message Exception: OpenAI API hits InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. follow the quick start guide
2. create new environment
3. install pf packages
4. create pf connections
5. clone promptlfow repo
run basic chat: python.exe -m promptflow._cli._pf.entry flow test --flow d:\code\pftest\promptflow\examples\flows\chat\basic-chat --interactive
===================================
Welcome to chat flow, default_flow.
Press Enter to send your message.
You can quit with ctrl+C.
===================================
User: test

Flow test failed with UserErrorException: Exception: OpenAI API hits InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'> [Error reference: https://platform.openai.com/docs/guides/error-codes/api-errors]

**Expected behavior**
Able to run the flow

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

pf: 0.1.0b5
Windows 10
Python 3.11.4

**Additional context**

**Comment by wangchao1230** [comment]
@metang Could you do a pip list and share your other packages version?
