### ISSUE TITLE
[BUG] Transient error INTERNAL SERVER ERROR encountered while exporting span batch, retrying in 2s

### ISSUE THREAD

**Issue by huqianghui** [microsoft/promptflow#3617]
**Describe the bug**
I tried to intergrate promptflow with graphRAG.
When I try to call local search API and global search API, then the warning message appears. 
And some azure openAI call does not appear in the trace portal.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. start_trace method，
2. call  graphRAG  local search API

**Expected behavior**
No warnning message.
And all of LLM call trace logs are in the portal.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]

(.venv) huqianghui@./graph-demo04 ➜  pf -v
{
  "promptflow": "1.14.0",
  "promptflow-azure": "1.14.0",
  "promptflow-core": "1.14.0",
  "promptflow-devkit": "1.14.0",
  "promptflow-tracing": "1.14.0"
}

Executable '/Users/huqianghui/Downloads/graph-demo04/.venv/bin/python'

 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
MacOS(14.5 (23F79))

 - Python Version using `python --version`: [e.g. python==3.10.12]
Python (Darwin) 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)]

**Additional context**

**Comment by huqianghui** [comment]
> there might be some erros during collecting traces in prompt flow service side, please help share related service logs, you shall find the logs file via CLI command `pf service status`.

(.venv) huqianghui@./graph-demo05 ➜  pf service status
{
  "create_time": "2024-08-05 15:18:40.988907",
  "log_file": "/Users/huqianghui/.promptflow/pfs/bin_cf18ebe74bdb6cb030b91b9164c80b3e600a8b93_pfs.log",
  "port": 23334,
  "service_host": "127.0.0.1",
  "uptime": "0:05:46.105642",
  "version": "1.14.0"
}

**Comment by huqianghui** [comment]
The reproduce steps as below:

I have intergrate the prompt-flow with graphRAG.  
and publish the python package:  graphrag-with-trace

You can follow the document :
https://microsoft.github.io/graphrag/posts/get_started/

**Comment by zhengfeiwang** [comment]
i just followed the get started doc and tried global search command, and somehow re-produce this; however, everything works fine for the first time, and it started to fail since the 2nd time, with the same errors, this makes me find out one wired thing: all **traces in global search are using one trace id and span id**, which results in the error in collector side.

our trace expert Qianlin is on his vacation this week; but in prompt flow, we use standard OTel SDK to generate traces, and it works very well in the past half year; so i guess there are some unknown magic inside GraphRAG that may change some behaviors in OTel.

from my perspective, there should be more investigation from GraphRAG and/or OTel side first.

**Comment by huqianghui** [comment]
@zhengfeiwang , thanks for your response. 
I just config the trace the methon run_global_search  in /Users/huqianghui/Downloads/git_temp/graphrag/graphrag/query/cli.py
 as below:

@trace
def run_global_search(
    config_dir: str | None,
    data_dir: str | None,
    root_dir: str | None,
    community_level: int,
    response_type: str,
    query: str,
):
    """Run a global search with the given query."""

    collection = "run_global_search_" + datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    start_trace(collection=collection)
    
    Is that fine or I need to change something.

**Comment by HRNPH** [comment]
it there any updated on this? as I am encountered the same issue.
