### ISSUE TITLE
[BUG]some LLM call trace log missing

### ISSUE THREAD

**Issue by huqianghui** [microsoft/promptflow#3619]
**Describe the bug**
When I tried to integrate GraphRAG with prompt-flow and you can install it by "pip install graphrag-with-trace". I found there is no LLM call trace log in local search. But I found LLM call log in the console log.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. follow the quick start step: https://microsoft.github.io/graphrag/posts/get_started/
2. just change the first step from "pip install graphrag" to "pip install graphrag-with-trace".
3. After running local search step,  check the trace log.

**Expected behavior**
The LLM calling trace log in the UI page.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
{
  "create_time": "2024-08-05 15:18:40.988907",
  "log_file": "/Users/huqianghui/.promptflow/pfs/bin_cf18ebe74bdb6cb030b91b9164c80b3e600a8b93_pfs.log",
  "port": 23334,
  "service_host": "127.0.0.1",
  "uptime": "0:05:46.105642",
  "version": "1.14.0"
} 

 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
MacOS 

 - Python Version using `python --version`: [e.g. python==3.10.12]

python3.11

**Additional context**

**Comment by zhengfeiwang** [comment]
i just followed the get started doc and tried local search, hitting error: `FileNotFoundError: Table entity_description_embeddings does not exist.Please first call db.create_table(entity_description_embeddings, data)`, seems there is one known issue investigated: https://github.com/microsoft/graphrag/issues/813, will hold and wait for them investigation.

**Comment by huqianghui** [comment]
@zhengfeiwang , thanks for the reponse. But I think they are different issue. Once the issue has been fixed, I will try again and update it.
