### ISSUE TITLE
[BUG] [VSCode Extension] Unexpected token error, Category Info ParentContainsErrorRecordException

### ISSUE THREAD

**Issue by craig1812** [microsoft/promptflow#3642]
**Describe the bug**
A clear and concise description of the bug.

I'm attempting to add Azure OpenAI Connection. When I select "Create Connection" in the new_AzureOpenAI_connection.yaml file after updating the applicable variables, I receive the below issue:

Unexpected token 'c:\Users\<username>\.vscode\extensions\prompt-flow.prompt-flow-1.20.1\pfutil\pfutil.py' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

Reviewing the pfutil.py file, I notice there is a warning indicating that "Import "_pf_vsc_main" could not be resolved (Pylance(reportMissingImports)

When reviewing all py scripts in pfutil folder, I notice the same warning occurs as above. 

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:

1. Setup VS Code in local development environment, install Prompt flow for VS Code extension
2. Install dependencies in working environment (virtual): promptflow, promptflow-tools, promptflow-core, promptflow-azure, promptflow-devkit, promptflow-tracing
3. Create new Azure OpenAI connection in Promptflow extension's "CONNECTIONS" pane
4. Select "Create connection" in new_AzureOpenAI_connection.yaml file
 

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.

![image](https://github.com/user-attachments/assets/44359a7c-3d89-4bcd-8757-2db51e8e3473)

3. Please provide other snapshots about the key steps to repro the issue.

Issue when selecting "Create connection" in new_AzureOpenAI_connection.yaml file:
![image](https://github.com/user-attachments/assets/b41151f1-4230-462d-a5d2-98ffb73f7073)

Warning:
![image](https://github.com/user-attachments/assets/df567b83-6357-4c96-b46c-a031f163d004)

Warning for _pf_vsc_custom_connection_config.py
![image](https://github.com/user-attachments/assets/216d3931-9616-4618-a33d-a75a76a24748)

**Environment Information**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
![image](https://github.com/user-attachments/assets/5c69e403-0aaf-4e70-8c63-5bbe6370dffe)

 - Operating System: Microsoft Windows 10 Enterprise
 - Python Version using `python --version`: Python 3.12.3
 - VS Code version: 1.92.1
 - Prompt Flow extension version: v1.20.1

**Additional context**

- Execution policy = RemoteSigned
- Keyring installed in virtual environment via pip
- Python PATH environment variable is configured 
![image](https://github.com/user-attachments/assets/8d29f49f-2024-4e33-a937-9941a3930db7)

I'm not entirely sure whether this issue relates to the extension, but additional guidance would be useful. When I execute pfutil.py through my virtual environment, no issues are present. However, when I the extension executes pfutil.py when I create a new connection, the issue is present.

**Comment by Useraccount1o1** [comment]
Hi Team, I am also getting same issue for open ai connections type while i do in local, can anyone help me out
