### ISSUE TITLE
[Feature Request] Ability to Add Custom Dimensions to Deployed Endpoint App Insights

### ISSUE THREAD

**Issue by adampolak-vertex** [microsoft/promptflow#3646]
**Is your feature request related to a problem? Please describe.**
Currently a deployed PromptFlow endpoint can have app insights enabled. This allows for seeing performance. Currently it is not possible to add custom dimensions to what PromptFlow creates.

![image](https://github.com/user-attachments/assets/9ae4a6d2-f41d-420e-bf42-ac1db89a8dbb)

**Describe the solution you'd like**
I would like a way to add to the custom dimensions easily in PromptFlow. So for each node I can add custom dimensions to what is already being created.

**Describe alternatives you've considered**
There does not seem to be a way to enhance the app insights data.

**Additional context**

**Comment by wxpjimmy** [comment]
You can use the open-telemetry API/SDK to get the current span and add your own attributes to the span easily.

**Comment by adampolak-vertex** [comment]
@wxpjimmy  I have implemented that code in the promptflow and the custom dimensions never appear in app insights. It does not seem to default to whatever the current deployed endpoint is generating as app insights events.
