### ISSUE TITLE
[BUG] promptflow-eval evaluate function changes current working directory

### ISSUE THREAD

**Issue by cedricvidal** [microsoft/promptflow#3650]
**Describe the bug**
The `evaluate` function changes current working directory

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Note CWD
2. Run `evaluate`
3. CWD is now a temporary folder set by pf

**Expected behavior**
CWD after running the `evaluate` function should be the same as before running it.

**Running Information(please complete the following information):**

```
$ pf -v
{
  "promptflow": null,
  "promptflow-azure": "1.14.0",
  "promptflow-core": "1.14.0",
  "promptflow-devkit": "1.14.0",
  "promptflow-evals": "0.3.1",
  "promptflow-tracing": "1.14.0"
}
```

 - Operating System: DevContainer 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

 - Python Version

```
$ python --version
Python 3.12.4
```

**Additional context**

**Comment by krisbock** [comment]
Experienced the same issue.  Impacts both data and output_path if using relative path names.  Will break when using multiple evaluators.
