### ISSUE TITLE
[Feature Request] Release next version of promptflow-tools

### ISSUE THREAD

**Issue by bostdiek** [microsoft/promptflow#3657]
**Is your feature request related to a problem? Please describe.**
We are working with a customer on using the DAG based flows. On GitHub, I see that there have been updates to the promptflow-tools directory that work with the OpenAI tool calling, both in the LLM tool as well as the Jinga processing. However, the latest release on pypi does not have that.

**Describe the solution you'd like**
Release the package.

**Describe alternatives you've considered**
Writing custom tools ourselves with massive copy and paste from promptflow repository

**Additional context**

**Comment by chjinche** [comment]
Hi @bostdiek Thanks for asking. 

The release timeline is in discussion and we will keep you informed once finalized. Sorry for inconvenience.

Alternatively, you could install the latest dev version by `pip install git+https://github.com/microsoft/promptflow.git#subdirectory=src/promptflow-tools`, which may reduce your massive copy-n-paste work.

**Comment by bostdiek** [comment]
Thanks @chjinche!

**Comment by sinwoobang** [comment]
@chjinche Is there any open discussion? Otherwise, would you please share the progress?
