### ISSUE TITLE
[BUG] [VSCode Extension] : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997).

### ISSUE THREAD

**Issue by kamzz1107** [microsoft/promptflow#3665]
**Describe the bug**
Not able to generate and verify the tool. getting error: WARNING:azure.monitor.opentelemetry.exporter.export._base:Retrying due to server request error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997).

**How To Reproduce the bug**
Try to create python or prompt tool and try to validate and parse the output.

**Screenshots**
<img width="377" alt="image" src="https://github.com/user-attachments/assets/dade3315-60dd-490d-9ec4-3259884acd12">

**Environment Information**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906] 1.15
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]: windows 11
 - Python Version using `python --version`: [e.g. python==3.10.12] 3.10.0
 - VS Code version. 1.92.1
 - Prompt Flow extension version.

**Comment by diondrapeck** [comment]
I'm facing the same issue. Any luck?
