### ISSUE TITLE
Does not support uploading datastore with PDFs[BUG]

### ISSUE THREAD

**Issue by agray0232** [microsoft/promptflow#369]
**Describe the bug**
PromptFlow will throw an error if you point to an azure DataStore that contains structured data (such as PDFs). Instead for structured data, you have to manually upload the files instead of pointing to a DataStore

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Go to Data in the AML workspace
2. Create a new Data connection
3. Create from Azure Storage 
4. Create a new Datastore
5. Create the datastore from uploaded PDFs in Azure Blob Storage
6. Store Path leave as default (/)
7. An error will be thrown

**Expected behavior**
A data asset should be able to be created from structured data such as PDFs

**Screenshots**
<img width="1392" alt="Screenshot 2023-09-11 at 11 12 32 AM" src="https://github.com/microsoft/promptflow/assets/16495950/3d3b791d-f7d2-46e4-beb9-5bd15eac9c25">

<img width="644" alt="Screenshot 2023-09-11 at 11 12 40 AM" src="https://github.com/microsoft/promptflow/assets/16495950/0cbc6e30-bfe9-4903-a13b-aedd3a668095">

**Comment by eniac871** [comment]
hi Anthony, this is an issue related to AzureML studio data asset. Could you please file OCV or raise the question in AzureML internal Teams channel?
