### ISSUE TITLE
[Feature Request] Automatic Propagation of PromptFlow Connection Changes to Live Endpoints

### ISSUE THREAD

**Issue by Stefano-Salvatori** [microsoft/promptflow#3706]
We are experiencing an issue with the behavior of PromptFlow connections in our current environment. Specifically, when a PromptFlow connection is modified, these changes are not automatically propagated to existing live endpoints. The only way to reflect these changes is by re-deploying the endpoint entirely, which causes operational inefficiency and potential downtime.

We would like the system to automatically propagate any changes made to a PromptFlow connection to live endpoints without requiring a manual re-deployment. This enhancement would streamline the workflow, reduce downtime, and improve the overall responsiveness of the system.

The only alternative we have currently is to manually re-deploy the endpoint after every change to the PromptFlow connection. This approach, however, is not ideal as it introduces unnecessary downtime and operational complexity.

**Comment by abozaralizadeh** [comment]
I fully support this issue. The current need to manually re-deploy endpoints after modifying a PromptFlow connection is indeed a significant operational burden. Automatic propagation of these changes would not only reduce downtime but also enhance the overall efficiency and reliability of the system. Implementing this enhancement would greatly benefit users by streamlining workflows and minimizing disruption to live services.
