### ISSUE TITLE
[BUG] Error when opening Visual Editor in flow.dag.yaml: Error loading webview: Error: Could not register service worker

### ISSUE THREAD

**Issue by FabianAltendorfer** [microsoft/promptflow#372]
I get the following error when opening the Visual Editor in the flow.dag.yaml file in VSCode on Ubuntu:

Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by ttthree** [comment]
hi @FabianAltendorfer  if you don't mind please share below information:

**Environment Information**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]
 - VS Code version.
 - Prompt Flow extension version.

**Comment by JYC-99** [comment]
We are still investigating. Probably related to: https://github.com/microsoft/vscode/issues/125993 which is old but reopened recently.
Can you try if upgrading VS Code to latest version or using VS Code insider works for you?

**Comment by FabianAltendorfer** [comment]
Hi,

Thank you for your answers. I've reinstalled VS Code, and the error has disappeared. Everything seems to be working now.
