### ISSUE TITLE
[Feature Request] Deploy Flow to Azure AI Studio UI

### ISSUE THREAD

**Issue by hayescode** [microsoft/promptflow#3728]
**Is your feature request related to a problem? Please describe.**
My use case primarily uses the Azure AI Studio to create, develop, and evaluate promptflows. Some of my flows are getting complicated so I tried the VS Code Extension. I can develop/run flows in VS Code, but I cannot save new flows to the Studio and make them visible. I can adjust an existing flow and changes show up though, just not create new flows in VS code and push to the Studio UI. I also tried developing in the `code` folder but this also isn't in the UI. 

I am sure this is user error or I'm misunderstanding. I cannot seem to find how to do this basic task in the documentation. This request is to ideally add deploy options in the VS Code extension and/or improve the documentation.

**Describe the solution you'd like**
A better way of developing flows in VS Code and using the UI to run/evaluate.

**Describe alternatives you've considered**
Copy/Paste existing flow in `shared/users/<user name>` but still nothing. 

**Additional context**

**Comment by hayescode** [comment]
Ok I still cannot get this working from the VS Extension, but just running in a juptyer notebook I see `pf.flows.create_or_update()` is the SDK for deploying, however the flex.flow I'm developing is not supported. So back to square one again. I'm not sure how to configure/customize flex flows in VS code and have those flex flows available in Azure AI Studio.

```py
flow = f"\copilot_sdk_flow"
flow_name = "test_from_local"
flow_type = "standard"
flow_description = "Flow created from local"
flow_tags = ["local", "test"]
pf.flows.create_or_update(flow=flow, display_name=flow_name, type=flow_type, description=flow_description, tags=flow_tags)
```
```sh
UserErrorException: Flow source 'C:/.../copilot_sdk_flow'. is flex flow. Creating it to cloud is not supported.
```

**Comment by dpolac** [comment]
@hayescode If you created a flow in VS Code and want to upload it to AI Studio, you must select "Prompt flow" from left side menu and click on the blue "+ Create" button. Then select "Upload from local" option.

**Comment by hayescode** [comment]
@dpolac This is from Azure AI Studio UI, right? Is there no way to deploy *from* VS Code? It looks like 'Upload from local' requires `flow.dag.yaml` so this doesn't work with flex flows ( `flow.flex.yaml` ) yet?

**Comment by hayescode** [comment]
pf.create_or_update_flow() works. The documentation has an issue with the credential code it's supposed to be `credential.token` not just `credential`.
