### ISSUE TITLE
[BUG] [VSCode Extension] pf connection create fails from cli with keyring.alt installed , but works from UI that uses pfutil.py connection upsert

### ISSUE THREAD

**Issue by cicorias** [microsoft/promptflow#373]
**Describe the bug**
pf connection create cli command with keyring.alt is failing but with UI triggered command that uses following -- it works:

```
/home/cicorias/g/cse/oneweek
/2023/llmops/prompt-flow-llmops/venv/bin/python /home/cicorias/.vscode-server/extensi
ons/prompt-flow.prompt-flow-1.0.7/pfutil/pfutil.py connection upsert -f /home/cicoria
s/.promptflow/temp/new_AzureOpenAI_connection.yaml -o /tmp/pf-upsertConnection-f41634
9a-5a60-45a2-ace6-1c5e8b5774cc.json
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. use ubuntu 20.04 in WSL
2. using the cli try to  create connection ie. `pf connection create --file azure_openai.yaml...`

**Screenshots**
<img width="886" alt="image" src="https://github.com/microsoft/promptflow/assets/1080406/d6154fbf-9330-4b83-8d88-f4fe9e1a0a12">

<img width="645" alt="image" src="https://github.com/microsoft/promptflow/assets/1080406/99cafde3-8571-4668-b2d9-215087b3c7f9">

<img width="645" alt="image" src="https://github.com/microsoft/promptflow/assets/1080406/14172c47-7d3f-42de-b88f-2b2cc365d9f0">

1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
4. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]  `0.1.0b5`
 - Operating System: [e.g. Ubuntu 20.04, Windows 11] `Ubuntu 22.04.3 LTS`
 - Python Version using `python --version`: [e.g. python==3.10.12] `Python 3.10.9`
 - VS Code version. `1.82.0`
 - Prompt Flow extension version. `v1.0.7`
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 - If your code to repro the issue is public and you want to share us, please share the link.
```
2023-09-12 17:29:51.808 Command failed: /home/cicorias/g/cse/oneweek/2023/llmops/prompt-flow-llmops/venv/bin/python /home/cicorias/.vscode-server/extensions/prompt-flow.prompt-flow-1.0.7/pfutil/pfutil.py connection get -n "open_ai_connection" -o /tmp/pf-getConnectionWithoutSecret-ca3699c5-6e66-4aaa-a60d-7201b3989084.json
Traceback (most recent call last):
  File "/home/cicorias/.vscode-server/extensions/prompt-flow.prompt-flow-1.0.7/pfutil/pfutil.py", line 4, in <module>
    main()
  File "/home/cicorias/.vscode-server/extensions/prompt-flow.prompt-flow-1.0.7/pfutil/_pf_vsc_main.py", line 32, in main
    operate_connection(args)
  File "/home/cicorias/.vscode-server/extensions/prompt-flow.prompt-flow-1.0.7/pfutil/_pf_vsc_connection.py", line 31, in operate_connection
    get_connection(args)
  File "/home/cicorias/.vscode-server/extensions/prompt-flow.prompt-flow-1.0.7/pfutil/_pf_vsc_connection.py", line 77, in get_connection
    connection_with_secret = convert_orm_object_to_connection(ORMConnection.get(connection_name), include_secret=include_secret)
  File "/home/cicorias/g/cse/oneweek/2023/llmops/prompt-flow-llmops/venv/lib/python3.10/site-packages/promptflow/_sdk/_orm/retry.py", line 43, in f_retry
    return f(*args, **kwargs)
  File "/home/cicorias/g/cse/oneweek/2023/llmops/prompt-flow-llmops/venv/lib/python3.10/site-packages/promptflow/_sdk/_orm/connection.py", line 52, in get
    raise ConnectionNotFoundError(f"Connection {name!r} is not found.")
promptflow._sdk._errors.ConnectionNotFoundError: Connection 'open_ai_connection' is not found.


```

**Additional context**

running with debug 

<img width="746" alt="image" src="https://github.com/microsoft/promptflow/assets/1080406/10158779-7c7d-4845-bb82-9b6b4591c54e">

**Comment by brynn-code** [comment]
@cicorias It seems like the conda environment used in terminal is different from the extension, as vscode extension will call the same logic with cli when creating connection... could you please exec a 'pip list' to see if keyings.alt installed in venv?

**Comment by xukecheng** [comment]
I hava same issue:
![CleanShot 2023-10-12 at 14 57 38](https://github.com/microsoft/promptflow/assets/29099863/a4eff0b6-8ae2-475c-928d-63261cbc088a)
Operating System: MacOS
Development Environment: VSCode with remote SSH extension
Remote Server OS: Debian 12

**Comment by brynn-code** [comment]
When manage connections, we are using the keyring library which provides an easy way to access the system keyring service. The error raised due to keyring can’t find an available backend to store keys on your operating system.  

Please reach more detail at https://microsoft.github.io/promptflow/how-to-guides/faq.html#connection-creation-failed-with-storeconnectionencryptionkeyerror to get more details about the keyring backend. For example, `keyrings.alt` is one of a valid third-party backend.

**Comment by cicorias** [comment]
> @cicorias It seems like the conda environment used in terminal is different from the extension, as vscode extension will call the same logic with cli when creating connection... could you please exec a 'pip list' to see if keyings.alt installed in venv?

Conda is not used. Just pyenv with pip

And, no that's not true either -- this is a pure venv and the `command -v python/pip` all point to the same location.

This is under WSL2 ubuntu 22

**Comment by Wix97** [comment]
@cicorias Please run the following command, it works for me
`sudo apt-get update `
`sudo apt-get install gcc cmake pkg-config libdbus-1-dev libglib2.0-dev `
`pip install keyrings.alt dbus-python`

For Linux, 'pip install keyrings.alt' cannot setup its dependency dbus-python correctly since it relies on other non-python dependencies.

**Comment by pamelafox** [comment]
I experienced this issue in a dev container on my M1 Mac today. I used the commands from @Wix97 in my devcontainer Dockerfile, and that does seem to work:

https://github.com/Azure-Samples/contoso-chat/blob/13ce7cb1e0d702efd869d767d2e124237aec44fb/.devcontainer/Dockerfile

It might be helpful to put explicit details about dbus installation in the promptflow documentation if it's going to be a common issue on Linux / dev containers.

**Comment by brynn-code** [comment]
Resolved as usually this is customer environment missing required package, you could see available solution above.
