### ISSUE TITLE
[Feature Request] Improve Evaluation Charts

### ISSUE THREAD

**Issue by hayescode** [microsoft/promptflow#3774]
**Is your feature request related to a problem? Please describe.**
My evaluation flow has inputs like "source system" and "difficulty" that i'd like charts for to visually see progress across evaluations. The only fields that are available in the Custom Charts however are evaluation flow outputs, not even my custom metrics.

**Describe the solution you'd like**
Any field in the evaluation flow results should be available for custom charts, including custom metrics (aggregations).

**Additional context**
![image](https://github.com/user-attachments/assets/20154d40-42cd-4b66-b498-e8852956d972)
![image](https://github.com/user-attachments/assets/1ededf51-e403-4483-956f-090c92d64379)

**Comment by vinuthakaranth** [comment]
Hi @hayescode , thanks for your valuable feedback in enhancing our product. 

We are trying to understand what 'including custom metrics (aggregations)' means here. How are you envisioning having this in chart? Any further details on this would definitely help in putting this request to implementation.

Could you give us an example of x-Axis and y-axis combinations you would like to see in your custom chart and how that would help you in viewing progress?

**Comment by hayescode** [comment]
Hi @vinuthakaranth - I have dimensions like difficulty (easy/medium/hard) I'd like to so the accuracy across for example. Another example would be RAG source, so I can see source A has high accuracy but not source B, soay e I should look into Source B instead of anything with the prompting/LLM.
