### ISSUE TITLE
[Feature Request] Remove errors when they are fixed

### ISSUE THREAD

**Issue by Vivihung** [microsoft/promptflow#378]
**Is your feature request related to a problem? Please describe.**
While trying to learn and use the code-first experience, I was confused by the Prompt flow errors in the IDE. After check the details of each error, it seems like a point in time error during my flow development. However, even my flow is fixed and can run successfully, the accumulated PF errors don't go away. It's annoying to dismiss them one by one.
![image](https://github.com/microsoft/promptflow/assets/4814277/84981b95-f972-4b3c-8d9d-c1450f55b7e1)

**Describe the solution you'd like**
Don't show errors when they are no longer valid (or have been fixed).

**Describe alternatives you've considered**
It might be a more natural place to show PF errors in VSCode Problem instead of having a pop up.
![image](https://github.com/microsoft/promptflow/assets/4814277/870e8cb1-42df-42fe-b7e0-afbf7a7d0da5)

**Additional context**
N/A

**Comment by veepe110** [comment]
Hello?
