### ISSUE TITLE
Can I use local LLM deployed by vllm?

### ISSUE THREAD

**Issue by LIUKAI0815** [microsoft/promptflow#3785]
llama3.1
qwen2.5
phi3.5
Mistral-Large-Instruct-2407
DeepSeek-V2-Chat-0628
ollama gguf

**Comment by pitt-liang** [comment]
vLLM/Ollama supports an OpenAI-compatible API server. 

You can create an PromtpFlow OpenAIconnection by simply replacing the base_url field with your LLM endpoint and use the connection in LLM tool.

**Comment by LIUKAI0815** [comment]
Thank you
