### ISSUE TITLE
[BUG]  Connections broken in flows and connections dialogs

### ISSUE THREAD

**Issue by fausttiger007** [microsoft/promptflow#3788]
**Describe the bug**
Trying to show Connections in Prompt Flow via old Connections menu... gives
Failed to get secret for connection 'Default_AzureOpenAI'. Service invocation failed! Request: POST management.azure.com/subscriptions/xxxxxxxx/resourceGroups/BIDSMachineLearning-dev-rg/providers/Microsoft.CognitiveServices/accounts/meuw-xxx-xxxx/listKeys Status Code: 403 Forbidden Reason Phrase: Forbidden Response Body: S2S invocation to arm failed when calling: https://management.azure.com/subscriptions/xxxxxxxx/resourceGroups/BIDSMachineLearning-dev-rg/providers/Microsoft.CognitiveServices/accounts/meuw-xxxxxxxx/listKeys?api-version=2023-10-01-preview

Separate "new preview" Connections Workspace dialog lists connections,   but Prompt Flows can not see connections.

Separate PromptFlow run in SDK has similar issue.

Prompt Flow in AI Studio appears to work.

Did the API Version change, and  prompt flows themselves need to be updated somehow?
https://management.azure.com/subscriptions/xxxxxxxx/resourceGroups/BIDSMachineLearning-dev-rg/providers/Microsoft.CognitiveServices/accounts/meuw-xxxxxxxx/listKeys?**api-version=2023-10-01-preview**

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. open ML Workspace
2. open prompt flow
3. click connections
4. wait and error occurs.
5. then
6. open new preview Connection Window.. displays connections
7. open prompt flow
8. no connections can be setup, since  can't see connections.

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/076a6db0-f0e3-4ec7-b44d-f29541c92a14)

![image](https://github.com/user-attachments/assets/e5a89cb1-5219-4de1-84b9-e87ca3a1b054)

**Running Information(please complete the following information):**
 - running in current Prompt Flow portal in ML Workspace

**Additional context**

**Comment by HFL-EDEKA** [comment]
Same Problem here - adding "Azure AI Adminitrator" role did not help. Still experiencing the same issue with identical error messages. Needless to say, we have not changed anything in the resources or the hub & project environment.

**Comment by fausttiger007** [comment]
I wonder if they have started enforcing the Workspace Connections  instead of the separate PromptFlow Connections...      but the prompt flows themselves (or new API version required?) aren't aware and use some prior method to access connections definitions.
