### ISSUE TITLE
[BUG] Still getting this error when trying to run deployed flow: Execution failure: (TypeError) unsupported operand type(s) for +: 'int' and 'NoneType'"

### ISSUE THREAD

**Issue by Chriss-24** [microsoft/promptflow#3806]
Everything related to this issue was marked as resolved but it is resolved and I am still getting this error when I try to consume prompt flow via http request. 

When I am adding openai<=1.44.1 to the requirements.txt (as it was suggested in other topics) I can't deploy a flow and getting this error: Authorization failed for container registry to access image details. Make sure that the container registry associated with the Environment is not unintentionally private, or if this container registry is behind a private network, ensure that it has been set up properly. Otherwise, please try running resync keys on your workspace and retry

**Comment by hiroki0525** [comment]
I'm still encountering a similar bug, the version of promptflow is 1.16.1.

```
promptflow._core._errors.ToolExecutionError: Execution failure in 'check_japanese_foods_from_table': (TypeError) unsupported operand type(s) for +: 'dict' and 'dict'
2024-10-10 22:44:51 +0900   42295 execution.flow     WARNING  Failed to calculate metrics due to exception: unsupported operand type(s) for +: 'int' and 'dict'.
2024-10-10 22:44:51 +0900   42295 execution.flow     WARNING  Failed to calculate metrics due to exception: unsupported operand type(s) for +: 'int' and 'dict'.
2024-10-10 22:44:51 +0900   42295 execution          INFO     Node create_version in line 0 is canceled.
pf.flow.test failed with UserErrorException: TypeError: Execution failure in 'check_japanese_foods_from_table': (TypeError) unsupported operand type(s) for +: 'dict' and 'dict'
```

**Comment by darrelhong** [comment]
it looks like the tokens object can have nested objects as well, like
```
{'completion_tokens': 298, 'prompt_tokens': 3193, 'total_tokens': 3491, 'completion_tokens_details': {'audio_tokens': None, 'reasoning_tokens': 0}
```
A solution would be to have a helper function that merges nested objects as well
