### ISSUE TITLE
[BUG] The content of assistant is <promptflow.tracing._trace.TracedIterator object at 0x………>, which causes the chat_history passed to LLM to be wrong

### ISSUE THREAD

**Issue by 21-10-4** [microsoft/promptflow#3812]
**Describe the bug**
A clear and concise description of the bug.
通过 `pf flow test --flow new-chat-flow-created-at-2024-10-11  --interactive`在终端进行交互式问答。
问答中，发现AI好像没有上下记忆，经过`trace`发现assistant 部分的content都是 `<promptflow.tracing._trace.TracedIterator object at 0x………>`，只有assistant的最后一次回答的content是正确的
![Image](https://github.com/user-attachments/assets/f57f52f0-e10f-442d-a5fc-40b42adeedb5)
![Image](https://github.com/user-attachments/assets/734e4241-84bd-4a5d-b335-bea4b9a870aa)

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. create new flow->chat flow with  a template

**Expected behavior**

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]
```
{
  "promptflow": "1.16.1",
  "promptflow-core": "1.16.1",
  "promptflow-devkit": "1.16.1",
  "promptflow-tracing": "1.16.1"
}

Executable '/home/xxx/anaconda3/envs/reflextion/bin/python'
Python (Linux) 3.8.19 (default, Mar 20 2024, 19:58:24)
[GCC 11.2.0]

```

**Additional context**

**Comment by dburik** [comment]
I'm experiencing the same issue with Prompt flow `1.16.1`.
Using the following code as a workaround:

```python
from promptflow.tracing.contracts.iterator_proxy import IteratorProxy

if isinstance(output, IteratorProxy):
    output= "".join(output.items)
```

Can someone from Prompt flow team provide a comment on this? Is this a bug or an intended but undocumented change in the API?

**Comment by zyw400** [comment]
Same for me as well. It would be great that some one can help take a check at this issue. 

Setting: 
- Using "iterative mode (text only).
- In the second round of the conversation, I printed out the chat history that was automatically constructed. The previous round's output from the chat module becomes a promptflow TracedIterator object, which is not JSON serializable and cannot be used in the second round of the conversation properly.

Versions:
Requirement already satisfied: promptflow in d:\programs\anaconda3\envs\py311\lib\site-packages (1.16.1)
Requirement already satisfied: promptflow-core==1.16.1 in d:\programs\anaconda3\envs\py311\lib\site-packages (from promptflow) (1.16.1)
Requirement already satisfied: promptflow-devkit==1.16.1 in d:\programs\anaconda3\envs\py311\lib\site-packages (from promptflow) (1.16.1)
Requirement already satisfied: promptflow-tracing==1.16.1 in d:\programs\anaconda3\envs\py311\lib\site-packages (from promptflow) (1.16.1)
Requirement already satisfied: promptflow-tools in d:\programs\anaconda3\envs\py311\lib\site-packages (1.4.0)

D:\Programs\Anaconda3\envs\py311\python.exe -m promptflow._cli._pf.entry flow test --flow d:\Repos\DRICopilot0820\DRICopilot\src\core\copilot_v2 --interactive --user-agent "prompt-flow-extension/1.20.2 (win32; x64) VSCode/1.94.2"
