### ISSUE TITLE
[BUG] Code-first with VSCode Web: Missing instructions on dev env setup

### ISSUE THREAD

**Issue by Vivihung** [microsoft/promptflow#384]
**Describe the bug**
Cannot create folder and virtual env by following the [instructions](https://microsoft.github.io/promptflow/how-to-guides/quick-start.html#set-up-your-dev-environment). Suspect we might miss guidance for developers who are not familar with AML env (according to the doc, AML knowledge isn't required 😄).

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a new project in the new portal.
2. Click on the "Work in VS Code (Web)" button.
3. Select compute and click on "Launch".
4. The portal will open VSCode web in a new window. Sign-in with my credential.
5-1. Try to create a src/ folder via UI or CLI. => permission denied.
5-2. Try to create a virtual env. => conda isn't installed

**Expected behavior**
1. Have permission to add folders/files.
2. conda is pre-installed.

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/4814277/48016f6e-752a-46c2-803e-01a0f2ba81be)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: N/A (Not install PF yet)
 - Operating System: Windows 11 + VSCode Web. The VSCode Web env seems run on Linux.
 - Python Version using `python --version`: the VSCode Web env has Python 3.10.12 (main, Jul 28 2023, 05:35:08) [GCC 12.2.0] on linux.

**Additional context**
It's not clear to developer what is the next step after open an empty PF project in VSCode Web. Recommend adding a PF welcome page to guide users through the necessary steps.

**Comment by Vivihung** [comment]
@wyl765, @JYC-99 - Is there any workaround/quick tips to resolve this permission error? My code-first route is blocked by this issue. Any help/guidance will be appreciated. thanks!

**Comment by JYC-99** [comment]
The prompt flow extension does not talk to the environment directly. PF extension leverates the Python extension to run all py scripts. It is documented.
Regarding this ask, you do not have to use conda. Venv, etc also works.
