### ISSUE TITLE
[BUG] Authorization issue in flows.create_or_update

### ISSUE THREAD

**Issue by Emilon1928** [microsoft/promptflow#3840]
**Describe the bug**
Calling flows.create_or_update raise error: "This request is not authorized to perform this operation."

**How To Reproduce the bug**

from azure.identity import DefaultAzureCredential
from promptflow.azure import PFClient

client = PFClient.from_config(
    credential=DefaultAzureCredential(),
    path='config.json'
)

client.flows.create_or_update(
    flow='./test_flow',
    display_name='test_flow',
)

**Expected behavior**
New flow is created from local files.

**Screenshots**
![Image](https://github.com/user-attachments/assets/a973a429-0a90-4e60-bd08-4903a39216f5)

**Running Information:**
{
  "promptflow": "1.16.1",
  "promptflow-azure": "1.16.1",
  "promptflow-core": "1.16.1",
  "promptflow-devkit": "1.16.1",
  "promptflow-tracing": "1.16.1"
}
Ubuntu 22.04.1 LTS
Python 3.10.12

**Additional context**
Storage account is open for public connections.

**Comment by luigiw** [comment]
Can you make sure your identity has ai developer role to the ai project you're using?

**Comment by Emilon1928** [comment]
I have a contributor role. I can create directories and upload new files to the file share using the interface.
