### ISSUE TITLE
Conditional Loops for LLMs

### ISSUE THREAD

**Issue by baris-kuru** [microsoft/promptflow#3852]
**Is your feature request related to a problem? Please describe.**
I am trying to rerun the LLM model if the generation is hallucinated, but I am getting a circular dependency error. Is there a way to implement this logic in Prompt Flow?

**Describe the solution you'd like**
I would like to have a loop mechanism with max_retries if the output is not sufficient.

**Describe alternatives you've considered**
I was thinking of a secondary LLM to be used in case of hallucination, but then I need as many LLMs as the max retries I want to have.

**Additional context**

Here is my current flow:
![Image](https://github.com/user-attachments/assets/9ecc4481-a4a3-40b7-9362-895e21b1b0aa)

here is the error I am getting:
"_variant_0 Run failed: 
Invalid node definitions found in the flow graph. Node circular dependency has been detected among the nodes in your flow. Kindly review the reference relationships for the nodes ['answer_the_question_with_context', 'hallucination_grader', 'hallucination_pass', 'output_show'] and resolve the circular reference issue in the flow._ "

**Comment by khangpham-arsen** [comment]
Hi, I also had similar struggle as yours. After researching, I realize that since it's a DAG flow, you are not supposed to implemented any loop. To achieve that logic, you should change to use Flex flow instead.
