### ISSUE TITLE
[BUG] CLI build issues when connection contains spaces

### ISSUE THREAD

**Issue by marcgs** [microsoft/promptflow#507]
**Describe the bug**
Few things do not work when running `pf flow build` having a connection with a space in the name (e.g. "Azure OpenAI"):
* The generated `start.sh` script does not escape the connection file path correctly:
   `pf connection create --file /connections/Azure OpenAI.yaml`
* The `api_key` for connection file (e.g. `connections/Azure OpenAI.yaml`) is invalid as it contains spaces:
   `api_key: ${env:AZURE OPENAI_API_KEY}`

**How To Reproduce the bug**
1. Create a simple flow
2. Configure a connection with a space in the name
3. Run `pf flow build --source <flow_dir> -f docker --output out`
4. Observe the aforementioned files

**Expected behavior**
The aforementioned files should be generated correctly

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b5
 - Operating System: MacOS 13.5.2
 - Python Version using `python --version`: 3.11.5

**Comment by brynn-code** [comment]
Thanks for the feedback, we'll use this issue to track and fix.
