### ISSUE TITLE
[Feature Request] When batch run, in logs.txt let me know how many records in my batch run dataset, what is the current progress. for example 3/10,

### ISSUE THREAD

**Issue by ishinzhang** [microsoft/promptflow#519]
**Is your feature request related to a problem? Please describe.**
when batch run, in logs.txt let me know how many records in my batch run dataset, what is the current progress. 

**Describe the solution you'd like**
I want something like tqdm package. tell me the progress (in percentage or/and a/b), elapsed time, estimated remaining time and average time to complete one record of data.
![image](https://github.com/microsoft/promptflow/assets/94444320/5adc1599-e41a-4fe9-b21a-57498003facc)

**Describe alternatives you've considered**
No. Currently in my flow, I printed a text to logs, it is long, so it is hard for me to know how much time I need to wait for the batch run to finish. I have to go through with naked eye among the long log to find the output of one step to get the path, and search in my data.jsonl to figure out the process. It is exhausting. 

**Additional context**

**Comment by zhengfeiwang** [comment]
Hi @ishinzhang , thanks for your feedback. We have an ongoing work item that will print out progess `Finished A/B lines` in the log.txt, which I understand can help you track the progress with simple search. Please share your thought on this, and we can use this issue to track this.

**Comment by zhengfeiwang** [comment]
Have synced with Yijun, we don't really need `tqdm` experience in logs.txt, and we will log progress and time related info in logs, so that users can track the progress more easily.

**Comment by zhengfeiwang** [comment]
Close this issue with Peiwen's PR.
