### ISSUE TITLE
[BUG] [VSCode Extension] Running bulk test vs code interactive window errors not show

### ISSUE THREAD

**Issue by zyw400** [microsoft/promptflow#527]
**Describe the bug**
I was running the code below to do a bulk test using the vs code python interactive window (shift-enter to execute the cells). 
![image](https://github.com/microsoft/promptflow/assets/33538664/94ec1bce-a464-4ed4-bca1-61366ac58307)
The flow has some issues. But from the VS code interactive window, the cell execution never stops.

**How To Reproduce the Bug**
Steps to reproduce the behavior, how frequently can you experience the bug: every time.

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/33538664/48acecde-0df3-4757-8cb1-9bc0a8cf71e5)

![image](https://github.com/microsoft/promptflow/assets/33538664/72f2b46e-709e-4484-aec7-558703d7c69d)

**Environment Information**
 - Operating System: Windows 11
 - Python Version using `python --version`: 3.9.17
 - VS Code version.
 - Prompt Flow extension version.
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by D-W-** [comment]
Hi @zyw400 , could you provide the code of the stuck cell so we can try repro it? From your screenshot seems the flow run has completed.

**Comment by D-W-** [comment]
Seems executor stucks when executing in python interactive window. @huaiyan's helping take a look.

**Comment by huaiyan** [comment]
Thanks for reporting @zyw400 
This issue is by design since we need to create child process for `exec_bulk`.
The workaround is executing your code in main block, for example:
```
if __name__ == "__main__":
    flow_executor = FlowExecutor.create(
        flow_file="./flow.dag.yaml",
        connections={"azure_open_ai_connection": AzureOpenAIConnection(
            api_key="fake_api_key",
            api_base="fake_api_base",
        )._to_execution_connection_dict()},
    )
    result = flow_executor.exec_bulk(inputs=[
        {"input1": "value"}
    ])

```



Root cause about it:
When Python `multiprocessing` module creates child processes, it imports the main module. So, if we don't execute the code in main block, the code will be triggered again as importing, which will be one disaster.
We will take effort about improving doc about it.
