### ISSUE TITLE
[Feature Request] Point local run outputs to flow folder

### ISSUE THREAD

**Issue by bepuca** [microsoft/promptflow#557]
**Is your feature request related to a problem? Please describe.**
At the moment, when running flows locally, the outputs are saved using `Path().home()` which ends up putting the outputs in a hard to access place. Whilst they can be found thanks to the outputs in std out, they are hard to recover later on which hinders the local experience for inspecting results. 

**Describe the solution you'd like**
Always save the outputs int the `<flow_directory>/.promptflow` like other artifacts that appear there. Thus, they are always easily recoverable.

**Describe alternatives you've considered**
Make it a parameter that you can pass it to the flow to save logs wherever you want them.

**Additional context**
I create this PR (https://github.com/microsoft/promptflow/pull/506) but it has been ignored without any feedback, so maybe the process should start with an issue.

**Comment by zhengfeiwang** [comment]
Hi @bepuca , thanks for your feedback, and your PR! We had a discussion on this, and we will support this as the suggested parameter way, so that you can specify the output path per run.

Let's use this issue to track.

**Comment by zhengfeiwang** [comment]
BTW, I noticed you mentioned in your PR that you have run into many issues running the tests. Could you please summarize them and open another issue on that? We do hope the develop experience could be smooth, so any feedback on that is appreciated!

**Comment by zhengfeiwang** [comment]
Hi @bepuca , sorry for the long time waiting, the related PR (#1212 ) has just merged, and it is expected to be shipped in the 1.1.0 release, next week. Please let me know if you have interest to try it before that!
