### ISSUE TITLE
[Feature Request] Allow AzureML data assets as non-data inputs

### ISSUE THREAD

**Issue by bepuca** [microsoft/promptflow#558]
**Is your feature request related to a problem? Please describe.**
When things start to complicate beyond the examples provided already, there are many cases where one might want to inject some data and/or file to some of the nodes in a flow that are not input records. An example, is to inject a custom vector index store. I was not able to do that.

**Describe the solution you'd like**
I would like to be able to mount AzureML registered data assets that are not input data but some other artifacts that are required by my flow.

**Comment by bepuca** [comment]
Hello @jiaochenlu ,

Yes and no :). So let me try to explain myself a little better. In local, things are fine for me to NOT inject any AzureML asset. What I'd like, is when running things in the cloud, to potentially do what you mention in step 1 with AzureML data assets via mounting mode.

At the moment, if there was nothing to mount, I can use flow inputs with default. The problem is that if one of these inputs is an AzureML artifact, that is not mounted (and it makes sense). So then, I'd like for an artifact that is not the input data to be able to be an AzureML artifact that is mounted so it is accessible for a specific node.

The case that brought this is that I was trying to create some lightweight custom vector store. For the problem where this was used, the corpus is not that big, so the easiest is to persist that vector store as a pkl of a dictionary. In local it is very easy to make that file available to the flow so I can use that instead of a third party connection. The problem is that there is no mechanism to do that (that I know of) in the cloud version.

I was trying to register that file and then reference it, but it is just not mounted. This would be useful in this case because setting up a custom vector store that can be called through API or REST is much more involved than using a file. Later on a project, setting that up as a service is probably the right answer, but I'd like to be able to experiment quickly with that custom vector store, and ideally I could load that artifact so it is available into the flow.

Does this makes things a bit more clear?

**Comment by jiaochenlu** [comment]
Thanks @bepuca for the comprehensive explanation, we are tracking this as a new feature ask in our side.
