### ISSUE TITLE
[Feature Request] Support flow parameters

### ISSUE THREAD

**Issue by bepuca** [microsoft/promptflow#559]
**Is your feature request related to a problem? Please describe.**
When running flows locally or in the cloud, I might want to set some values differently. Maybe a parameter that points to a different model. At the moment, this can only be done, to some extent, with variants, which may be extremely verbose for tiny changes some times. Additionally, they require the YAML to be heavily modified to test new parameter combinations.

**Describe the solution you'd like**
I would like some input parameters to a flow that can be reference throughout the DAG YAML, that can have defaults but can be passed at run time. That way, I could for instance test very quickly different things, without having to heavily change the YAML. For transparency, these could be logged at the beginning of an execution or set as tags of the flow when running in the cloud.

**Describe alternatives you've considered**
To some extent, this can be solved with variants, but if a flow is complex, the YAML becomes huge for maybe just changing one little number on one step.

**Comment by sethjuarez** [comment]
There's a combination of things that _may_ work for you - interested in your thoughts.

1. prompt flow inputs - you can control the inputs to the prompt flow using the inputs section - in theory you can put anything in there:
![image](https://github.com/microsoft/promptflow/assets/115409/bd8b63af-e485-4b90-9590-bc0563f280bd)

2. Activation Config - this stipulates when the node will run or if it is bypassed altogether:
![image](https://github.com/microsoft/promptflow/assets/115409/70c14e39-f652-4a55-a10c-55dce45f1e27)

Will these settings be sufficient to achieve your desired result?

**Comment by bepuca** [comment]
Just a question then: My understanding is that whatever I put in `inputs` is expected to be in every record I pass the flow (or use the default). This, would not work, for instance if I wanted to try different runs from the same DAG varying one parameter for the same dataset. I could do some shanenigans before passing the data to the flow but I think it is too much complexity.

What I would need then is some mechanism where I can override a parameter in the DAG when I trigger a flow. I am fine of using inputs with defaults, but then I would like to be able to overwrite that default at runtime without modifying the YAML. Would that be possible somehow?

**Comment by ttthree** [comment]
@bepuca  please check this example: 
https://github.com/microsoft/promptflow/blob/26e7e04796ce447fc4cded243f0c5f403b1cc54e/examples/flows/chat/chat-with-pdf/flow.dag.yaml#L13

We used a config as flow parameter, it has default value, it can be override when doing batch run (so you don't have to have the config in every line of input), it can be override when deploy endpoint/app (so you don't have to include it in your request)

Example for batch run:
https://github.com/microsoft/promptflow/blob/26e7e04796ce447fc4cded243f0c5f403b1cc54e/examples/flows/chat/chat-with-pdf/tests/chat_with_pdf_test.py#L64

**Comment by bepuca** [comment]
Hello @ttthree , thank you very much for your answer! I just saw it now. This actually looks like it will solve my needs, thank you very much!
