### ISSUE TITLE
[BUG] AML Studio Web version of Prompt Flow does not log or trace to Azure Application Insights 

### ISSUE THREAD

**Issue by Rhernandez513** [microsoft/promptflow#611]
During the Microsoft Global Hackathon 2023 it was discovered that when using the Web version of PromptFlow, logging and tracing does not reach App Insights.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1.  Use the following python packages: opencensus-ext-azure, opencensus-ext-logging.  Consider the "chat_flow_with_vectordb_tool" flow on the branch https://github.com/microsoft/prompt-flow-llmops/tree/feature/logging_and_tracing

2. Engage the flow on local VSCode or web version of VSCode using cloud compute, verify a trace appears on AppInsights.  Check for traces by using the search query "traces" in LogAnalytics. 

3. Engage the flow on Azure Machine Learning Studio, observe no trace appears on AppInsights

**Expected behavior**

When flow is engaged using Azure Machine Learning Studio's version of PromptFlow, simple traces appear in AppInsights.

**Screenshots**

 Evidence showing working version on VSCode https://github.com/microsoft/prompt-flow-llmops/issues/3

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.0.105586882
 - Operating System: MacOS 13.6 using DevContainer with $ uname -a returning : `Linux d3f8f1336671 6.3.13-linuxkit #1 SMP PREEMPT Thu Sep  7 07:48:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux` 
 - Python Version using `python --version`: Python 3.9.16

**Comment by eniac871** [comment]
@Rhernandez513  I don't have access to the prompt-flow-llmops repo. Could you please grant me the permission so that we can check how do you send telemetry to Appinsights?

**Comment by Rhernandez513** [comment]
> @Rhernandez513 I don't have access to the prompt-flow-llmops repo. Could you please grant me the permission so that we can check how do you send telemetry to Appinsights?

Yes I've reached out to [prabdeb](https://github.com/prabdeb), hope to get you access soon.

**Comment by Rhernandez513** [comment]
Hi @eniac871  you should have access now

**Comment by eniac871** [comment]
@Rhernandez513  I just checked the code, I see it needs to read app insight connection string from env file, could you please confirm when submit to cloud, does the connection string set properly?
