### ISSUE TITLE
The exention connection panel “always loading” [BUG][vscode extension]

### ISSUE THREAD

**Issue by joisonwk** [microsoft/promptflow#654]
**Describe the bug**
I cannot create connections through the plugin's connection panel, and the pannel is always waiting for fetching connections, and the progress message in the bottom status bar keeps saying "Fetching connections or Validating connection configurations". 
Does anybody know how to solve this issue?

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1、open the Prompt flow for vscode extension, not do anything, the connection pannel show below 
![image](https://github.com/microsoft/promptflow/assets/7928742/75f545d8-fb23-4147-93be-7c03e756ae9f)
2、click "+" select openai or azure, then click the "Create connection", No Task Effect。
 
**Expected behavior**

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/7928742/0a158d5e-c33a-4abb-bffb-c03658ad084e)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b5
 - Operating System: [e.g. WSL: Ubuntu 20.04]
 - Python Version using `python --version`: python==3.10.11

**Comment by bobogogo1990** [comment]
Thanks @joisonwk , is there any error message on the terminal or output of `prompf-flow` can share with us ?

**Comment by joisonwk** [comment]
> Thanks @joisonwk , is there any error message on the terminal or output of `prompf-flow` can share with us ?

I don't know where to view the plugin's logs, the default terminal doesn't have any other output. When I click Refresh Connections in the CONNECTIONS panel, the status bar will prompt “Fetching connections...”, and when I click "Create connection" in the new_OpenAI_connection.yaml file, it will prompt "Validating connection configurations..."

**Comment by joisonwk** [comment]
================~/.promptflow/logs/prompt-flow-2023-09-28.log===========================
[perf: prompt-flow 1.0.12 2023-09-28T04:17:49.586Z] load flowYamlContent 5884 bytes duration: 48.50084698200226ms[9/28/2023, 12:17:49 PM]
[perf: prompt-flow 1.0.12 2023-09-28T04:17:49.589Z] parse flowYamlContent duration: 2.8917330503463745ms[9/28/2023, 12:18:12 PM]
[perf: prompt-flow 1.0.12 2023-09-28T04:18:12.969Z] listBulkTestRun 3761 bytes duration: 989.518837094307ms[9/28/2023, 12:28:58 PM]
[perf: prompt-flow 1.0.12 2023-09-28T04:28:58.995Z] listConnectionSpecs 3494 bytes duration: 17.876119017601013ms

**Comment by joisonwk** [comment]
I tried deleting the cache directory ".promptflow" and restarting vscode, the CONNECTIONS panel can show all types of connections and the connections can be created normally. Then it enters the previous error state. When you click Create, you are prompted for verification. Refresh Fetching prompt.

**Comment by joisonwk** [comment]
[prompt-flow-2023-09-28.log](https://github.com/microsoft/promptflow/files/12745708/prompt-flow-2023-09-28.log)
This is the complete log file

**Comment by bobogogo1990** [comment]
hi @joisonwk is there still problem when use the latest version extension ?

**Comment by yayachenyi** [comment]
same problem. VS extension keep fetching connections even though I find a lot of connections using `pf connection list`
