### ISSUE TITLE
[BUG] PFClient uses execution path instead of flow path as root of relative path defined in the flow 

### ISSUE THREAD

**Issue by luigiw** [microsoft/promptflow#656]
**Describe the bug**
A clear and concise description of the bug.

When I'm using a relative path in my flow code. I expect the path is relative to the flow folder, but it's actually relative to the execution path.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a flow that references a file using relative path
<img width="576" alt="image" src="https://github.com/microsoft/promptflow/assets/1483379/718f951e-5288-4325-a183-85fd13d27b9c">
2. Run the flow using the VS code extension. The flow works as expected.
3. Run the flow using PFClient from PF SDK from a different folder. There will be an error saying the path doesn't exist. 

**Expected behavior**

The behavior should be consistent between VS code extension run and PFClient run.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

**Comment by eniac871** [comment]
@luigiw  when you run the flow using PFClient in a different folder, seems we cannot control what's the flow execution folder and hard to know how to identify the path.
