### ISSUE TITLE
[BUG] PFClient fails silently when there's an error running the flow

### ISSUE THREAD

**Issue by luigiw** [microsoft/promptflow#657]
**Describe the bug**
A clear and concise description of the bug.

When the flow code raises an exception, the exception doesn't throw through PFClient.run(). It makes me think the run succeeded but it actually didn't. I have to look at `error.json` to know what went wrong.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Manually raise an exception in a flow's code.
2. Run the flow with PFClient.run()
3. Observe the call succeeded without raising any exceptions.

**Expected behavior**

An exception raised from PFClient.run() or it prints out the error messages.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

**Comment by lalala123123** [comment]
There is a bug with the flow run status, we will fix it and print an error log to alert customer that the flow run failed
