### ISSUE TITLE
[BUG] PF connection locally api_key issue

### ISSUE THREAD

**Issue by YusakuNo1** [microsoft/promptflow#669]
**Describe the bug**
When I'm using a connection from a PromptFlow node (the function decorated by "@tool"), in Azure portal, the connection contains the correct API KEY, but when I run it locally with "pf flow test --flow .", the api_key field returns a string with paths. I'm using Windows, but not sure it's Windows specific or not.

Sample function:

```
@tool
def my_demo_tool(
  query: str,
  aoai_connection: AzureOpenAIConnection
) -> str:
    print(repr(aoai_connection.api_key))
```

In Azure portal, it shows the correct API key, while in my laptop, it returns `C:\Users\[my_user_name]\AppData\Local\miniconda3\envs\py3\python.exe c:\Users\[my_user_name]\.vscode\extensions\prompt-flow.prompt-flow-1.0.12\pfutil\pfutil.py connection upsert -f c:\Users\[my_user_name]\.promptflow\temp\new_AzureOpenAI_connection.yaml -o C:\Users\[my_user_name]\AppData\Local\Temp\pf-upsertConnection-[uuid].json`

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a chat flow in Azure portal, replace LLM with a Python function with AzureOpenAIConnection as input
2. The code shows the correct API key from `print(repr(aoai_connection.api_key))`
3. Download the project and run with "pf flow test --flow .", the code shows the file paths above.

**Expected behavior**
We expect the consistent behavior for Azure portal and local run

**Running Information(please complete the following information):**
 - promptflow: 0.1.0b7.post1
 - promptflow-tools: 0.1.0b6
 - Operating System: Windows 11
 - Python: 3.10.12

**Comment by brynn-code** [comment]
Sorry I didn't repro the issue, my python tool looks like:
![image](https://github.com/microsoft/promptflow/assets/24237253/47f5875c-c355-4620-b706-b6f720814b31)
it can print the api key successfully: 
![image](https://github.com/microsoft/promptflow/assets/24237253/13cea9ed-ac6a-4abc-8fd8-db3b5a173f4d)
Is it convenient for you to share the flow folder for repro the bug?

**Comment by YusakuNo1** [comment]
It's very strange, the issue disappeared -- I deleted/recreated the local connections, and also downgrade/upgrade the PF locally before. Close the issue for now, if I can reproduce or got more details later, I'll update to the issue. Thanks for the investigation!
