### ISSUE TITLE
[Feature Request] Sample showing how to use Monitoring feature (preview) with promptflow

### ISSUE THREAD

**Issue by ouphi** [microsoft/promptflow#670]
**Is your feature request related to a problem? Please describe.**
I deployed a promptflow to an online endpoint, and I would like to continuously monitor the deployed model with the [Model monitoring (preview) feature](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-monitor-generative-ai-applications?view=azureml-api-2)). I tried to use it without success. Is this feature ready to be used with a promptflow registered model?

**Describe the solution you'd like**
Provide a sample showing how to use [Model monitoring (preview) feature](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-monitor-generative-ai-applications?view=azureml-api-2) on a promptflow deployed on an online-endpoint.

**Describe alternatives you've considered**
I tried to create a Monitor for a standard promptflow, but the step "Generation Safety & Quality - Signal Monitor
" fails with `Error encountered while attempting to get model type`.

**Comment by likebupt** [comment]
This is an internal user ran into failure when configure model monitoring. She already opened MDC.
Follow up with momo team.
