### ISSUE TITLE
[BUG] Vector DB Lookup tool does not use variables inside search_params field.

### ISSUE THREAD

**Issue by VeliKivilahti** [microsoft/promptflow#672]
**Describe the bug**
When using Vector DB Lookup tool, search_params field does not use the referenced variable as input. 
**How To Reproduce the bug**

1. Create an Vector DB Lookup tool.
2. Fill the information using https://microsoft.github.io/promptflow/reference/tools-reference/vector_db_lookup_tool.html#inputs as a reference. 
3. Add search filter {"search": "${question.output}"}
4. Observe how instead of the variable, the Vector DB Lookup tool uses the variable name as the search term.

**Expected behavior**
The search: field would be filled by the referenced variable when sent to Cognitive Search.

**Screenshots**

![image](https://github.com/microsoft/promptflow/assets/74296274/eb992d0b-dcb5-4632-8fd6-daa30eea4f5d)

Would expect it to work similar to vector:

![image](https://github.com/microsoft/promptflow/assets/74296274/84c6915a-9a48-419d-8f47-ba8ba2bbbf4e)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b6
 - Operating System: Windows 10
 - Python Version using `python --version`: Python 3.11.6

**Additional context**
Trying to do hybrid search with Azure Cognitive Search with the embedded question and the question text. Did not find from documentation how to refer to the question variable in the search parameter with the tool.

**Comment by henry-zeng** [comment]
@VeliKivilahti  according to the doc on the input of Azure Cognitive Search tool for vector lookup https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/tools-reference/vector-db-lookup-tool?view=azureml-api-2#inputs

and prompt flow input reference to output can be only refer to the step output directly without pre/post-fix, you can try change your upstream step **Rewrite_Question**  output format to "{search: }"

**Comment by VeliKivilahti** [comment]
Thank you, thought this might had been more of an user error / lack of understanding, Having a upstream jinja2 file with simply "search" : {{search_term}} (note: without the outer braces)  and submitting this as an input to the search_params output works.

Still would be nice for future updates to have this possible without needing upstream process as hybrid search is fairly common in retrieval process.
