### ISSUE TITLE
Support OpenAI-compatible APIs  for other endpoints [Feature Request]

### ISSUE THREAD

**Issue by whitelilis** [microsoft/promptflow#677]
**Is your feature request related to a problem? Please describe.**
For example I want to test LLaMa2 for AI application.

**Describe the solution you'd like**
I like promptflow treat  fastchat API which is OpenAI-compatible as a new endpoint.

**Describe alternatives you've considered**
Direct support huggingface model (auto its loading into a API endpoint) is perfect.

**Additional context**

**Comment by jiaochenlu** [comment]
Hi @whitelilis, we are about to launch a new tool named "**Open Source LLM**", which will accommodate Falcon or Llama2 in PromptFlow. This tool is set to be available next week. You can then refer to the tool documentation to utilize Llama2.
https://microsoft.github.io/promptflow/reference/tools-reference/open_source_llm_tool.html
