### ISSUE TITLE
[Feature Request] Transition from requirements.txt to pyproject.toml

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/promptflow#688]
**Is your feature request related to a problem? Please describe.**
The current codebase relies on `requirements.txt` for dependency management. This approach, while functional, might not be the most efficient, especially as we aim to foster collaboration in an open source environment.

**Describe the solution you'd like**
I suggest transitioning to the `pyproject.toml` setup using `poetry`. This will offer a more unified configuration, differentiate between build-time and run-time dependencies, and provide a more intuitive environment for developers familiar with modern Python packaging standards.

**Additional context**
Transitioning to `poetry` and `pyproject.toml` would not only modernize our setup but also make our project more inviting for contributors. A unified setup can lead to fewer configuration-related issues and a smoother onboarding experience for new developers.

**Comment by wangchao1230** [comment]
Thanks for the feedback!

We have already a pyproject.toml in repo but as you said we are not fully leveraging it: https://github.com/microsoft/promptflow/blob/main/src/promptflow/pyproject.toml

But for now as it's functional, we might not take imediate action on this. 
We will revisit this in future.

**Comment by wangchao1230** [comment]
Please note we have done migration to `pyproject.toml` using `poetry`, see : https://github.com/microsoft/promptflow/blob/main/src/promptflow-core/pyproject.toml
