### ISSUE TITLE
The built local app exists time limit for response (timeout of 60000ms exceeded)

### ISSUE THREAD

**Issue by plasmashen** [microsoft/promptflow#690]
**Describe the bug**
The built local app has time limit for response and it output: timeout of 60000ms exceeded

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. An agent function that requires longer running time (or time.sleep(60))

**Expected behavior**
Expected to allow function running longer than 1min

**Screenshots**
![bug](https://github.com/microsoft/promptflow/assets/40386089/e7552a34-3a1a-4350-bb71-fcbdbd32983a)

**Running Information(please complete the following information):**
 - Promptflow Package Version using 0.1.0b6
 - Operating System: Windows 11
 - Python Version using python==3.10.13

**Comment by ttthree** [comment]
@thy09 do we allow setting this timeout value? I thought the default is 6min ...

**Comment by rakeshmallik2003** [comment]
Loajfiuhf  hfdsfjh uik ygf sdfkl igsdafb 89 ayhapi ypa;hu p7auy rpafhap fyha;fyha  njoiashfa;ghfbvbdges   ujdnkjhdfbg;agh aghauoyghgIUYRtuewlqpotruf i g hn  sdf

**Comment by thy09** [comment]
@ttthree Confirmed that this is set by pf serving UX code, will increase it to 6 min in the next version.

**Comment by thy09** [comment]
Fixed in 1.0.0
