### ISSUE TITLE
[BUG] Tests May Not Count as Runs? 

### ISSUE THREAD

**Issue by mindlessroman** [microsoft/promptflow#695]
**Describe the bug**
This may be intended behavior, but I observed that if I run a test evaluation/aggregation flow using the python SDK, I cannot get the metrics of that run due to the return value

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a flow with an aggregation step.
    ```yaml
    # FILE: flow.dag.yaml
    # ...
    # The Aggregation step
    - name: aggregate
      type: python
      source:
        type: code
        path: step05_aggregate.py
      inputs:
        processed_results: ${concat_scores.output}
        variant_ids: ${inputs.variant_id}
      aggregation: true
    ```
    ```python
    # FILE: step05_aggregate.py
    from promptflow import tool, log_metric
    # other imports for calculating stats
    @tool
    def aggregate_score_results(processed_results: List[dict],
                                variant_ids: List[str],
                                threshold_value: float = 0.80,
                                minimum_stars: int = 3):
    # ...
    # doing the math and stats
    # ...
    
    # Log the metrics
    log_metric(key="ada_cosine_similarity", value=ada_cosine_pct, variant_id=variant)
    log_metric(key="f1_score", value=f1_pct, variant_id=variant)
    log_metric(key="gpt_relevance", value=gpt_relevance_pct, variant_id=variant)
    log_metric(key="gpt_similarity", value=gpt_similarity_pct, variant_id=variant)
    log_metric(key="sbert_similarity", value=sbert_pct, variant_id=variant)

    return SOME_RESULTS
    ```
2. Do a test run in a python notebook with the CLI:
    ```python
    # Jupyter Cell
    agg_eval_inputs = {
        "question": TEST_QUESTION, 
        "groundtruth": EVAL_TEST_GROUNDTRUTH,
        "prediction": EVAL_TEST_PREDICTION,
        "variant_id": "test_variant"
    }
    agg_eval_test_result = pf.test("explore-answer-eval-agg", inputs=agg_eval_inputs)

    print("The aggregate evaluation output:", agg_eval_test_result)
    ```
    ```text
    $ The aggregate evaluation output: {'results': {'ada_similarity': 0.959586792120976, 'f1_score': 0.5, 'gpt_relevance': 5, 'gpt_relevance_pass_rate': 1, 'gpt_similarity': 5, 'gpt_similarity_pass_rate': 1, 'sbert_similarity': 0.8725967407226562}}
    ```
3. Try to get the metrics:
    ```python
    # Jupyter Cell
    pf.get_metrics(agg_eval_test_result)
   ```
4. Get an error instead:
    ```text
    .... # stack trace
    InvalidRunError: Invalid run {'results': {'ada_similarity': 0.959586792120976, 'f1_score': 0.5, 'gpt_relevance': 5,
    'gpt_relevance_pass_rate': 1, 'gpt_similarity': 5, 'gpt_similarity_pass_rate': 1, 'sbert_similarity': 0.8725967407226562}}, 
    expected 'str' or 'Run' object but got <class 'dict'>.
    ```

**Expected behavior**
I'd expect a test have a similar behavior to a run. However, if this is intended behavior, then having a note somewhere that one can't get metrics 

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: `0.1.0b6`
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]: Mac 14.0 
 - Python Version using `python --version`: `python==3.9.17`

**Additional context**
Using `0.1.0b6` because I had an installation dependency conflict with 0.1.0b7. Using `python==3.9.17` to abide by the initial request for using 3.9 by documentation

**Comment by ttthree** [comment]
Thanks for reporting this @mindlessroman, you're right the pf.test() doesn't return a "run" while pf.get_metrics expects a run as argument. For your case seems the "agg_eval_test_result" already contains the metrics you try to output.

@eniac871 to consider how to make this more explicit, maybe a doc improvement?

**Comment by mindlessroman** [comment]
Having the metrics available for observability would be great, but it works fine during a regular run. 

+1 for doc improvement

**Comment by eniac871** [comment]
Add @0mza987  to follow up the doc update

**Comment by 0mza987** [comment]
I have update the doc, see https://github.com/microsoft/promptflow/pull/737

**Comment by mindlessroman** [comment]
Looks amazing! Thank you @0mza987 !!!
