### ISSUE TITLE
[BUG] Metrics with More than One Variant

### ISSUE THREAD

**Issue by mindlessroman** [microsoft/promptflow#696]
**Describe the bug**
Based on the [unit test for `test_log_metric`](https://github.com/microsoft/promptflow/blob/793794b9bafcfe2a43d12000f6640e8e34ef1dd2/src/promptflow/tests/executor/unittests/_core/test_metric_logger.py#L29), my presumption is that if you have multiple variants logged, the results would be rendered much like this unit test. Sadly, it does not.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Have a dataset that has multiple variants in their `data.jsonl`-ish file.
2. Run through an aggregation flow (see issue #695 for the code snippets I used, including the `log_metric()` lines).
    ```python
    # Jupyter Cell
    agg_eval_run = pf.run(
        flow=agg_eval_path, # whatever the path is
        data=eval_data_path, # the path where the data is
        run=run_result, # a previous standard flow run
        column_mapping={
            "question": "${data.question}",
            "groundtruth": "${data.groundtruth}",
            "prediction": "${run.outputs.answer}",
            "variant_id": "${data.variant_id}"
        },
        display_name="Aggregate Evaluation of Flow Run",
        stream=True,
    )
    ```
3. Call the `pf.get_metrics()` function on the run.
    ```python
    # Jupyter Cell
    import json
    agg_metrics = pf.runs.get_metrics(agg_eval_run) 
    print(json.dumps(agg_metrics, indent=4))
    ```
4. Get the result:
    ```jsonc
    // the result
    {
        "ada_cosine_similarity": 0.XX,
        "f1_score": 0.XX,
        "gpt_relevance": 0.XX,
        "gpt_similarity": 0.XX,
        "sbert_similarity": 0.XX
    }
    ```

**Expected behavior**
Based on the unit test, I would expect something more like (the "numbers" here are just placeholders): 
```json
{
    "ada_cosine_similarity": {
        "variant_0": 0.XX,
        "variant_1": 0.XX
    }, 
    "f1_score": {
        "variant_0": 0.XX,
        "variant_1": 0.XX
    },
    "gpt_relevance": {
        "variant_0": 0.XX,
        "variant_1": 0.XX
    },
    "gpt_similarity": {
        "variant_0": 0.XX,
        "variant_1": 0.XX
    },
    "sbert_similarity": {
        "variant_0": 0.XX,
        "variant_1": 0.XX
    }
}
```

Is the unit test outdated? Or is this a bug?

**Screenshots**

**Running Information(please complete the following information):**
- Promptflow Package Version using pf -v: `0.1.0b6`
- Operating System: [e.g. Ubuntu 20.04, Windows 11]: Mac 14.0
- Python Version using python --version: `python==3.9.17`

**Additional context**
Using 0.1.0b6 because I had an installation dependency conflict with 0.1.0b7. Using python==3.9.17 to abide by the initial request for using 3.9 by documentation

**Comment by mohanpatel6677** [comment]
super

**Comment by zhengfeiwang** [comment]
Hi @mindlessroman , thanks for your feedback!

If you want to tune different variants, you need to declare it(them) in `flow.dag.yaml`, you can refer to our doc: [Tune prompts using variants](https://microsoft.github.io/promptflow/how-to-guides/tune-prompts-with-variants.html) for details.

**Comment by mindlessroman** [comment]
> Note that in current design, there will be only one variant in each run, so the metrics will not be logged as your expectation.

Ah, okay! I had originally been using it in an aggregation step, so if I were to want to use the `log_metric()` I'd likely need to use it in a standard flow instead?

As for current design, does that unit test need updating to reflect current expectations? Or is there a plan for this later?

Thank you so much for following up!

**Comment by zhengfeiwang** [comment]
`log_metric()` should be available for all aggregation step, so there won't be limit on flow type.

Actually, we will ignore the `variant_id` parameter in our code for now; however, we still keep that in function signature for some legacy usage - sorry about that, and we will remove that once it is totally deprecated.

For the test you mentioned, I understand we are talking about the last line. There is one custom logging function defined here: https://github.com/microsoft/promptflow/blob/793794b9bafcfe2a43d12000f6640e8e34ef1dd2/src/promptflow/tests/executor/unittests/_core/test_metric_logger.py#L36-L37 so the logged metrics will look a little bit different with normal `log_metric()`.

Though the test leads to some confusion, but I think you can somehow refer from it to make the metrics work for your case? So that you can get metrics with variant id in it.
