### ISSUE TITLE
[BUG] Cannot create a Azure open AI connection through Prompt flow UI

### ISSUE THREAD

**Issue by samithaj** [microsoft/promptflow#724]
**Describe the bug**
Cannot create a Azure open AI connection through Prompt flow UI

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a "Standard flow" in prompt flow
2. Try to add a Azure openAI connection by clicking "Add connection"
![image](https://github.com/microsoft/promptflow/assets/1928352/5fafbfbd-5d4e-4f4a-94ac-92f6b9e734c9)

screen keeps blinking and doesn't load the connection details page
**Expected behavior**
should load the Azure open AI connection form
**Screenshots**

**Running Information(please complete the following information):**
- Brower- tested with chrome and Edge
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [  Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

**Comment by wyl765** [comment]
@samithaj thanks for reporting, we will fix this bug. BTW, since this is AML Studio prompt flow issue, you can open ocv to us for AML Studio prompt flow issue in the future.
