### ISSUE TITLE
[Feature Request] Hard to recognize input and output connections for new node

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#731]
**Is your feature request related to a problem? Please describe.**
Adding a new node sometimes renders a flow graph where it's hard to recognize input to and output from the new node.
![image](https://github.com/microsoft/promptflow/assets/5781796/8b84ec43-19cd-4b19-b728-18dfc831f814)

**Describe the solution you'd like**
Something like this (after auto layout) would be nice
![image](https://github.com/microsoft/promptflow/assets/5781796/5dc6ac77-db0e-48cb-809d-c86e687cbb13)

**Describe alternatives you've considered**

**Additional context**

**Comment by Linalooo** [comment]
Very Helpul Info . we need People Like You in this World . I am Inspried From Some of those Give Me the Best Info Like My Teacher Shaan Sir He has not physically with Me . But He teach me [Quran ](https://ayeshaquranacademy.com/)With the Best Way . Thanks to him and You

**Comment by JYC-99** [comment]
We fixed this with the extension release for version 1.12.0
