### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kacha2008** [microsoft/promptflow#735]
**Describe the bug**
A clear and concise description of the bug.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1.

**Expected behavior**

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by ttthree** [comment]
seems to be created by mistake.
