### ISSUE TITLE
[BUG] Workspace CustomConnection secrets cannot be retrieved

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#749]
**Describe the bug**
Unable to retrieve secrets in a CustomConnection created in AML workspace.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a CustomConnection in AML workspace:
   ![image](https://github.com/microsoft/promptflow/assets/5781796/1a05e998-03b3-4f31-a44d-2d9626b4f344)
2. Set default connection to workspace by `pf config set connection.provider="azureml:/...`
3. Try to retrieve secrets
   ![image](https://github.com/microsoft/promptflow/assets/5781796/63ddd6b2-7dc6-4655-baf2-4924683dfbec)

**Expected behavior**
Secrets in CustomConnection can be retrieved.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b7.post1
 - Operating System: Windows 10
 - Python Version using `python --version`: Python 3.9.18

**Additional context**

**Comment by brynn-code** [comment]
@Anbang-Hu This is a by-design behavior, when list and get connection from workspace, secrets (the whole key-value pairs) will not be returned by service thus can't be shown, but it will not block the flow execution, when execute the flow, promptflow will call the ARM api to get the connections with secrets, this call requires user action permission.
