### ISSUE TITLE
[BUG] [examples][flow-with-symlinks] same code like [web-classification]

### ISSUE THREAD

**Issue by lingfengchencn** [microsoft/promptflow#760]
**Describe the bug**
the code `promptflow/examples/flows/standard/flow-with-symlinks/flow.dag.yaml` is copy from web-classification??

**Comment by lalala123123** [comment]
Hi @lingfengchencn , flow.dag.yaml in flow-with-symlinks is copied from web-classification.
flow-with-symlinks and web-classification are the same flow structure. You need to execute "create_symlinks.py" in flow-with-symlinks to create symlinks referencing the tool scripts in web-classification.

**Comment by lalala123123** [comment]
It is by design.
