### ISSUE TITLE
[BUG] "+add a connection" button in Web UI causes screen to flash and no sidebar to appear

### ISSUE THREAD

**Issue by ian-t-adams** [microsoft/promptflow#768]
**Describe the bug**
Clicking the "+ add a connection" button inside the Web Portal based UI causes the sidebar that should open to repeatedly flash on-and-off the screen and renders the entire process unusable until you refresh the screen. Clicking again after refreshing only causes the issue to happen again.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Open a Chromium based browser (only browsers tested so far, others may have the same issue)
2. Log into https://ml.azure.com/
3. Start a new prompt flow (Chat used in tests)
4. See Figure 1 

click on "+ add a connection" to try and add a new connection to an AOAI endpoint (or any endpoint).
5. Proceed to enjoy your epilepsy test, free of charge, as your screen flashes at you rapidly while trying to open the sidebar that contains the fields to enter the connection information.

**Expected behavior**
A sidebar window to open that looks like Figure 2, or similar for other connection types.

**Screenshots**
Figure 1: <img width="565" alt="image" src="https://github.com/microsoft/promptflow/assets/106187595/9f5d6713-114e-4481-9f9f-6ccdbf2f66ff">
Figure 2: <img width="326" alt="image" src="https://github.com/microsoft/promptflow/assets/106187595/97347dec-f39f-4b65-ae3e-81dcf6411739">

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

**Comment by wyl765** [comment]
Thanks @ian-t-adams for reporting the issue. We already fixed this issue and pending release. For workaround, you can create a connection from prompt flow home page. 
![image](https://github.com/microsoft/promptflow/assets/834505/06c63441-bffe-4a9f-b51b-78fd07320361)
