### ISSUE TITLE
[BUG] [VSCode Extension] Generating tool meta... forever

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#769]
**Describe the bug**
When creating a new python node, visual editor could get stuck in Generating tool meta... Close and reopen visual editor can solve the issue.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:

This is not always reproducible. It happens occasionally.

![image](https://github.com/microsoft/promptflow/assets/5781796/e5e8b5df-4b50-4281-8596-159837e473e6)
![image](https://github.com/microsoft/promptflow/assets/5781796/2ae19928-3512-4598-8d9e-81dd9b23c515)

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
2. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: 0.1.0b7.post1
 - Operating System: Windows 10
 - Python Version using `python --version`: Python 3.9.18
 - VS Code version. v1.0.12
 - Prompt Flow extension version.
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by naiyunzhang** [comment]
Hi, @Anbang-Hu  Are there any spaces in your directory? I have fixed a similar issue caused by that. Can you try the latest version of the extension 1.1.2?

**Comment by Anbang-Hu** [comment]
@naiyunzhang , I can't repro any more.

**Comment by tyler-suard-parker** [comment]
I found this happens when there is an error in my file where the promptflow tool is defined.  For example if I am using a python script and defining a tool there, and there is a mismatch between the inputs in the yaml and the inputs in my tool function, the generating tool meta will time out.
