### ISSUE TITLE
[Feature Request] Python SDK, pf.show() to get run meta info

### ISSUE THREAD

**Issue by lisagreenview** [microsoft/promptflow#771]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

In pf CLI, we have `pf run show -n <run_name>` to get run meta information, but in Python SDK, pf.show(run) is not available, we can provide similar functionality.
![CleanShot 2023-10-14 at 09 18 51@2x](https://github.com/microsoft/promptflow/assets/10419778/9bc3b64c-31da-4a07-96e5-6b0be355696a)

**Describe the solution you'd like**

Have pf.show(run) to get run meta info.

**Describe alternatives you've considered**

**Additional context**

**Comment by 0mza987** [comment]
There is an equivalent in SDK funciton `pf.runs.get()`, please refer to:
[Python Library Reference](https://microsoft.github.io/promptflow/reference/python-library-reference/promptflow.azure.operations.html). It returns a `Run` object that contains the run's meta info.
