### ISSUE TITLE
[BUG] No module named 'azure.storage'

### ISSUE THREAD

**Issue by jimmy-nhk** [microsoft/promptflow#775]
**Describe the bug**
I have a bug related to prompt flow when tried to create vector index in VSCode.
Flow test failed with ResolveToolError: Tool load failed in 'search_question_from_indexed_docs': (ToolLoadError) Failed to load package tool 'Vector Index Lookup': (ModuleNotFoundError) No module named 'azure.storage'

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create the whole flow first 
2. Include the vector index
3.  Run the whole prompt flow

**Expected behavior**
It should run without any errors

**Screenshots**
<img width="266" alt="image" src="https://github.com/microsoft/promptflow/assets/56537411/290151a0-baeb-43fb-b8ed-f685a56db418">
<img width="686" alt="image" src="https://github.com/microsoft/promptflow/assets/56537411/a84a3b9e-bf18-4a92-8053-2adec8107613">

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b7.post1
 - Operating System: MacOs Monterey
 - Python Version using `python --version`: python==3.10

**Additional context**
This is urgent. Please help me on this

**Comment by jimmy-nhk** [comment]
@huaiyan could you help me look on this?

**Comment by jimmy-nhk** [comment]
After that, I degrade the version of promptflow and promptflow-tools to 0.1.0b5. It solved the problem but creates another error 👎🏻 . 
<img width="711" alt="image" src="https://github.com/microsoft/promptflow/assets/56537411/ca23344c-73cb-474c-8b7b-05c2b1b7475d">

I tried with different version of azure cli but did not work as well, please help me

**Comment by ttthree** [comment]
@jimmy-nhk please use the latest promptflow and promptflow-tools package. And would you mind try `pip install promptflow-vectordb` in your local env and see if that helps?

It worked for me.

@eniac871  do you know why we didn't include promptflow-vectordb in the requirements.txt of our Bring your own data for chat sample?

**Comment by jimmy-nhk** [comment]
> @jimmy-nhk please use the latest promptflow and promptflow-tools package. And would you mind try `pip install promptflow-vectordb` in your local env and see if that helps?
> 
> It worked for me.
> 
> @eniac871 do you know why we didn't include promptflow-vectordb in the requirements.txt of our Bring your own data for chat sample?

I did install promptflow-vectordb already, but I don't know I keep getting the message of az_login related to vectordb.

**Comment by ttthree** [comment]
@jimmy-nhk  to confirm - is your flow downloaded from Azure ML (the Bring your own data chat sample) and you try to run it locally?
Note that our sample is depending on an index on Azure so require you to have Azure logon etc.

![CleanShot 2023-10-17 at 14 58 03@2x](https://github.com/microsoft/promptflow/assets/18907/c6322729-1bb5-4a06-b297-d3138495c289)

I tried `az logout` then i got something like this:

![CleanShot 2023-10-17 at 14 59 08@2x](https://github.com/microsoft/promptflow/assets/18907/841003ad-e4a9-4b35-b0ec-0917a9f97daa)

**Comment by 0mza987** [comment]
I have repro-ed this bug, the root cause is that this flow uses tool "promptflow_vectordb.tool.vector_index_lookup.VectorIndexLookup.search", it requires dependency of "azure.storage", but if you installed the package "promptflow-vectordb" with "pip install promptflow-vectordb" (note there is no [azure] suffix), so there is no azure related dependency and it will raise error: No module named 'azure.storage'
 
Here comes 3 possible situations:
- This tool by-design requires azure dependency. Then customer can install with "pip install promptflow-vectordb[azure]" to fix this issue and this is not a bug.
- This tool by-design does not require azure dependency. Then it's a bug in promptflow-vectordb code that it should not execute the part that imports azure storage dependency.
- This tool by-design does not require azure dependency, but when the input is a remote blob link, it requires azure dependency. Then customer can install with "pip install promptflow-vectordb[azure]" to fix this issue and this is not a bug.

We are confirming with vectordb owner which situation is the case here.

**Comment by 0mza987** [comment]
Have confirmed with vectordb owner, it's the third situation:
- This tool by-design does not require azure dependency, but when the input path is a remote blob link, it requires azure dependency. Then customer can install with `pip install promptflow-vectordb[azure]` to fix this issue and this is not a bug

Unfortunately even if I installed the azure dependencies, this step still fails with error:

>  Tool load failed in 'search_question_from_indexed_docs': (ToolLoadError) Failed to load package tool 'Vector Index Lookup': (FileNotFoundError) [Errno 2] No such file or directory: 'C:\\Users\\hod\\AppData\\Local\\Temp\\tmp7y89ogbb\\MLIndex'

![image](https://github.com/microsoft/promptflow/assets/2572521/d96cc288-5894-4dad-a8cd-78dc69a6db45)

Also confirming this error with vectordb owner.

**Comment by eniac871** [comment]
@ttthree  regarding to the package dependency in requirements.txt, when the sample run in AzureML workspace, the runtime already installed these packages so the problem doesn't exist. We will address the issue to make sure samples work when user  download it to local.

**Comment by khangNgRackSpace** [comment]
> @jimmy-nhk to confirm - is your flow downloaded from Azure ML (the Bring your own data chat sample) and you try to run it locally? Note that our sample is depending on an index on Azure so require you to have Azure logon etc.
> 
> ![CleanShot 2023-10-17 at 14 58 03@2x](https://user-images.githubusercontent.com/18907/275738906-c6322729-1bb5-4a06-b297-d3138495c289.png)
> 
> I tried `az logout` then i got something like this:
> 
> ![CleanShot 2023-10-17 at 14 59 08@2x](https://user-images.githubusercontent.com/18907/275739113-841003ad-e4a9-4b35-b0ec-0917a9f97daa.png)
> 
> so if you `az login` successfully then you should be able to run your flow.

I did try to log in but it keeps requiring me to log in. I don't know why

**Comment by 0mza987** [comment]
I have opened a new issue to address the `MLIndex` not found issue:
https://github.com/microsoft/promptflow/issues/808
