### ISSUE TITLE
[BUG] [VSCode Extension] Custom Connections in AML Workspace Do Not Show Up in Drop Down

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#790]
**Describe the bug**
After setting `pf config set connection.provider="azureml:/subscriptions/<your-subscription>/resourceGroups/<your-resourcegroup>/providers/Microsoft.MachineLearningServices/workspaces/<your-workspace>"`, connection dropdown list shows nothing:
![image](https://github.com/microsoft/promptflow/assets/5781796/77fd0529-43e4-4667-9276-8b9633d5801f)

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a custom connection in AML workspace
2. Configure provider to AML workspace
3. Create an LLM node, connection dropdown list shows nothing.

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
4. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]
 - VS Code version.
 - Prompt Flow extension version.
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by JYC-99** [comment]
Fixed with version 1.1.2.
