### ISSUE TITLE
[BUG] [VSCode Extension] Meta file not founnd due to Windows path delimiter on Linux

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#791]
**Describe the bug**
When we develop on Windows machine, path delimiter is `\`, but our CI is a Linux machine. (Users can also run on Linux)
```
{
      "message": "Meta file not found, path '....my_prompt.jinja2', type 'prompt'.",
      "path": "nodes.0.source.path",
      "value": "prompts\\my_prompt.jinja2",
      "location": ".../flow.dag.yaml"
    }
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Create a Prompt node and give a Windows input path.
2. Run the flow on Linux machine

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
3. Please provide other snapshots about the key steps to repro the issue.

**Environment Information**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]
 - VS Code version.
 - Prompt Flow extension version.
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by JYC-99** [comment]
Fixed with version 1.1.2.
