### ISSUE TITLE
[BUG] Unable to install latest pip python packages due to Prompt Flow SDK Docker base image.

### ISSUE THREAD

**Issue by Leonwatsoni** [microsoft/promptflow#801]
**Describe the bug**
I want to access the latest version of Langchain in Prompt Flow. When I run `langchain.__version__` it always defaults to the one specified in the Prompt Flow base image (`langchain==0.0.236`). Even when my docker file specifically selects a different version (`RUN pip install langchain==0.0.300`), it always go to the older version.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. DOCKER IMAGE
```
FROM mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:latest

ENV APP_DIR=/code
ENV PYTHONUNBUFFERED 1
WORKDIR $APP_DIR
RUN apt-get update
COPY ./requirements.txt $APP_DIR/requirements.txt
RUN pip install --no-cache-dir --upgrade -r $APP_DIR/requirements.txt

```
2. RUN IN PROMPT FLOW UI
```
import langchain
print(langchain.__version__)
```

**Expected behavior**
output: 0.0.236

**Running Information(please complete the following information):**
 mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:latest

**Comment by Leonwatsoni** [comment]
after killing the compute instance and creating a brand new one (because restarting it was not enough) it now works properly.

**Comment by zhohuang** [comment]
Cannot reproduce the bug with the dockerfile provided and the dockerfile
`
FROM mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:latest
RUN pip install langchain==0.0.300
`

They both return langchain version = 0.0.300 when run in promptflow UI
