### ISSUE TITLE
[Feature Request] Fill in Default Values By Default When Adding Custom Tool to Flow

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#824]
**Is your feature request related to a problem? Please describe.**
Custom defined tool with default values in yaml spec don't have those default values actually filled in when adding them to flow
![image](https://github.com/microsoft/promptflow/assets/5781796/66bb99ae-7b08-42a2-941e-2ab529846cff)
Even though the values show up, the textboxes are blank.
Users have to type again even they want to use the default values.

**Describe the solution you'd like**
It would be helpful if these default values are actually filled in.

**Describe alternatives you've considered**

**Additional context**

**Comment by JYC-99** [comment]
You do not have to fill in those values. Leave them empty and PF executor will hornor the default values.
And we do not prefer UX to do auto filling unless users send explicit signal to ask to change flow content.
