### ISSUE TITLE
[BUG] The guidance link of column-mapping is not match between error message and actual link

### ISSUE THREAD

**Issue by eniac871** [microsoft/promptflow#826]
**Describe the bug**
A clear and concise description of the bug.

**How To Reproduce the bug**
1. Use a wrong column mapping and create a batch run
2. We can see the error which contains a link of how to use column mapping
3. While the link is wrong which will direct to a page 404. The right page has a "use-" in the page name https://github.com/microsoft/promptflow/blob/main/docs/how-to-guides/use-column-mapping.md
**Expected behavior**
User can see the right page from the error message

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/15699380/dc7fd8de-d466-4231-a64b-e2f1b92a5ad9)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

**Additional context**

**Comment by huaiyan** [comment]
We improved doc name and link in this PR last week.
[[Doc] Add global config doc by brynn-code · Pull Request #651 · microsoft/promptflow (github.com)](https://github.com/microsoft/promptflow/pull/651/files)

Will fix the error message soon.

**Comment by huaiyan** [comment]
[Fix PR](https://github.com/microsoft/promptflow/pull/830) has been merged.
