### ISSUE TITLE
[Feature Request] Enforce same naming rules in flow dag and AML component

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#828]
**Is your feature request related to a problem? Please describe.**
Flow template produces `flow.dag.yaml` with `name: Template Standard Flow`, but it will cause problems when we load it as a component:
```bash
Component name should only contain lower letter, number, underscore and start with a lower letter. Currently got Template Standard Flow
```

**Describe the solution you'd like**
Enforce the same naming rules in flow and component.

**Describe alternatives you've considered**

**Additional context**

**Comment by lalala123123** [comment]
In the latest version 0.1.0b7.post1, the name in the template has been removed
