### ISSUE TITLE
[Feature Request] Support for other LLMs

### ISSUE THREAD

**Issue by seankovacs** [microsoft/promptflow#829]
**Is your feature request related to a problem? Please describe.**
Currently PF only supports ChatGPT via OpenAI or Azure.

**Describe the solution you'd like**
It would be nice if there was a way to add a custom connection to support other LLMs, such as Vertex-AI's PaLM 2 LLM.

**Comment by chjinche** [comment]
Hi @seankovacs thanks for sharing this feature request, looks you're looking for a way to integrate additional large language models beyond OpenAI or Azure OpenAI into Prompt flow. Our [Open Source LLM](https://github.com/microsoft/promptflow/blob/main/docs/reference/tools-reference/open_source_llm_tool.md) tool may offer a solution here. It allows you to utilize a variety of Open Source and Foundational Models. 

Maybe you could try out the Open Source LLM tool to see if it enables using your preferred language model. The docs have guidance on configuration and usage. Let us know if you run into any issues getting it set up. We're happy to help troubleshoot.

Thanks again for the feedback. Expanding Prompt flow's LLM integrations is on our roadmap. Please feel free to share if you have any other feature requests related to it!

CC: our expert @gjwoods

**Comment by faaany** [comment]
Hi @chjinche @gjwoods, would you guys consider LLMs on Hugging Face?

**Comment by prakharg-msft** [comment]
Hi @faaany , thanks a lot for sharing your feedback. Is there any particular model on Hugging Face Hub that you are interested in?  The [Open Source LLM](https://github.com/microsoft/promptflow/blob/main/docs/reference/tools-reference/open_source_llm_tool.md) tool today support Falcon, llama and dolly models.

**Comment by faaany** [comment]
> Hi @faaany , thanks a lot for sharing your feedback. Is there any particular model on Hugging Face Hub that you are interested in? The [Open Source LLM](https://github.com/microsoft/promptflow/blob/main/docs/reference/tools-reference/open_source_llm_tool.md) tool today support Falcon, llama and dolly models.

Hi @prakharg-msft , I am using `HuggingFaceH4/zephyr-7b-beta` in my application. Can I use directly from Hugging Face instead of from [Azure Machine Learning model catalog](https://ml.azure.com/model/catalog)?
