### ISSUE TITLE
[Feature Request] [VSCode Extension] Display results of run in UI

### ISSUE THREAD

**Issue by ArtyomZemlyak** [microsoft/promptflow#889]
**Is your feature request related to a problem? Please describe.**
Now to watch results of run we need use cli tool to `visualize` run into html file, which saved in tmp folder.
And in my case its not opened by default. 

**Describe the solution you'd like**
Option in `VSCode Extension` UI for watch results of specific run.

Also interesting additional possible features for UI in `VSCode Extension`:

1. Combine runs (with showing diffirence between)
2. Compare runs (like punct 1, but spificaly for comparing two or more runs side by side) (for reference - `ClearML` comparing experiments)
3. Foldered/tags structure for runs
4. Renaiming runs
5. Integrations with tools for experimemt tracking (`ClearML` for example, which can visualize html)

**Comment by JYC-99** [comment]
![image](https://github.com/microsoft/promptflow/assets/5934735/be9b108d-ba6f-4eba-9e83-be3207c53261)
You can select one or more items in the runs list, and there will be an option on the top right to visualize run(s).
