### ISSUE TITLE
[Feature Request] [VSCode Extension] Creating and Configuring tools in VSCode Extension UI

### ISSUE THREAD

**Issue by ArtyomZemlyak** [microsoft/promptflow#890]
**Is your feature request related to a problem? Please describe.**
At the moment it is not very convenient to switch between the VSCode Extension and cmd to create tools.
Now we need to run a few CLI commands to create a new custom tool.

**Describe the solution you'd like**
It would be very helpful if the same functionality for creating and configuring tools could be achieved using the VSCode Extension UI.

**Comment by eniac871** [comment]
Thanks for the suggestion, we have some ongoing works to improve the experience of this. The first version of 'pf tool init' will be available in next realease. @ArtyomZemlyak  please take a look whether the behavior described in this PR's doc works for your requirement: https://github.com/microsoft/promptflow/pull/882 . Meanwhile we're also working on keep improving this and switch VSCode extension to leverage the newly added command

**Comment by ArtyomZemlyak** [comment]
Thanks for reply!
Yes, PR's doc seems promising!
