### ISSUE TITLE
[Feature Request] HUB for tools

### ISSUE THREAD

**Issue by ArtyomZemlyak** [microsoft/promptflow#891]
**Is your feature request related to a problem? Please describe.**
For starting point a little amout of tools provided.

**Describe the solution you'd like**
It will be very useful if some kind of HUB for tools is launched (if this can be done through the VSCode Extension UI - it will be very good!)

**Comment by eniac871** [comment]
We have some doc site update to add a place to explore some of the tools not owned by prompt flow team. @jiaochenlu  @ChenJieting  please help provide the update of adding the docs of this.

**Comment by jiaochenlu** [comment]
Hi @ArtyomZemlyak , we do have a tool hub page to collect all integrated custom tools. Integration here means that you **contribute a one-page document** of your built custom tool to our doc site, and then the doc page index will be in Listed here -- https://microsoft.github.io/promptflow/integrations/tools/index.html 
For maintenance flexibility, we recommend that custom tool owners host such documentation separately in their own repository. If the doc repo is not ready yet, you can add such a page of doc introducing the tool package under: [promptflow/integrations/tools](https://microsoft.github.io/promptflow/integrations/tools/index.html).

In addition, we now have a feature that we are working on, which is to support access to this central page in the vscode extension tool list.
