### ISSUE TITLE
[Feature Request] Provide ability to create variants for other tools/multiple tools and use more than one variant within an execution

### ISSUE THREAD

**Issue by pragmatical** [microsoft/promptflow#908]
**Is your feature request related to a problem? Please describe.**
I am currently very limited in how much variation in terms of variants I can have in a flow.

**Describe the solution you'd like**
When building out a flow, I may want to have multiple variations for things other than one single LLM node.  For example, I might want to have variations for system prompt, as well as variations for fewshots to be added to prompt.  In addition, I might want to experiment with calls to different services, maybe different search indexes, or different external services.   It would be useful to have support for variations of any tool.

Once we have multiple variants, it would be necessary to be able to create variations of the flow that can use any combination of the defined variants for all tools.

**Describe alternatives you've considered**

**Additional context**

 No.| Desired Functionality
-- | --
1 | I want the ability to multiple variations of the following items for a prompt: System prompt, Additional messages to use as examples  (single shot, few shot)
2 | I want to be able to provide different variations of values for the following items for the call to the OpenAI model:model,frequency_penalty,presence_penalty,stop,temperature,top_p,max_tokens,function_call,functions,logit_bias
3 | I want to be able to use different variations of external services leveraged by OpenAI based endpoint - example - if my endpoint uses speech to text, I would like to be able to have variants that use different speech to text services (WhisperAPI, Azure speech2text, etc.)
4 | I want to be able to create endpoint variants that capture any combination of the customized settings mentioned  in desired functionality 1,2, and 3

**Comment by jiaochenlu** [comment]
@pragmatical 
Regarding your No.1 requirement, you can currently achieve this by dividing the single prompt node into multiple prompt nodes. For instance, you can have one node for the system prompt and another for the few-shot prompt, and then combine them in one prompt node downstream.

for your No.2, it's already feasible. You can create variations of your LLM node that calls OpenAI and set different configurations for each node variant.
![image](https://github.com/microsoft/promptflow/assets/32232238/6c47b877-beac-4dfe-abd8-09a5cf155719)


for your No.3, to call other AI endpoints? seems like you want to have the variants enabled on python tool or more other tool types as well, we will take this feature request into consideration and aim to develop a more comprehensive design.

for your No.4  I see that you've reported it in another issue. We have a work item to track this as a new feature request.
