### ISSUE TITLE
[BUG] SDK code example fails to run

### ISSUE THREAD

**Issue by mydmdm** [microsoft/promptflow#910]
**Describe the bug**
The code example of SDK in [Run and evaluate a flow](https://microsoft.github.io/promptflow/how-to-guides/run-and-evaluate-a-flow/run-and-evaluate-a-flow.html#create-a-batch-run)
```{python}
# Set flow path and run input data
flow = "standard/web-classification" # set the flow directory
data= "standard/web-classification/data.jsonl" # set the data file

# create a run, stream it until it's finished
base_run = pf.run(
    flow=flow,
    data=data,
    stream=True,
)
```
fails to run because `pf` if not defined

**Comment by eniac871** [comment]
When running it using SDK, please import the promptflow modules before calling it, 
`from promptflow import PFClient
pf = PFClient()` 
But we probably can make the example more robust to let users know that . Add @0mza987  to help follow up this
