### ISSUE TITLE
[BUG] [VSCode Extension] \n in fields in UI of VSCode Extension converted into \\n 

### ISSUE THREAD

**Issue by ArtyomZemlyak** [microsoft/promptflow#912]
**Describe the bug**
`\n` in fields in UI of `VSCode Extension` converted into `\\n`. And its not properly used in jinja templates after. And after rendering its visualized like this:
```
...
[chat]: ...Some text of prompt...<|im_end|>
[chat]: 
[chat]: \n<|im_start|>user\nHi!<|im_end|>
[chat]: \n<|im_start|>assistant\n
```

**How To Reproduce the bug**
Always

**Expected behavior**
`\n` not changed ant keeps to jinja template as is. (after rendering its not displayed in resulted text)
```
...
[chat]: ...Some text of prompt...<|im_end|>
[chat]: 
[chat]: 
[chat]: <|im_start|>user
[chat]: Hi!<|im_end|>
[chat]: 
[chat]: <|im_start|>assistant
```

**Comment by JYC-99** [comment]
Fixed with new release. Please keep your extension updated. Feel free to reopen if issue still exists.
