### ISSUE TITLE
[BUG] Problems with encoding and decoding in Chinese environment on Windows 10

### ISSUE THREAD

**Issue by bamboowind** [microsoft/promptflow#914]
**Describe the bug**
Problems with encoding and decoding in Chinese environment, when we use Chinese characers in the config file, 
there is an exception:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 507: illegal multibyte sequence

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. type in some Chinese characters in flow.dag.yaml
2. run the yaml file.

**Expected behavior**
No such exception.

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/231992/0ac1536e-b91a-46b5-b858-448861b62697)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b7.post1
 - Operating System: Windows 10 22H2
 - Python Version using `python --version`: Python 3.9.16

**Comment by lalala123123** [comment]
Hi @bamboowind , this bug has been fixed in the latest version. You can try this version 0.1.0b8
