### ISSUE TITLE
Compute 'not ready' when deploying custom environment

### ISSUE THREAD

**Issue by gauravAgile** [microsoft/promptflow#942]
I'm trying to create a runtime to use for the new prompt flow feature. I'm trying to use a custom environment for the runtime because I need additional python packages.

The environment builds without issue. However, when I try to create a runtime it always throws this error. I've tried several times to create new compute instances without success.

compute instance details I used :
 Standard_E8s_v3
8 cores, 64GB RAM, 128GB storage
100 cores
Memory optimized

This is the error I recieved:
UserError: FlowRuntime test in compute instance lms-prompt-flow-gb compute is not ready: runtime starting timeout. Please try to create a new compute instance to hold runtime

Can anyone please help me debug this error?

Following is the conda.yml of environment:
```
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.3.1
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - azure-core==1.29.4
      - azure-functions==1.17.0
      - azure-functions-durable==1.2.6
      - azure-storage-blob==12.18.3
      - beautifulsoup4==4.12.2
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.0
      - colorama==0.4.6
      - cryptography==41.0.4
      - dataclasses-json==0.6.1
      - exceptiongroup==1.1.3
      - filelock==3.12.4
      - frozenlist==1.4.0
      - furl==2.1.3
      - gdown==4.7.1
      - greenlet==3.0.0
      - idna==3.4
      - isodate==0.6.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.0.315
      - langsmith==0.0.43
      - marshmallow==3.20.1
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - numpy==1.26.1
      - openai==0.28.1
      - orderedmultidict==1.0.1
      - packaging==23.2
      - pycparser==2.21
      - pydantic==2.4.2
      - pydantic_core==2.10.1
      - PySocks==1.7.1
      - python-dateutil==2.8.2
      - PyYAML==6.0.1
      - requests==2.31.0
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - SQLAlchemy==2.0.22
      - tenacity==8.2.3
      - tqdm==4.66.1
      - typing-inspect==0.9.0
      - typing_extensions==4.8.0
      - urllib3==2.0.6
      - yarl==1.9.2
```

![image](https://github.com/microsoft/promptflow/assets/142978015/5a89cb92-5395-4acc-98fe-d82bd7fcee13)

**Comment by xiaolul** [comment]
I am having exactly the same problem. I am using the the latest prompflow image as the base image with additional pip requirements. 
Custom environment build in AML is working, but cannot create promptflow runtime.

**Comment by danigian** [comment]
I think we are encountering a similar issue with dynamic environments. Any idea?

```
Status code: 503 
Reason: Serverless compute is not ready in a fixed timespan, error: Container not started 
Error message: (SystemError) Serverless compute is not ready in a fixed timespan, error: Container not started
Code: SystemError
Message: Serverless compute is not ready in a fixed timespan, error: Container not started 
```

**Comment by doz-msft** [comment]
The issue should be related to mlflow compatibility issue with pydantic v2. See [[BUG] MLFlow 2.6.0 PydanticUserError when importing mlflow w/ latest pydantic version](https://github.com/mlflow/mlflow/issues/9331) for more details. Please update mlflow version (add "mlflow==2.7.1" to requirements.txt) as a temporary mitigation. We will update the version of promptflow image to fix the issue.

**Comment by danigian** [comment]
> The issue should be related to mlflow compatibility issue with pydantic v2. See [[BUG] MLFlow 2.6.0 PydanticUserError when importing mlflow w/ latest pydantic version](https://github.com/mlflow/mlflow/issues/9331) for more details. Please update mlflow version (add "mlflow==2.7.1" to requirements.txt) as a temporary mitigation. We will update the version of promptflow image to fix the issue.

Doesn't fix the issue on our side. We have no dependency on mlflow, and pydantic is on 1.10.13

**Comment by DaweiCai** [comment]
@danigian how did you create the customized env?  did you use the option "use existing docker image with optional conda file"? If so , it did not work currently and can you try with the option "Craete a new docker context"? 
![image](https://github.com/microsoft/promptflow/assets/10734523/e704814a-707a-45d7-b574-20d1005ce58e)

**Comment by gauravAgile** [comment]
Yes , creating a new docker context do work . We  yesterday had a meeting
with ms tech team and they told us that currently the conda environment
have some defects (internal bugs ) which needs to be fixed

**Comment by DaweiCai** [comment]
Great. I will close this bug.

**Comment by DaweiCai** [comment]
Issue been resolved.
