### ISSUE TITLE
[Feature Request] Adding input nodes to the output

### ISSUE THREAD

**Issue by farshadkt87** [microsoft/promptflow#978]
**Is your feature request related to a problem? Please describe.**
Right now for using the output in prompt flow I have to join the output to my input to get the matching of the input and output results. This is an extra step and it could introduce mistakes. 

**Describe the solution you'd like**
Ideally I want to be able to add some of the input columns to the output, but this is not supported right now.

**Describe alternatives you've considered**
Doing the join after the pipeline is finished

**Additional context**
NA

**Comment by lisagreenview** [comment]
Could you try this way? I tested and it works as expected:
![CleanShot 2023-11-02 at 21 50 44@2x](https://github.com/microsoft/promptflow/assets/10419778/d591a908-fbe7-479c-b630-efd925c59a23)

![CleanShot 2023-11-02 at 21 52 03@2x](https://github.com/microsoft/promptflow/assets/10419778/3ea8044f-d08e-4297-86f6-c09f1f27446a)

**Comment by Anbang-Hu** [comment]
The inputs is not available in the dropdown list. Can we make it visible there?
![image](https://github.com/microsoft/promptflow/assets/5781796/d40f459f-e255-4b86-b956-0bdee0c73954)

**Comment by farshadkt87** [comment]
Thanks this works as expected! As Anbang said it would be great to make that visible in the drop down, especially because when typing in the output column after typing each single character the text box becomes unselected and I have to click on it again.

**Comment by lisagreenview** [comment]
Sure, the client should make it easier.
