### ISSUE TITLE
[BUG] [VSCode Extension] Non latin characters are not properly displayed in output

### ISSUE THREAD

**Issue by Anbang-Hu** [microsoft/promptflow#979]
**Describe the bug**
If you have Arabic as part of the output, it's not displayed properly.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. 

**Screenshots**
![image](https://github.com/microsoft/promptflow/assets/5781796/5d6c3239-0035-4c1a-9e4d-1a4ca97c1850)

**Environment Information**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]
 - VS Code version.
 - Prompt Flow extension version.
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by lalala123123** [comment]
Hi @Anbang-Hu , it has been fixed in this PR #951. This change will be in the next release, in mid-November
