### ISSUE TITLE
[Feature Request] Make Node-Execution Conditional

### ISSUE THREAD

**Issue by T-Hipp** [microsoft/promptflow#988]
**Is your feature request related to a problem? Please describe.**
My execution graph is getting larger and to save execution time, I would like to not execute some nodes, if they are not needed - depending on some pre-conditions

**Describe the solution you'd like**
Have the option to not execute a node, depending on a previous node / variable / condition

**Describe alternatives you've considered**
I start to use more Python-Nodes and use conditional execution there

**Comment by ArtyomZemlyak** [comment]
I think you can achive this through `Activate config` in UI VSCode Extention.

**Comment by thy09** [comment]
@T-Hipp You may read this document for conditional flow: https://microsoft.github.io/promptflow/how-to-guides/add-conditional-control-to-a-flow.html

**Comment by thy09** [comment]
Close this issue since it is already supported.
